foundation-objs/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FB{00000}</displayFormat>
        <label>Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Feedback__c/fields/Feedback_Object__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Object__c</fullName>
    <label>Feedback Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Feedback__c/fields/Feedback_Owner__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feedback Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Feedback__c/fields/Need_Improvement__c.field-meta.xml
<CustomField>
    <fullName>Need_Improvement__c</fullName>
    <label>Need Improvement</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

foundation-objs/main/default/objects/Feedback__c/fields/Pluses__c.field-meta.xml
<CustomField>
    <fullName>Pluses__c</fullName>
    <label>Pluses</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

foundation-objs/main/default/objects/Feedback__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <label>Review</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

foundation-code/main/default/classes/CTX_FeedbackLogClass.cls
public without sharing class CTX_FeedbackLogClass {
    
    @AuraEnabled
    public static LogFeedbackReturnWrapper logFeedback(
        String 	objectName,
        String 	feedback,
        String 	pluses, 
        String 	needImprovement,
        Integer rating
    ){
        
        system.debug('currentRating: '+rating);
        LogFeedbackReturnWrapper thisResult = new LogFeedbackReturnWrapper();
        
        Feedback__c newfeedback = new Feedback__c(
            Feedback_Owner__c 	= UserInfo.getUserId(),
            Feedback_Object__c 	= objectName,
            Review__c 			= feedback,
            Pluses__c 			= pluses,
            Need_Improvement__c = needImprovement,
            Rating__c 			= rating
        );
        
        try{
            insert newfeedback; 
            thisResult.isSuccess = TRUE;
        } catch(Exception ex){
            system.debug('CTX_FeedbackLogClass Error: '+ex.getMessage());
            thisResult.errorMessage = ex.getMessage();
        }
        
        return thisResult;
    }
    
    Public Class LogFeedbackReturnWrapper{
        
        @AuraEnabled
        Public Boolean isSuccess = FALSE;
        
        @AuraEnabled
        Public String errorMessage;
    }
}