foundation-objs/main/default/objects/Account/fields/Agreement_Sign_Method__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Sign_Method__c</fullName>
    <label>Agreement Sign Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E-Sign</fullName>
                <default>true</default>
                <label>E-Sign</label>
            </value>
            <value>
                <fullName>Physical Sign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Account/fields/CC__c.field-meta.xml
<CustomField>
    <fullName>CC__c</fullName>
    <label>Esign CC Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Account/fields/E_Sign_Type__c.field-meta.xml
<CustomField>
    <fullName>E_Sign_Type__c</fullName>
    <label>E-Sign Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>aadhaar</fullName>
            </value>
            <value>
                <fullName>electronic</fullName>
                <default>true</default>
                <label>electronic</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Account/fields/Esign_Order__c.field-meta.xml
<CustomField>
    <fullName>Esign_Order__c</fullName>
    <label>Esign Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client First</fullName>
                <default>true</default>
                <label>Client First</label>
            </value>
            <value>
                <fullName>CTX First</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Account/fields/Master_admin_Email__c.field-meta.xml
<CustomField>
    <fullName>Master_admin_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Master admin Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

foundation-objs/main/default/objects/Account/fields/OTP_For_Electronic_Signature__c.field-meta.xml
<CustomField>
    <fullName>OTP_For_Electronic_Signature__c</fullName>
    <label>OTP For Electronic Signature</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>E_Sign_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>email</fullName>
                <default>true</default>
                <label>email</label>
            </value>
            <value>
                <fullName>mobile</fullName>
            </value>
            <value>
                <fullName>both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-code/main/default/classes/CTX_PartnerAgreementESignSender_TEST.cls
@isTest
public class CTX_PartnerAgreementESignSender_TEST {
    @testsetup
    public static void setup(){
        List<sObject> ls = Test.loadData(E_Sign_Config__c.sObjectType, 'ESign_Config');
System.debug(ls);
        Account acc = new Account(
            Name 					= 'Test Account',
            RecordTypeId 			= AccountConstants.CHANNEL_PARTNER_RecordTypeId,
            Master_Admin_Email__c 	= 'test@test.com'
        );
        
        insert acc;
        
        Contact con = new Contact(
        	LastName 	= 'Test Contact',
            Email 		= acc.Master_Admin_Email__c,
            Phone 		= '1111111111',
            AccountId 	= acc.Id
        );
        
        insert con;
        
        Map<String, E_Sign_Config__c> 	eSignConfig 				= E_Sign_Config__c.getAll();
        
        ContentVersion conVersion = new ContentVersion(
            PathOnClient 		= 'OrderForm' + '.pdf',
            Title 				= 'OrderFrom',
            Type_of_document__c = eSignConfig.get('Type_Of_Doc').Value__c,
            System_Generated__c = true,
            VersionData 		= Blob.valueOf('abcd')
        );
        insert conVersion;
        
        Id cdId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE id = : conVersion.id].ContentDocumentId;
        ContentDocumentLink cdl = new ContentDocumentLink(
        	ContentDocumentId = cdId,
            LinkedEntityId = acc.Id,
            ShareType = 'V'
        );
        insert cdl;
        
    }
    
    @isTest
    public Static void sendOrderFromForESign_TEST(){
        Map<Id, Account> accMap = new Map<Id, Account>([SELECT Id,Name,Agreement_Sign_Method__c,Master_Admin_Email__c,Owner.Name,RecordType.name,CC__c,OTP_For_Electronic_Signature__c,Esign_Order__c, E_Sign_Type__c 
                                                                             FROM Account WHERE Name = 'Test Account']);
        Test.setMock(HttpCalloutMock.class, new CTX_ESignGenericRespoceMock());
        Test.StartTest();
        //CTX_PartnerAgreementESignSender.sendOrderFromForESign(accMap, new set<String>{'test@test.com'});
        Test.StopTest();    
    }
    
}