foundation-objs/main/default/objects/Account/fields/Bank_Branch__c.field-meta.xml
<CustomField>
    <fullName>Bank_Branch__c</fullName>
    <label>Bank Branch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Account/fields/Bank_IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>Bank_IFSC_Code__c</fullName>
    <label>Bank IFSC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Account/fields/Bank_Swift_Code__c.field-meta.xml
<CustomField>
    <fullName>Bank_Swift_Code__c</fullName>
    <label>Bank Swift Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Account/fields/Is_Auto_Renewal_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Is_Auto_Renewal_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Auto Renewal Enabled?</label>
    <type>Checkbox</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/BackEndQuote__c.field-meta.xml
<CustomField>
    <fullName>BackEndQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BackEndQuote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/BackEndQuoteDiscount__c.field-meta.xml
<CustomField>
    <fullName>BackEndQuoteDiscount__c</fullName>
    <formula>0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BackEndQuoteDiscount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <label>Billing Address</label>
    <type>TextArea</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Legal_Entity_Name_Of_The_Client__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name_Of_The_Client__c</fullName>
    <label>Legal Entity Name Of The Client</label>
    <type>TextArea</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_ID__c.field-meta.xml
<CustomField>
    <fullName>License_ID__c</fullName>
    <label>License ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_no_of_gstins__c.field-meta.xml
<CustomField>
    <fullName>License_no_of_gstins__c</fullName>
    <label>Allowance_No. of GSTINs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_no_of_irns_per_year__c.field-meta.xml
<CustomField>
    <fullName>License_no_of_irns_per_year__c</fullName>
    <label>Allowance_No. of IRNs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_no_of_pans__c.field-meta.xml
<CustomField>
    <fullName>License_no_of_pans__c</fullName>
    <label>Allowance_No. of PANs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_no_of_userids__c.field-meta.xml
<CustomField>
    <fullName>License_no_of_userids__c</fullName>
    <label>Allowance_No. of User IDs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Number_of_eway_bill__c.field-meta.xml
<CustomField>
    <fullName>Number_of_eway_bill__c</fullName>
    <label>Allowance_No. of E-way bill</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
            <value>
                <fullName>Razorpay</fullName>
            </value>
            <value>
                <fullName>NEFT</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Paytm</fullName>
            </value>
            <value>
                <fullName>IMPS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>TEXT(Product2.Product_Line__c)</formula>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Renewal_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Renewal Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets (Renewal Opportunity)</relationshipLabel>
    <relationshipName>Assets_Renewal</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <label>Shipping Address</label>
    <type>TextArea</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <label>Billing Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Billing_GST__c.field-meta.xml
<CustomField>
    <fullName>Billing_GST__c</fullName>
    <label>Billing GSTIN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Country_of_Origin__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Origin__c</fullName>
    <formula>TEXT(Account.Country_of_Origin__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country of Origin</label>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/E_Sign_Customer_Info__c.field-meta.xml
<CustomField>
    <fullName>E_Sign_Customer_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>E-Sign Customer Info</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Mark Esign customer contact as communicable by navigating to the contact</errorMessage>
        <filterItems>
            <field>Contact.Email</field>
            <operation>notContain</operation>
            <value>cleartax.in</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Is_Communicable__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes_llq</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Legal_Entity_Name_Of_The_Client__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name_Of_The_Client__c</fullName>
    <label>Legal Entity Name Of The Client</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
            <value>
                <fullName>Razorpay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <label>Shipping Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/State_2__c.field-meta.xml
<CustomField>
    <fullName>State_2__c</fullName>
    <label>Billing State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Product2/fields/Plan_Tier__c.field-meta.xml
<CustomField>
    <fullName>Plan_Tier__c</fullName>
    <label>Plan Tier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-code/main/default/classes/CTX_EnableAutoRenewalBatch.cls
public class CTX_EnableAutoRenewalBatch implements Database.Batchable<sObject>, Schedulable{
    Public string queryString;
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        String numberOfDays = System.Label.CTX_EnableAutoRenewalDate;
        Date assetWillExpireIn3Months=System.today() + Integer.valueOf(numberOfDays);
        
        String productLine = 'E-invoicing & E-Way Bill';
        
        Integer limitSOQL= integer.valueOf(label.limitSOQL);
        
        List<String> applicableStatus = System.Label.CTX_AutoRenewAssetStatus.split(',');
        
        queryString = 'SELECT Id, Name, License_ID__c,Account.Is_Auto_Renewal_Enabled__c, Product2.Plan_Tier__c,PurchaseDate,UsageEndDate,Price,';
        queryString+= 'Number_of_eway_bill__c,License_no_of_gstins__c,License_no_of_irns_per_year__c,License_no_of_pans__c ,License_no_of_userids__c ,';
        queryString+=  'Account.Owner.Name,Account.Owner.Email,Account.Owner.Phone,OwnerId, BackEndQuote__c,Account.Country_of_Origin__c,Account.ParentId,';
        queryString+=  'Account.Onboarding_Owner__c,Account.Onboarding_Owner__r.Email,Account.Onboarding_Owner__r.Phone,Product2.IsActive,CurrencyIsoCode,';
        queryString+=  'Account.Onboarding_Owner__r.ManagerId,Account.Onboarding_Owner__r.Manager.Email,Account.Onboarding_Owner__r.Manager.Phone,BackEndQuoteDiscount__c,';
        queryString+=  'Account.Onboarding_Owner__r.Manager.ManagerId,Account.Onboarding_Owner__r.Manager.Manager.Email,Account.Onboarding_Owner__r.Manager.Manager.Phone,';
        queryString+=  'Opportunity__r.Billing_Address__c,Opportunity__r.Billing_GST__c ,Opportunity__r.Legal_Entity_Name_Of_The_Client__c , Payment_Method__c,';
        queryString+=  'Renewal_Opportunity__c, Account.Name, Account.Account_Number__c, Account.Bank_Branch__c, Account.Bank_IFSC_Code__c , Account.Bank_Name__c,';
        queryString+=  'Account.Bank_Swift_Code__c, Renewal_Opportunity__r.E_Sign_Customer_Info__c, AccountId,Opportunity__r.Shipping_Address__c, Opportunity__r.State_2__c,'; 
        queryString+=  'Opportunity__r.E_Sign_Customer_Info__r.Name,Opportunity__r.E_Sign_Customer_Info__r.Email,Opportunity__r.E_Sign_Customer_Info__r.Phone, ';
        queryString+=  'Renewal_Opportunity__r.Billing_GST__c,Renewal_Opportunity__r.Billing_Address__c ,Renewal_Opportunity__r.Shipping_Address__c, ';
        queryString+=  'Renewal_Opportunity__r.State_2__c, Renewal_Opportunity__r.Legal_Entity_Name_Of_The_Client__c ';
        queryString+=  'FROM Asset WHERE Account.Is_Auto_Renewal_Enabled__c = TRUE AND Product2.Product_Line__c =:productLine AND License_ID__c != NULL AND Status IN :applicableStatus AND UsageEndDate = :assetWillExpireIn3Months ORDER BY UsageEndDate  ASC limit '+limitSOQL;
        
        System.debug('@queryString'+queryString);
        return Database.getQueryLocator(queryString);
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope){
        
        
        Map<Id, Asset> astMapToEnableAutoRenew 			= new  Map<Id, Asset>();
        Map<String, String> assetAccountMap				= new Map<String, String>();
        List<Asset> createRenewalOpp 					= new List<Asset>();
        
        if(scope.size() > 0){
            for(Asset thisRec : (List<Asset>) scope){
                astMapToEnableAutoRenew.put(thisRec.Id, thisRec);               
                assetAccountMap.put(thisRec.License_ID__c, thisRec.AccountId);
            }
            
            CTX_AutoRenewalFlag.enableAutoRenewal(astMapToEnableAutoRenew, assetAccountMap);
        }
    }
    
    public void finish(Database.BatchableContext BC){
        
        
    }
    
    
    public void execute(SchedulableContext sc){
        database.executeBatch(new CTX_EnableAutoRenewalBatch(), 50);
    }
}