foundation-objs/main/default/objects/Account/fields/Master_admin_Email__c.field-meta.xml
<CustomField>
    <fullName>Master_admin_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Master admin Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

foundation-objs/main/default/objects/Account/fields/Product_Email__c.field-meta.xml
<CustomField>
    <fullName>Product_Email__c</fullName>
    <externalId>true</externalId>
    <label>Product Email</label>
    <type>Email</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_Activated_On__c.field-meta.xml
<CustomField>
    <fullName>License_Activated_On__c</fullName>
    <label>License Activated On</label>
    <type>Date</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_ID__c.field-meta.xml
<CustomField>
    <fullName>License_ID__c</fullName>
    <label>License ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Plan_Type__c</fullName>
    <label>Plan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>TEXT(Product2.Product_Line__c)</formula>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Renewal_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Renewal Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets (Renewal Opportunity)</relationshipLabel>
    <relationshipName>Assets_Renewal</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Master_admin_Email__c.field-meta.xml
<CustomField>
    <fullName>Master_admin_Email__c</fullName>
    <inlineHelpText>(should belong to company domain name only)</inlineHelpText>
    <label>Master admin Email</label>
    <type>Email</type>
</CustomField>

foundation-objs/main/default/objects/Product2/fields/Plan_Tier__c.field-meta.xml
<CustomField>
    <fullName>Plan_Tier__c</fullName>
    <label>Plan Tier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-code/main/default/classes/CTX_FetchAssetService.cls
@RestResource(urlMapping='/FetchAssetsByMasterAdminEmails/*')
global class CTX_FetchAssetService {
    
    @HttpPost
    global static ReturnWrapper getAsset(
        List<String> adminEmails
    ){
        
        System.debug('adminEmails: '+adminEmails); 
        ReturnWrapper	thisWrapper 	= new ReturnWrapper();
        RestRequest 	req 			= RestContext.request;
        RestResponse 	res 			= RestContext.response;
        Set<String> 	validEmails 	= new Set<String>();
        
        
        if(adminEmails != NULL || adminEmails.size() > 0){
            for(String thisSTR : adminEmails){
                if(CTX_UtilityClass.validateEmailAddress(thisSTR)){
                    validEmails.add(thisSTR);
                }
            }
        }
        
        System.debug('CTX_FetchAssetService: validEmails: '+validEmails);
        System.debug('CTX_FetchAssetService: validEmails Size: '+validEmails.size());
        
        if(validEmails.size() <= 0){
            
            thisWrapper.numberOfAssets 				= 0;
            thisWrapper.isSuccess					= FALSE;
            thisWrapper.statusMessage				= 'Please provide valid Email Addresses to Proceed.';
        } else{
            
            for(
                Asset thisRec : [ SELECT Id, Name, Status, PurchaseDate, UsageEndDate, Plan_Type__c,  
                                 License_ID__c, License_Activated_On__c, 
                                 Account.Master_Admin_Email__c,
                                 Account.Product_Email__c,
                                 Opportunity__r.Master_Admin_Email__c, 
                                 Renewal_Opportunity__r.Master_Admin_Email__c, 
                                 Product2.ProductCode, Product2.Plan_Tier__c
                                 FROM Asset WHERE 
                                 (
                                     Product2.Product_Line__c IN :System.Label.Asset_Standard_Plan_Product_Line.split(';') AND 
                                     ( NOT Status IN :System.Label.Asset_Standard_Plan_Exclude_Status.split(';') ) 
                                 ) AND 
                                 ( 
                                     Account.Master_Admin_Email__c IN :validEmails OR 
                                     Account.Product_Email__c IN :validEmails
                                 ) 
                                ]
            ){
                
                /**	Master Admin Email Block : START	**/
                if(thisRec.Account.Master_Admin_Email__c != NULL){
                    if(thisWrapper.mapOfAdminEmailAndAsset.containsKey(thisRec.Account.Master_Admin_Email__c)){
                        thisWrapper.mapOfAdminEmailAndAsset.get(thisRec.Account.Master_Admin_Email__c).add(thisRec);
                    } else{
                        thisWrapper.mapOfAdminEmailAndAsset.put(thisRec.Account.Master_Admin_Email__c, new List<Asset>{thisRec});
                    }
                }/**	Master Admin Email Block : END	**/
                
                /**	Product Email Block : START	**/
                if(thisRec.Account.Product_Email__c != NULL){
                    if(thisWrapper.mapOfAdminEmailAndAsset.containsKey(thisRec.Account.Product_Email__c)){
                        thisWrapper.mapOfAdminEmailAndAsset.get(thisRec.Account.Product_Email__c).add(thisRec);
                    } else{
                        thisWrapper.mapOfAdminEmailAndAsset.put(thisRec.Account.Product_Email__c, new List<Asset>{thisRec});
                    }
                }/**	Product Email Block : END	**/
                
            }
            
            thisWrapper.numberOfAssets 				= thisWrapper.mapOfAdminEmailAndAsset.keySet().size();
            thisWrapper.isSuccess					= TRUE;
            thisWrapper.statusMessage				= 'Result fetched successfully.';
            
            if(thisWrapper.mapOfAdminEmailAndAsset.keySet().size() < 1 )
                thisWrapper.statusMessage			= 'No records found with the given Email Id.';
        } 
        
        return thisWrapper;
    }
    
    global class ReturnWrapper{
        Map<String, List<Asset>> mapOfAdminEmailAndAsset = new Map<String, List<Asset>>();
        Integer				numberOfAssets;
        Boolean				isSuccess;
        String				statusMessage;
    }
    
}