foundation-objs/main/default/objects/Account/fields/Master_admin_Email__c.field-meta.xml
<CustomField>
    <fullName>Master_admin_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Master admin Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Billing_GST__c.field-meta.xml
<CustomField>
    <fullName>Billing_GST__c</fullName>
    <label>Billing GSTIN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/ClearTax_Billing_Entity__c.field-meta.xml
<CustomField>
    <fullName>ClearTax_Billing_Entity__c</fullName>
    <label>ClearTax Billing Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Defmacro</fullName>
            </value>
            <value>
                <fullName>Xpedize</fullName>
            </value>
            <value>
                <fullName>CimplyFive</fullName>
            </value>
            <value>
                <fullName>ClearSharp</fullName>
                <isActive>false</isActive>
                <label>ClearSharp</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Company_Domain_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Domain_Name__c</fullName>
    <inlineHelpText>(e.g : xyz.in, abc.com or characters after ‘@’ in mail id) and If no domain name , please enter &apos;NA&apos;</inlineHelpText>
    <label>Company Domain Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Master_admin_Email__c.field-meta.xml
<CustomField>
    <fullName>Master_admin_Email__c</fullName>
    <inlineHelpText>(should belong to company domain name only)</inlineHelpText>
    <label>Master admin Email</label>
    <type>Email</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Order_Form_Required__c.field-meta.xml
<CustomField>
    <fullName>Order_Form_Required__c</fullName>
    <label>Order Form Required?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Presales_Resource__c.field-meta.xml
<CustomField>
    <fullName>Presales_Resource__c</fullName>
    <label>PreSales Primary Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Presales_Primary_Resource</valueSetName>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>Please include the scope or the products that will be closed under this opportunity</inlineHelpText>
    <label>Product Interested/Scope of sales</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Scope</valueSetName>
    </valueSet>
</CustomField>

foundation-objs/main/default/globalValueSets/Presales_Primary_Resource.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ankit Singhvi</fullName>
    </customValue>
    <customValue>
        <fullName>Geetika Sethi</fullName>
    </customValue>
    <customValue>
        <fullName>Rohit Jain</fullName>
    </customValue>
    <customValue>
        <fullName>Sagar Arora</fullName>
    </customValue>
    <customValue>
        <fullName>Jigar Vachharajani</fullName>
    </customValue>
    <customValue>
        <fullName>Shailja Sood</fullName>
    </customValue>
    <customValue>
        <fullName>Shrenik Shah</fullName>
    </customValue>
    <customValue>
        <fullName>Sunil Gupta</fullName>
    </customValue>
    <customValue>
        <fullName>Vipul Gupta</fullName>
    </customValue>
    <customValue>
        <fullName>Aneree Shah</fullName>
        <isActive>false</isActive>
        <label>Aneree Shah</label>
    </customValue>
    <customValue>
        <fullName>Mitanshi Goel</fullName>
        <isActive>false</isActive>
        <label>Mitanshi Goel</label>
    </customValue>
    <description>Presales reps who assist during demo / pocs</description>
    <masterLabel>Presales Resource</masterLabel>
</GlobalValueSet>

foundation-code/main/default/classes/GSTINValidationHelperForOpportunityTest.cls
@isTest
public class GSTINValidationHelperForOpportunityTest {
    
     @isTest
     public static void opptestForReceivable(){
        
        Profile pr = [SELECT Id FROM Profile WHERE Name='Standard User' Limit 1]; 
        
       // User preSaleOwner = [SELECT Id FROM User WHERE Name = 'Ankit Singhvi' Limit 1];
        
        User testUser = new User(Alias = 'standt', Email='standarduser@receivabletestorg1.com', 
                                 EmailEncodingKey='UTF-8', LastName='Testing1', LanguageLocaleKey='en_US', 
                                 LocaleSidKey='en_US', ProfileId = pr.Id, 
                                 TimeZoneSidKey='Asia/Kolkata', UserName='standarduser2121@receivabletestorg1.com');
        insert testUser;
        
        
        Account a1=new Account();
        a1.Name='Receivable test validation';
        a1.PAN__c = 'CUGPM4227R';
        //			HGSDR2254G
        //a1.Company_Domain_name__c = 'cleartax.com';
        a1.Master_admin_Email__c = 'abc@cleartax.com';
       // insert a1;
        try{
            System.runAs(testUser){
                insert a1;
            }
        }
        catch(exception e){
            system.debug('error in creating opportunity'+e);
        }
        
        Receivables__c  r1 = new Receivables__c ();
        r1.Name = 'Demo Receivables';
        r1.CT_Billing_Entity__c = 'Defmacro';
        r1.CurrencyIsoCode = 'INR';
        r1.PAN_TIN__c = 'CUGPM4227R';
        r1.Account__c = a1.id;
        r1.Name_of_the_entity__c = 'Test class Receivable';
         
        
       // insert r1;
        try{
            System.runAs(testUser){
                insert r1;
            }
        }
        catch(exception e){
            system.debug('error in creating opportunity'+e);
        }
        
        Opportunity opp1=new Opportunity();
        opp1.Name='Demo Receivables oppty';
        opp1.StageName='SQL';
        opp1.CloseDate=System.today();
        opp1.AccountId=a1.Id;
        opp1.OwnerId = testUser.id;
        opp1.Order_Form_Required__c = 'Yes';
        //opp1.ForecastCategory = 'Pipeline';
        opp1.ClearTax_Billing_Entity__c = 'Defmacro';
        opp1.Forecast_Amount__c = 100;
        opp1.Presales_Resource__c = 'Shailja Sood';
        opp1.Product__c = 'Airline Credit';
        opp1.StageName = 'SQL';
        opp1.Billing_GST__c = '12CUGPM4227R54321';
        try{
            System.runAs(testUser){
                insert opp1;
            }
        }
        catch(exception e){
            system.debug('error in creating opportunity'+e);
        }
        
        Receivables__c receiv = [SELECT id,PAN_TIN__c FROM Receivables__c WHERE Id =:r1.Id];
        Opportunity opp = [SELECT id,Billing_GST__c FROM Opportunity WHERE Id =:opp1.Id];
        
        System.debug('opp id'+opp.id);
		System.assertEquals(receiv.PAN_TIN__c, opp.Billing_GST__c.substring(2,12));
        
    }
}