foundation-objs/main/default/objects/Account/fields/Master_admin_Email__c.field-meta.xml
<CustomField>
    <fullName>Master_admin_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Master admin Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

foundation-objs/main/default/objects/Account/fields/No_of_GSTIN__c.field-meta.xml
<CustomField>
    <fullName>No_of_GSTIN__c</fullName>
    <label>No. of GSTIN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onboarding</fullName>
                <default>true</default>
                <label>Onboarding</label>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Company_Domain_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Domain_Name__c</fullName>
    <inlineHelpText>(e.g : xyz.in, abc.com or characters after ‘@’ in mail id) and If no domain name , please enter &apos;NA&apos;</inlineHelpText>
    <label>Company Domain Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Master_admin_Email__c.field-meta.xml
<CustomField>
    <fullName>Master_admin_Email__c</fullName>
    <inlineHelpText>(should belong to company domain name only)</inlineHelpText>
    <label>Master admin Email</label>
    <type>Email</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/No_of_B2B_Sales_invoice__c.field-meta.xml
<CustomField>
    <fullName>No_of_B2B_Sales_invoice__c</fullName>
    <label>No. of B2B Sales invoice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/No_of_B2C_Sales_invoice__c.field-meta.xml
<CustomField>
    <fullName>No_of_B2C_Sales_invoice__c</fullName>
    <label>No. of B2C Sales invoice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/No_of_E_way_bill__c.field-meta.xml
<CustomField>
    <fullName>No_of_E_way_bill__c</fullName>
    <label>No. of E-way bill</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/No_of_GSTIN__c.field-meta.xml
<CustomField>
    <fullName>No_of_GSTIN__c</fullName>
    <label>No. of GSTIN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/No_of_GSTIN_verification_credits__c.field-meta.xml
<CustomField>
    <fullName>No_of_GSTIN_verification_credits__c</fullName>
    <label>No. of GSTIN verification credits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/No_of_IRNs__c.field-meta.xml
<CustomField>
    <fullName>No_of_IRNs__c</fullName>
    <label>Estimated no. of IRNs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/No_of_PANs__c.field-meta.xml
<CustomField>
    <fullName>No_of_PANs__c</fullName>
    <label>No. of PANs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/No_of_purchase_invoice__c.field-meta.xml
<CustomField>
    <fullName>No_of_purchase_invoice__c</fullName>
    <label>No. of purchase invoice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/No_of_user_IDs__c.field-meta.xml
<CustomField>
    <fullName>No_of_user_IDs__c</fullName>
    <label>No. of user IDs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/No_of_Vendors__c.field-meta.xml
<CustomField>
    <fullName>No_of_Vendors__c</fullName>
    <label>Estimated No. of Vendors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>Please include the scope or the products that will be closed under this opportunity</inlineHelpText>
    <label>Product Interested/Scope of sales</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Scope</valueSetName>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/Upsell_Top_up__c.object-meta.xml
<CustomObject>
    <label>Upsell - Top-up</label>
    <nameField>
        <label>Upsell - Top-up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Upsell - Top-ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Upsell - Top-ups</relationshipLabel>
    <relationshipName>Upsell_Top_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Additional_Price__c.field-meta.xml
<CustomField>
    <fullName>Additional_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Additional Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finance Approval In Progress</fullName>
            </value>
            <value>
                <fullName>Finance Approval Approved</fullName>
            </value>
            <value>
                <fullName>Finance Approval Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Upsell - Top-ups</relationshipLabel>
    <relationshipName>Upsell_Top_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/No_of_B2B_Sales_invoice__c.field-meta.xml
<CustomField>
    <fullName>No_of_B2B_Sales_invoice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of B2B Sales invoice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/No_of_B2C_Sales_invoice__c.field-meta.xml
<CustomField>
    <fullName>No_of_B2C_Sales_invoice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of B2C Sales invoice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/No_of_E_way_bill__c.field-meta.xml
<CustomField>
    <fullName>No_of_E_way_bill__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of E-way bill</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/No_of_GSTIN__c.field-meta.xml
<CustomField>
    <fullName>No_of_GSTIN__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of GSTIN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/No_of_GSTIN_verification_credits__c.field-meta.xml
<CustomField>
    <fullName>No_of_GSTIN_verification_credits__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of GSTIN verification credits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/No_of_IRNs__c.field-meta.xml
<CustomField>
    <fullName>No_of_IRNs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of IRNs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/No_of_PANs__c.field-meta.xml
<CustomField>
    <fullName>No_of_PANs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of PANs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/No_of_purchase_invoice__c.field-meta.xml
<CustomField>
    <fullName>No_of_purchase_invoice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of purchase invoice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/No_of_user_IDs__c.field-meta.xml
<CustomField>
    <fullName>No_of_user_IDs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of user IDs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/No_of_vendors__c.field-meta.xml
<CustomField>
    <fullName>No_of_vendors__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of vendors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Upsell - Top-ups</relationshipLabel>
    <relationshipName>Upsell_Top_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Upsell - Top-ups</relationshipLabel>
    <relationshipName>Upsell_Top_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Request</fullName>
                <default>true</default>
                <label>New Request</label>
            </value>
            <value>
                <fullName>Billing Details</fullName>
            </value>
            <value>
                <fullName>Finance Approval</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-code/main/default/classes/UpsellTriggerTest.cls
@isTest(seeAllData = False)
public class UpsellTriggerTest {
    
	@isTest
    Public static void upsellTest(){
        
        TriggerActivationOrDeactivation__c ta = new TriggerActivationOrDeactivation__c();
        ta.Name='Upsell_Top_up__c';
        ta.Object_API_Name__c = 'Upsell_Top_up__c';
        ta.isActive__c = true;
        insert ta;
        
        Account acc=new Account();
        acc.Name='Test acc';
        acc.PAN__c = 'QWERT2254G';
        acc.Company_Domain_name__c = 'abc.com';
        acc.Master_admin_Email__c = 'abc@abc.com';
        insert acc;
        
        Opportunity opp=new Opportunity();
        opp.Name='Test opp';
        opp.StageName='SQL';
        opp.CloseDate=System.today();
        opp.AccountId=acc.Id;
        insert opp;
    
        Product2 p=new Product2();
        p.Name='Test Prod';
        p.Family='Airline';
        p.IsActive =true;
        p.Family = 'Managed Service';
        p.Formula__c = '1500';
        insert p;
        
        Asset ast= new Asset();
        ast.Name='Test Asset';
        ast.Product2Id = p.id;
        ast.AccountId = acc.id;
        ast.Opportunity__c = opp.Id;
        ast.Price = 200000;
        ast.PurchaseDate = system.today();
        ast.usageEndDate = system.today() + 365;
        insert ast;
                
        Upsell_Top_up__c ups = new Upsell_Top_up__c();
        ups.Name = 'Test Ups';
        ups.Account__c = acc.Id;
        ups.Product__c = p.Id;
        ups.Asset__c = ast.Id;
        ups.Additional_Price__c = 100000;
        ups.Stage__c = 'New Request';
        ups.No_of_B2B_Sales_invoice__c = 10;
        ups.No_of_B2C_Sales_invoice__c = 10;
        ups.No_of_E_way_bill__c = 20;
        ups.No_of_GSTIN__c = 20;
        ups.No_of_GSTIN_verification_credits__c = 20;
        ups.No_of_IRNs__c = 10;
        ups.No_of_PANs__c = 10;
        ups.No_of_purchase_invoice__c = 20;
        ups.No_of_vendors__c = 10;
        ups.No_of_user_IDs__c = 10;
        insert ups;
        
        try{
            ups.Stage__c = 'Finance Approval';
            ups.Approval_Status__c = 'Finance Approval Approved';
            update ups; 
        }Catch(Exception ex){
            System.debug(' Exception on OrderFile Validation \n'+ex.getMessage()+'\n'+ex.getLineNumber());
        }
      
 		Opportunity opp1 =new Opportunity();
        opp1.Name='Test opp';
        opp1.StageName='Closed';
        opp1.CloseDate=System.today();
        opp1.AccountId=acc.Id;
        insert opp1;
        

        
        
    }
}