foundation-objs/main/default/objects/Account/fields/No_of_GSTIN__c.field-meta.xml
<CustomField>
    <fullName>No_of_GSTIN__c</fullName>
    <label>No. of GSTIN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Lead/fields/Invoice_Discounting_Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Discounting_Annual_Revenue__c</fullName>
    <label>Invoice Discounting Annual Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

foundation-objs/main/default/objects/Lead/fields/Number_Of_GSTN__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_GSTN__c</fullName>
    <label>Number Of GSTN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Lead/fields/Number_of_PAN__c.field-meta.xml
<CustomField>
    <fullName>Number_of_PAN__c</fullName>
    <label>Number of PAN</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Lead/fields/Number_of_Sales_Invoices__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Sales_Invoices__c</fullName>
    <label>Number of Sales Invoices</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Lead/fields/PAN__c.field-meta.xml
<CustomField>
    <fullName>PAN__c</fullName>
    <externalId>true</externalId>
    <label>Primary PAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-code/main/default/classes/CTX_LeadFieldsPopulateFromAccount.cls
public class CTX_LeadFieldsPopulateFromAccount {
    
    public static void updateNoOfGSTINSalesInvoice(Map<String, Lead> leadsToUpdateMap){
        for(Account acct : [SELECT Id, PAN__c, No_of_PAN__c, No_of_GSTIN__c, Invoice_Discounting_Annual_Revenue__c, Number_of_Sales_Invoices__c FROM Account WHERE PAN__c IN : leadsToUpdateMap.keySet()]){
            if(leadsToUpdateMap.get(acct.PAN__c) != null){
             	leadsToUpdateMap.get(acct.PAN__c).Number_Of_GSTN__c = acct.No_of_GSTIN__c;
                leadsToUpdateMap.get(acct.PAN__c).Number_of_PAN__c = acct.No_of_PAN__c;
                leadsToUpdateMap.get(acct.PAN__c).Number_of_Sales_Invoices__c  = acct.Number_of_Sales_Invoices__c;
                leadsToUpdateMap.get(acct.PAN__c).Invoice_Discounting_Annual_Revenue__c = acct.Invoice_Discounting_Annual_Revenue__c;
            }
        }
    }

}