foundation-objs/main/default/objects/Account/fields/No_of_GSTIN__c.field-meta.xml
<CustomField>
    <fullName>No_of_GSTIN__c</fullName>
    <label>No. of GSTIN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Lead/fields/Invoice_Discounting_Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Discounting_Annual_Revenue__c</fullName>
    <label>Invoice Discounting Annual Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

foundation-objs/main/default/objects/Lead/fields/Number_Of_GSTN__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_GSTN__c</fullName>
    <label>Number Of GSTN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Lead/fields/Number_of_PAN__c.field-meta.xml
<CustomField>
    <fullName>Number_of_PAN__c</fullName>
    <label>Number of PAN</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Lead/fields/Number_of_Sales_Invoices__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Sales_Invoices__c</fullName>
    <label>Number of Sales Invoices</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Lead/fields/PAN__c.field-meta.xml
<CustomField>
    <fullName>PAN__c</fullName>
    <externalId>true</externalId>
    <label>Primary PAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-code/main/default/classes/CTX_UpdateLeadFieldsFromAccountBatch.cls
public class CTX_UpdateLeadFieldsFromAccountBatch implements Database.Batchable<String>, Database.stateful {
    public Map<String, Account> accountMap;
    public CTX_UpdateLeadFieldsFromAccountBatch (Map<String, Account> accountMap){
        this.accountMap = accountMap;
    }
	public Iterable<String> start(Database.BatchableContext BC){
        return new List<String>(accountMap.keySet());
    }

    public void execute(Database.BatchableContext BC, List<String> accountPANList){
        List<Lead> leadsToUpdate = new List<Lead>();
        for(Lead leadInstance : [SELECT Id, PAN__c, Number_Of_GSTN__c, Number_of_PAN__c, Number_of_Sales_Invoices__c, Invoice_Discounting_Annual_Revenue__c FROM Lead WHERE PAN__c IN : accountPANList]){
            leadInstance.Number_Of_GSTN__c = accountMap.get(leadInstance.PAN__c).No_of_GSTIN__c;
            leadInstance.Number_of_PAN__c = accountMap.get(leadInstance.PAN__c).No_of_PAN__c;
            leadInstance.Number_of_Sales_Invoices__c = accountMap.get(leadInstance.PAN__c).Number_of_Sales_Invoices__c;
            leadInstance.Invoice_Discounting_Annual_Revenue__c = accountMap.get(leadInstance.PAN__c).Invoice_Discounting_Annual_Revenue__c;
            leadsToUpdate.add(leadInstance);
        }
        
        if(!leadsToUpdate.isEmpty()){
            AccountConstants.updateLeadFields = true;
            Database.update(leadsToUpdate, false);
        }
        
        
    }

    public void finish(Database.BatchableContext BC){}
}