foundation-objs/main/default/objects/Integration_Scope_Add_On__c/Integration_Scope_Add_On__c.object-meta.xml
<CustomObject>
    <label>Integration Scope Add On</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Scope Add Ons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/Add_On_Status__c.field-meta.xml
<CustomField>
    <fullName>Add_On_Status__c</fullName>
    <label>Add On Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Applicable any more</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/Discount_Rate__c.field-meta.xml
<CustomField>
    <fullName>Discount_Rate__c</fullName>
    <formula>( List_Price__c - ( (List_Price__c *  Discount_Percentage__c) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/ERP_Family__c.field-meta.xml
<CustomField>
    <fullName>ERP_Family__c</fullName>
    <label>ERP Family</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/Product_SKU__c.field-meta.xml
<CustomField>
    <fullName>Product_SKU__c</fullName>
    <label>Product SKU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <formula>CASESAFEID(Related_Quote__r.OpportunityId)</formula>
    <label>Related Opportunity</label>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/Related_Quote__c.field-meta.xml
<CustomField>
    <fullName>Related_Quote__c</fullName>
    <label>Related Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Integration Scope Add Ons</relationshipLabel>
    <relationshipName>Related_Quote</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/ERP_Family__c.field-meta.xml
<CustomField>
    <fullName>ERP_Family__c</fullName>
    <label>ERP Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ERP_Family</valueSetName>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/QuoteLineItem/fields/Actual_Sell_Price__c.field-meta.xml
<CustomField>
    <fullName>Actual_Sell_Price__c</fullName>
    <formula>Sale_Price__c  -  Add_On_Discounted_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Sell Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/QuoteLineItem/fields/Actual_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Actual_Unit_Price__c</fullName>
    <formula>UnitPrice  -  Add_On_Prices__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/QuoteLineItem/fields/Add_On_Discounted_Price__c.field-meta.xml
<CustomField>
    <fullName>Add_On_Discounted_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Add On Discounted Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/QuoteLineItem/fields/Add_On_Prices__c.field-meta.xml
<CustomField>
    <fullName>Add_On_Prices__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Add On Prices</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/globalValueSets/ERP_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SAP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ECC / S4 Hana</fullName>
    </customValue>
    <customValue>
        <fullName>SAP B1</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle</fullName>
    </customValue>
    <customValue>
        <fullName>Microsoft</fullName>
    </customValue>
    <masterLabel>ERP Family</masterLabel>
</GlobalValueSet>

foundation-code/main/default/classes/CTX_IntegrationScopeAddOnTriggerHandler.cls
Public Class CTX_IntegrationScopeAddOnTriggerHandler IMPLEMENTS TriggerInterface{
    
    public static void beforeInsert(List<Sobject> listOfNewSObjects){}
    
    public static void afterInsert(List<Sobject> listOfNewSObjects,Map<Id,Sobject> mapOfNewSObjects){}
    
    public static void beforeUpdate(Map<Id,Sobject> mapOfNewSObjects,Map<Id,Sobject> mapOfOldSObjects){}
    
    public static void afterUpdate(Map<Id,Sobject> mapOfNewSObjects,Map<Id,Sobject> mapOfOldSObjects){}
    
    public static void beforeDelete(List<Sobject> listOfOldSObjects,Map<Id,Sobject> mapOfOldSObjects){}
    
    public static void afterDelete(Map<Id,Sobject> mapOfOldSObjects){
        
        System.debug('After Delete Trigger for ISAO');
        Map<Id, Integration_Scope_Add_On__c> oldIntegrationScopeMap = (Map<Id, Integration_Scope_Add_On__c>)mapOfOldSObjects;
        
        System.debug('After Delete Trigger for ISAO : '+oldIntegrationScopeMap.keySet());
        Map<String, Set<Integration_Scope_Add_On__c>> 	erpSKUIntegrationScopeMap 	= new Map<String, Set<Integration_Scope_Add_On__c>>();
        Map<Id, sObject>								quoteLineItemAndISAList		= new Map<Id, sObject>();        
        Set<Id>											quoteIds					= new Set<Id>();
        
        for(Integration_Scope_Add_On__c thisRec : oldIntegrationScopeMap.values()){
            
            if(thisRec.Add_On_Status__c == 'Approved'){
                String tempString = thisRec.ERP_Family__c + thisRec.Product_SKU__c;
                quoteIds.add(thisRec.Related_Quote__c);
                if(erpSKUIntegrationScopeMap.containsKey(tempString)){
                    erpSKUIntegrationScopeMap.get(tempString).add(thisRec);
                } else{
                    erpSKUIntegrationScopeMap.put(tempString, new Set<Integration_Scope_Add_On__c>{thisRec});
                }
            }
        }
        system.debug('erpSKUIntegrationScopeMap Integration_Scope_Add_On__c CTX_IntegrationScopeAddOnTriggerHandler: '+erpSKUIntegrationScopeMap);
        
        for(
            QuoteLineItem thisRec : [  SELECT Id, UnitPrice, Sale_Price__c, Add_On_Prices__c, Add_On_Discounted_Price__c, 
                                     Actual_Unit_Price__c, Actual_Sell_Price__c, Product2.OrderForm_Product_Name__c, 
                                     Quote.OpportunityId, Quote.Opportunity.ERP_Family__c, 
                                     Quote.Opportunity.Owner.ManagerId
                                     
                                     FROM QuoteLineItem WHERE QuoteId IN :quoteIds ]
        ){
            String tempString = thisRec.Quote.Opportunity.ERP_Family__c + thisRec.Product2.OrderForm_Product_Name__c;
            if(erpSKUIntegrationScopeMap.containsKey(tempString)){
                
                for( Integration_Scope_Add_On__c thisOne : erpSKUIntegrationScopeMap.get(tempString) ){
                    if(thisOne.Related_Opportunity__c == thisRec.Quote.OpportunityId){
                        
                        system.debug('Inside QLI List');
                        thisRec.Add_On_Prices__c			= thisRec.Add_On_Prices__c - thisOne.List_Price__c;
                        thisRec.Add_On_Discounted_Price__c	= thisRec.Add_On_Discounted_Price__c - thisOne.Discount_Rate__c;
                        
                        thisRec.UnitPrice 					= thisRec.UnitPrice - thisOne.List_Price__c;
                        thisRec.Sale_Price__c 				= thisRec.Sale_Price__c - thisOne.Discount_Rate__c;
                        
                        quoteLineItemAndISAList.put(thisRec.Id, thisRec);
                    } 
                }
                system.debug('quoteLineItemAndISAList QuoteLineItem erpSKUIntegrationScopeMap: '+quoteLineItemAndISAList);
            }
        }
        
        update quoteLineItemAndISAList.values();
    }
    
    public static void afterUndelete(List<Sobject> listOfNewSObjects,Map<Id,Sobject> mapOfNewSObjects){}
}