foundation-objs/main/default/objects/Case/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Case/fields/Developer_Comment_JIRA__c.field-meta.xml
<CustomField>
    <fullName>Developer_Comment_JIRA__c</fullName>
    <label>Developer Comment(JIRA)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

foundation-objs/main/default/objects/Case/fields/JIRA_Issue_Id__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Issue_Id__c</fullName>
    <externalId>true</externalId>
    <label>JIRA Issue Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

foundation-objs/main/default/objects/Case/fields/JIRA_Ticket_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Ticket_Created_Date__c</fullName>
    <label>JIRA Ticket Created Date</label>
    <type>DateTime</type>
</CustomField>

foundation-objs/main/default/objects/Case/fields/Jira_URL__c.field-meta.xml
<CustomField>
    <fullName>Jira_URL__c</fullName>
    <label>Jira URL</label>
    <type>Url</type>
</CustomField>

foundation-objs/main/default/objects/Case/fields/L3_Developer_JIRA__c.field-meta.xml
<CustomField>
    <fullName>L3_Developer_JIRA__c</fullName>
    <label>L3 Developer(JIRA)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Case/fields/Planned_Release_Date_JIRA__c.field-meta.xml
<CustomField>
    <fullName>Planned_Release_Date_JIRA__c</fullName>
    <label>Planned Release Date(JIRA)</label>
    <type>DateTime</type>
</CustomField>

foundation-code/main/default/objects/Case/fields/Products_Available__c.field-meta.xml
<CustomField>
    <fullName>Products_Available__c</fullName>
    <label>Product Related To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GST 2.0</fullName>
            </value>
            <value>
                <fullName>GST 1.0</fullName>
            </value>
            <value>
                <fullName>E-Invoicing &amp; E-Way Bill</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
            </value>
            <value>
                <fullName>Tax Cloud</fullName>
            </value>
            <value>
                <fullName>MAX ITC</fullName>
            </value>
            <value>
                <fullName>Capture</fullName>
            </value>
            <value>
                <fullName>Cimplyfive</fullName>
            </value>
            <value>
                <fullName>Clear Identity</fullName>
            </value>
            <value>
                <fullName>GST</fullName>
            </value>
            <value>
                <fullName>Invoice Discount</fullName>
            </value>
            <value>
                <fullName>e-invoicing</fullName>
            </value>
            <value>
                <fullName>IRP</fullName>
            </value>
            <value>
                <fullName>Clear Invoicing</fullName>
            </value>
            <value>
                <fullName>E Invoice - KSA</fullName>
            </value>
            <value>
                <fullName>Notice Management</fullName>
                <isActive>false</isActive>
                <label>Notice Management</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Case/fields/Status_JIRA__c.field-meta.xml
<CustomField>
    <fullName>Status_JIRA__c</fullName>
    <label>Status(JIRA)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-code/main/default/classes/CTX_CaseEmailBatch.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-06-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
global class CTX_CaseEmailBatch implements Database.Batchable<sObject>, Schedulable {
    
    public string 	queryString;
    public integer 	queryInMinutes;
    
    public CTX_CaseEmailBatch( String queryString, Integer queryInMinutes ){
        this.queryString 	= queryString;
        this.queryInMinutes = queryInMinutes;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        if( queryString != NULL ){
            Datetime timeBeforeMinutes 	= queryInMinutes != NULL ? Datetime.now().addMinutes(queryInMinutes) : Datetime.now().addMinutes(-60);
            queryString  				= queryString + ' LastModifiedDate >= :timeBeforeMinutes';
        } else{
            Datetime thirtyMinutesAgo 	= Datetime.now().addMinutes(-60);
            queryString					= ' SELECT Id, LastModifiedDate, CaseNumber, JIRA_Notification_Rollout_Time__c, Account.Onboarding_Owner__r.EMail, Account.Onboarding_Owner__r.Manager_Email__c, LastModifiedBy.Email, LastModifiedBy.Manager_Email__c, Owner_Email__c, Owner.Email, Account_Name__c, Account_Active_ARR__c, Products_Available__c, Subject, Jira_URL__c, Owner.Name, Status_JIRA__c, JIRA_Comment_Updates__c, Developer_Comment_JIRA__c, Planned_Release_Date_JIRA__c, CreatedDate, JIRA_Ticket_Created_Date__c, L3_Developer_JIRA__c, OwnerId FROM Case WHERE JIRA_Issue_Id__c != NULL AND LastModifiedBy.Name LIKE \'%JIRA Integration Site Guest User%\' AND ( NOT Status IN (\'Solved\', \'Closed\') ) AND LastModifiedDate >= :thirtyMinutesAgo ';
        }

        system.debug('CTX_CaseEmailBatch queryString: '+queryString);
        return Database.getQueryLocator(queryString);
    }
    
    global void execute(Database.BatchableContext BC, List<Case> caseList) {
        
        system.debug('CTX_CaseEmailBatch caseList: '+caseList);
        try {
            RecursiveTriggerHandler.isFirstTime         = FALSE;
            RecursiveTriggerHandler.isFirstTimeRenewed  = FALSE;
            CaseConstants.isFirstTimeCase				= FALSE;
            
            String returnValue = CTX_CaseEmailsShooter.sendEmailAlertForJiraFieldUpdate(caseList);
            system.debug('returnValue'+returnValue);
            database.update( caseList, FALSE );/**	JIRA_Notification_Rollout_Time	**/

            CaseConstants.isFirstTimeCase				= TRUE;
            RecursiveTriggerHandler.isFirstTime 		= TRUE;
            RecursiveTriggerHandler.isFirstTimeRenewed  = TRUE;
        } catch(Exception e) {
            System.debug('exception in batch'+e);
        }
        
    }   
    
    global void finish(Database.BatchableContext BC){}
    
    global void execute(SchedulableContext sc) {

        if( queryString != NULL ){
            Datetime timeBeforeMinutes 	= queryInMinutes != NULL ? Datetime.now().addMinutes(queryInMinutes) : Datetime.now().addMinutes(-60);
            queryString  				= queryString + ' LastModifiedDate >= :timeBeforeMinutes';
        } else{
            Datetime thirtyMinutesAgo 	= Datetime.now().addMinutes(-60);
            queryString					= ' SELECT Id, LastModifiedDate, CaseNumber, JIRA_Notification_Rollout_Time__c, Account.Onboarding_Owner__r.EMail, Account.Onboarding_Owner__r.Manager_Email__c, LastModifiedBy.Email, LastModifiedBy.Manager_Email__c, Owner_Email__c, Owner.Email, Account_Name__c, Account_Active_ARR__c, Products_Available__c, Subject, Jira_URL__c, Owner.Name, Status_JIRA__c, JIRA_Comment_Updates__c, Developer_Comment_JIRA__c, Planned_Release_Date_JIRA__c, CreatedDate, JIRA_Ticket_Created_Date__c, L3_Developer_JIRA__c, OwnerId FROM Case WHERE JIRA_Issue_Id__c != NULL AND LastModifiedBy.Name LIKE \'%JIRA Integration Site Guest User%\' AND ( NOT Status IN (\'Solved\', \'Closed\') ) AND LastModifiedDate >= :thirtyMinutesAgo ';
        }
        
        Database.executeBatch( 
            new CTX_CaseEmailBatch( ' SELECT Id, LastModifiedDate, CaseNumber, JIRA_Notification_Rollout_Time__c, Account.Onboarding_Owner__r.EMail, Account.Onboarding_Owner__r.Manager_Email__c, LastModifiedBy.Email, LastModifiedBy.Manager_Email__c, Owner_Email__c, Owner.Email, Account_Name__c, Account_Active_ARR__c, Products_Available__c, Subject, Jira_URL__c, Owner.Name, Status_JIRA__c, JIRA_Comment_Updates__c, Developer_Comment_JIRA__c, Planned_Release_Date_JIRA__c, CreatedDate, JIRA_Ticket_Created_Date__c, L3_Developer_JIRA__c, OwnerId FROM Case WHERE JIRA_Issue_Id__c != NULL AND LastModifiedBy.Name LIKE \'%JIRA Integration Site Guest User%\' AND ( NOT Status IN (\'Solved\', \'Closed\') ) AND ', -60 ),
            100
        );
    }
    
}