foundation-objs/main/default/objects/Lead/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <label>Campaign Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Lead/fields/Lead_Source_Details__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Details__c</fullName>
    <label>Lead Source Details</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

foundation-objs/main/default/objects/Lead/fields/Lead_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_Source__c</fullName>
    <label>Lead Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA Referral</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>Daily Demo Business Leads</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Google Ads</fullName>
            </value>
            <value>
                <fullName>GST Support Desk</fullName>
            </value>
            <value>
                <fullName>Inbound Mail</fullName>
            </value>
            <value>
                <fullName>Instapage</fullName>
            </value>
            <value>
                <fullName>Landing Page</fullName>
            </value>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>Microsite</fullName>
            </value>
            <value>
                <fullName>Ozontel</fullName>
            </value>
            <value>
                <fullName>Product Sign Up</fullName>
            </value>
            <value>
                <fullName>Tally</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Karza</fullName>
            </value>
            <value>
                <fullName>Neo Kinetics</fullName>
            </value>
            <value>
                <fullName>other Purchased</fullName>
            </value>
            <value>
                <fullName>Figment</fullName>
            </value>
            <value>
                <fullName>Incoming Demo Emails</fullName>
            </value>
            <value>
                <fullName>Customer Referral</fullName>
            </value>
            <value>
                <fullName>Exisitng Customer - New Scope</fullName>
            </value>
            <value>
                <fullName>Cold Calls</fullName>
            </value>
            <value>
                <fullName>Incoming Emails</fullName>
            </value>
            <value>
                <fullName>CA2013.com</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Lead/fields/UTM_Campaign__c.field-meta.xml
<CustomField>
    <fullName>UTM_Campaign__c</fullName>
    <label>UTM_Campaign</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Lead/fields/UTM_Content__c.field-meta.xml
<CustomField>
    <fullName>UTM_Content__c</fullName>
    <label>UTM_Content</label>
    <type>TextArea</type>
</CustomField>

foundation-objs/main/default/objects/Lead/fields/UTM_Medium__c.field-meta.xml
<CustomField>
    <fullName>UTM_Medium__c</fullName>
    <label>UTM_Medium</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Lead/fields/UTM_Source__c.field-meta.xml
<CustomField>
    <fullName>UTM_Source__c</fullName>
    <label>UTM_Source</label>
    <type>TextArea</type>
</CustomField>

foundation-code/main/default/classes/CTX_HandleGCCExistingLeads.cls
public class CTX_HandleGCCExistingLeads {
    public Static void handleLeadsAlreadyExists(Map<String,Lead> leadEmailToLeadMap){
        Map<String, Lead> existingEmailToLeadMap = new Map<String, Lead>();
        List<Lead_Re_Request__e> eventList = new List<Lead_Re_Request__e>();
        for(Lead leadInst : [SELECT Id, Name, Email, Incoming_Count__c FROM Lead WHERE Email IN :leadEmailToLeadMap.keySet()])
        {
            existingEmailToLeadMap.put(leadInst.Email, leadInst);
            eventList.add(new Lead_Re_Request__e(
                    Existing_Lead_Emails__c = leadInst.Email,
                    Lead_Source__c 			= leadEmailToLeadMap.get(leadInst.Email).leadSource,
                    Lead_Subsource__c 		= leadEmailToLeadMap.get(leadInst.Email).Lead_Sub_Source__c,
                    Campaign_Name__c		= leadEmailToLeadMap.get(leadInst.Email).Campaign_Name__c,
                    UTM_Source__c			= leadEmailToLeadMap.get(leadInst.Email).UTM_Source__c,
                    UTM_Medium__c			= leadEmailToLeadMap.get(leadInst.Email).UTM_Medium__c,
                	Lead_Source_Details__c	= leadEmailToLeadMap.get(leadInst.Email).Lead_Source_Details__c,
                    UTM_Content__c			= leadEmailToLeadMap.get(leadInst.Email).UTM_Content__c,
                    UTM_Campaign__c			= leadEmailToLeadMap.get(leadInst.Email).UTM_Campaign__c
            	)
            );
        }
        if(!eventList.isEmpty()){
            List<Database.SaveResult> results = Eventbus.publish(eventList);
            for(Database.SaveResult res : results){
                if(!res.isSuccess()){
                    System.debug('Event Failed : ' + res.id);
                }
            }
        }
        
        for(Lead leadInstance : leadEmailToLeadMap.values()){
            if(existingEmailToLeadMap.keySet().contains(leadInstance.Email)){
                leadInstance.addError('The Lead (Id:'+ existingEmailToLeadMap.get(leadInstance.Email).Id +') already Exists.');
            }
        }
    }
    
}