foundation-objs/main/default/objects/Additional_GSTIN__c/Additional_GSTIN__c.object-meta.xml
<CustomObject>
    <label>Additional GSTIN</label>
    <nameField>
        <label>GSTIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional GSTINs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Add_on_split__c.field-meta.xml
<CustomField>
    <fullName>Add_on_split__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Add-on split</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Billing ID</relationshipLabel>
    <relationshipName>Billing_ID</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Upsell_Top_up__c.field-meta.xml
<CustomField>
    <fullName>Upsell_Top_up__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Upsell - Top-up</label>
    <referenceTo>Upsell_Top_up__c</referenceTo>
    <relationshipLabel>Additional GSTINs</relationshipLabel>
    <relationshipName>Additional_GSTINs</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/Upsell_Top_up__c.object-meta.xml
<CustomObject>
    <label>Upsell - Top-up</label>
    <nameField>
        <label>Upsell - Top-up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Upsell - Top-ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Additional_Price__c.field-meta.xml
<CustomField>
    <fullName>Additional_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Additional Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Upsell - Top-ups</relationshipLabel>
    <relationshipName>Upsell_Top_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-code/main/default/classes/CTX_AdditionalGstinTriggerHelper.cls
public class CTX_AdditionalGstinTriggerHelper {
    /** Added By Ashwin -> Validate Add-On Split **/
    public static void validateTotalAddOn(Map<Id,Additional_GSTIN__c> billingIdMap){
        
        Set<Id> 								upsellSet 					= new Set<Id>();
        Map<Id,Decimal> 						upsellBillingIdMap 		= new Map<Id,Decimal>();
        Map<Id,Decimal> 						totalAddOnMap 			= new Map<Id,Decimal>();
        Map<Id,Upsell_Top_up__c> 				upsellMap 				= new Map<Id,Upsell_Top_up__c>([SELECT Id, Additional_Price__c, Asset__c
                                                                                                                FROM Upsell_Top_up__c
                                                                                                                WHERE Id IN :upsellSet]);
        
        for(Additional_GSTIN__c thisRec : billingIdMap.values()){
            upsellSet.add(thisRec.Upsell_Top_up__c);
        }
        
	        
        for(Additional_GSTIN__c thisRec : [SELECT Id,Name,Asset__c,Add_on_split__c,Upsell_Top_up__c
                                           FROM Additional_GSTIN__c
                                           WHERE Upsell_Top_up__c IN :upsellSet])
            
        {
            if(upsellBillingIdMap.containsKey(thisRec.Upsell_Top_up__c) && upsellBillingIdMap.get(thisRec.Upsell_Top_up__c) != NULL){
                Decimal totalAddOn;
                if(thisRec.Add_on_split__c != NULL){
					totalAddOn = upsellBillingIdMap.get(thisRec.Upsell_Top_up__c)  + thisRec.Add_on_split__c;
                }else{
					totalAddOn = upsellBillingIdMap.get(thisRec.Upsell_Top_up__c) ;
                }
                
                upsellBillingIdMap.put(thisRec.Upsell_Top_up__c, totalAddOn);   
                
            }else
            {
                upsellBillingIdMap.put(thisRec.Upsell_Top_up__c, thisRec.Add_on_split__c);
            }
        }
        
        for(Additional_GSTIN__c thisRec : billingIdMap.values()){
            if(upsellMap.get(thisRec.Upsell_Top_up__c) 											!= NULL								&& 
              upsellBillingIdMap.get(thisRec.Upsell_Top_up__c).round(System.RoundingMode.CEILING)	!= upsellMap.get(thisRec.Upsell_Top_up__c).Additional_Price__c)
            {
                thisRec.addError('Please ensure Total Add-on Split is equal to Additional Price.');
            }
        }
    }
}