foundation-objs/main/default/objects/Additional_GSTIN__c/Additional_GSTIN__c.object-meta.xml
<CustomObject>
    <label>Additional GSTIN</label>
    <nameField>
        <label>GSTIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional GSTINs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Add_on_split__c.field-meta.xml
<CustomField>
    <fullName>Add_on_split__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Add-on split</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address Line 1</label>
    <type>TextArea</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <label>Address Line 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Billing ID</relationshipLabel>
    <relationshipName>Billing_ID</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Billing_PAN__c.field-meta.xml
<CustomField>
    <fullName>Billing_PAN__c</fullName>
    <label>Billing PAN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Name_Of_The_Customer__c.field-meta.xml
<CustomField>
    <fullName>Name_Of_The_Customer__c</fullName>
    <label>Name Of The Customer</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <label>Pincode</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/SEZ_Yes_No__c.field-meta.xml
<CustomField>
    <fullName>SEZ_Yes_No__c</fullName>
    <label>SEZ (Yes/No)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/TAN__c.field-meta.xml
<CustomField>
    <fullName>TAN__c</fullName>
    <label>TAN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Upsell_Top_up__c.field-meta.xml
<CustomField>
    <fullName>Upsell_Top_up__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Upsell - Top-up</label>
    <referenceTo>Upsell_Top_up__c</referenceTo>
    <relationshipLabel>Additional GSTINs</relationshipLabel>
    <relationshipName>Additional_GSTINs</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/Upsell_Top_up__c.object-meta.xml
<CustomObject>
    <label>Upsell - Top-up</label>
    <nameField>
        <label>Upsell - Top-up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Upsell - Top-ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Upsell - Top-ups</relationshipLabel>
    <relationshipName>Upsell_Top_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Billing_PAN__c.field-meta.xml
<CustomField>
    <fullName>Billing_PAN__c</fullName>
    <label>Billing PAN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

foundation-code/main/default/classes/CTX_AdditionalGstinUpsellController.cls
public class CTX_AdditionalGstinUpsellController {
	@AuraEnabled(cacheable=true)
    Public static List<Additional_GSTIN__c > getAdditionalGstins(Id topupId){
        //Id assetId = [SELECT Id, Asset__c from Upsell_Top_up__c  where Id = :topupId]?.Asset__c;
        List<Additional_GSTIN__c> gstinRecords	= new List<Additional_GSTIN__c>
            (
                [ SELECT Id, Name, Amount__c, Add_on_split__c,Name_Of_The_Customer__c,
                 Billing_PAN__c, Address__c, Address_Line_2__c,
                 City__c,State__c, Pincode__c, TAN__c, SEZ_Yes_No__c
                 FROM Additional_GSTIN__c
                 WHERE Upsell_Top_up__c  = :topupId]
            );
        System.debug('Additional Gstins-->'+gstinRecords);
        return gstinRecords;
    }
    
    @AuraEnabled
    Public static void updateBillingIds(List<Additional_GSTIN__c> gstinList ){
        try{
          update gstinList;  
        }catch(Exception ex){
            throw new AuraHandledException(ex.getDmlMessage(0));
        }
        
    }
}