foundation-objs/main/default/objects/Additional_GSTIN__c/Additional_GSTIN__c.object-meta.xml
<CustomObject>
    <label>Additional GSTIN</label>
    <nameField>
        <label>GSTIN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional GSTINs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Add_on_split__c.field-meta.xml
<CustomField>
    <fullName>Add_on_split__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Add-on split</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address Line 1</label>
    <type>TextArea</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <label>Address Line 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Billing ID</relationshipLabel>
    <relationshipName>Billing_ID</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Name_Of_The_Customer__c.field-meta.xml
<CustomField>
    <fullName>Name_Of_The_Customer__c</fullName>
    <label>Name Of The Customer</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <label>Pincode</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Additional_GSTIN__c/fields/Upsell_Top_up__c.field-meta.xml
<CustomField>
    <fullName>Upsell_Top_up__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Upsell - Top-up</label>
    <referenceTo>Upsell_Top_up__c</referenceTo>
    <relationshipLabel>Additional GSTINs</relationshipLabel>
    <relationshipName>Additional_GSTINs</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Legal_Entity_Name_Of_The_Client__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name_Of_The_Client__c</fullName>
    <label>Legal Entity Name Of The Client</label>
    <type>TextArea</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <label>Billing Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>IF( Record_Type_cumulated__c = &apos;Upsell_Topup&apos;, Upsell_Amount__c,IF((Record_Type_cumulated__c = &apos;Net_New_ID&apos; || ISPICKVAL(ClearTax_Billing_Entity__c,&apos;Xpedize&apos;)) &amp;&amp;
!ISPICKVAL(Xpedize_Product_Type__c, &apos;KYC APIs&apos;), Forecast_Amount__c,
IF(NOT(ISBLANK(SyncedQuoteId)) , Actual_Amount__c  ,  Forecast_Amount__c  )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>Location_Master__c</referenceTo>
    <relationshipLabel>Opportunities_City</relationshipLabel>
    <relationshipName>Opportunities_City</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Legal_Entity_Name_Of_The_Client__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name_Of_The_Client__c</fullName>
    <label>Legal Entity Name Of The Client</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <label>Billing Pincode</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/recordTypes/Upsell.recordType-meta.xml
<RecordType>
    <fullName>Upsell</fullName>
    <active>true</active>
    <businessProcess>Net New%2C Cross Sell%2FUpsell and Partner Success</businessProcess>
    <description>Used for Upsell</description>
    <label>Upsell</label>
</RecordType>

foundation-objs/main/default/objects/Upsell_Top_up__c/Upsell_Top_up__c.object-meta.xml
<CustomObject>
    <label>Upsell - Top-up</label>
    <nameField>
        <label>Upsell - Top-up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Upsell - Top-ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Upsell - Top-ups</relationshipLabel>
    <relationshipName>Upsell_Top_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Upsell - Top-ups</relationshipLabel>
    <relationshipName>Upsell_Top_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/recordTypes/Upsell.recordType-meta.xml
<RecordType>
    <fullName>Upsell</fullName>
    <active>true</active>
    <label>Upsell</label>
</RecordType>

foundation-code/main/default/classes/CTX_OrderFormAddendumController.cls
global without sharing class CTX_OrderFormAddendumController {
    
    Public List<Additional_GSTIN__c > billing_Ids{get;set;}
    public static Decimal 	additionalGSTINTotal{get;set;}
    public static boolean 	isOrderFormSaved = FALSE;
    
    public CTX_OrderFormAddendumController(ApexPages.StandardController topupFormController){
        
        
        Upsell_Top_up__c upsell=(Upsell_Top_up__c) topupFormController.getRecord();
        System.debug('upsell-->'+upsell);
        
        billing_Ids = [SELECT Id, Name, Amount__c, Name_Of_The_Customer__c,Upsell_Top_up__c,
                       Add_on_split__c, Address__c, Address_Line_2__c, City__c,
                       State__c, Pincode__c
                       FROM Additional_GSTIN__c
                       WHERE Upsell_Top_up__c = :upsell.Id 
                       AND Add_on_split__c > 0];
        
        System.debug('billing_Ids->'+billing_Ids);
        
        additionalGSTINTotal = 0;
        for(Additional_GSTIN__c addtnGstin : billing_Ids){
            additionalGSTINTotal += addtnGstin.Add_on_split__c;
        }
        
        
    }
    
    public Static void saveOrderFormToUpsell(){
        
        
        Id conDoc;
        Id upsellId = ApexPages.currentPage().getParameters().get('id');
        PageReference ref = new PageReference('/apex/OrderformAddendum?id='+ upsellId);
        
        Upsell_Top_up__c upsell = [SELECT id, Name,Asset__r.Opportunity__r.Legal_Entity_Name_Of_The_Client__c 
                                   FROM Upsell_Top_up__c WHERE id=:upsellId LIMIT 1];
        ContentVersion cont = new ContentVersion();
        cont.Title = 'Order Form Addendum - '+upsell.Asset__r.Opportunity__r.Legal_Entity_Name_Of_The_Client__c;
        cont.PathOnClient = 'Order Form Addendum - '+upsell.Asset__r.Opportunity__r.Legal_Entity_Name_Of_The_Client__c+'.pdf';
        Blob pdfBlob = ref.getContent();
        cont.VersionData = pdfBlob;
        cont.System_Generated__c = true;
        cont.Type_of_document__c = 'Order Form Addendum';
        insert cont;
        conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cont.Id].ContentDocumentId;
        ContentDocumentLink conDocLink = New ContentDocumentLink();
        conDocLink.LinkedEntityId = upsell.Id; 
        conDocLink.ContentDocumentId = conDoc;  
        conDocLink.shareType = 'V';
        insert conDocLink;
        
    }
    
}