foundation-objs/main/default/objects/Resource_Constraints__mdt/Resource_Constraints__mdt.object-meta.xml
<CustomObject>
    <label>Resource Constraints</label>
    <pluralLabel>Resource Constraints</pluralLabel>
</CustomObject>

foundation-objs/main/default/objects/Resource_Constraints__mdt/fields/Plan_Tier__c.field-meta.xml
<CustomField>
    <fullName>Plan_Tier__c</fullName>
    <label>Plan Tier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-code/main/default/objects/Resource_Constraints__mdt/fields/Salesforce_Field_QLI__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_QLI__c</fullName>
    <label>Salesforce Field QLI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-code/main/default/classes/CTX_MetadataRetriveUtility.cls
public class CTX_MetadataRetriveUtility{
    
    @AuraEnabled
    public static Map<String, Resource_Constraints__mdt> getResourceConstraintMetadataDetailsByFieldAPI( String planTier ){
        
        Map<String, Resource_Constraints__mdt>  resourceDetailsBasedOnFieldName = new Map<String, Resource_Constraints__mdt>();
        /**	Get Metadata Result to Map : START	**/
        for(Resource_Constraints__mdt mdt : Resource_Constraints__mdt.getAll().values()){
            
            if( mdt.Plan_Tier__c == planTier ){
                resourceDetailsBasedOnFieldName.put(mdt.Salesforce_Field_QLI__c, mdt);
            }
            
        }	/**	Get Metadata Result to Map : END	**/
        
        return resourceDetailsBasedOnFieldName;
    }
 
}