foundation-objs/main/default/objects/Product2/fields/Plan_Allowance_GSTIN__c.field-meta.xml
<CustomField>
    <fullName>Plan_Allowance_GSTIN__c</fullName>
    <label>Plan Allowance GSTIN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Product2/fields/Plan_Allowance_GSTIN_Verification__c.field-meta.xml
<CustomField>
    <fullName>Plan_Allowance_GSTIN_Verification__c</fullName>
    <label>Plan Allowance GSTIN verification credit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Product2/fields/Plan_Allowance_PAN__c.field-meta.xml
<CustomField>
    <fullName>Plan_Allowance_PAN__c</fullName>
    <label>Plan Allowance PAN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Product2/fields/Plan_Allowance_Total_invoices__c.field-meta.xml
<CustomField>
    <fullName>Plan_Allowance_Total_Invoices__c</fullName>
    <label>Plan Allowance Total Invoices</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/QuoteLineItem/fields/No_of_GSTIN_one__c.field-meta.xml
<CustomField>
    <fullName>No_of_GSTIN_one__c</fullName>
    <label>No. of GSTIN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/QuoteLineItem/fields/No_of_GSTIN_verification_credits__c.field-meta.xml
<CustomField>
    <fullName>No_of_GSTIN_verification_credits__c</fullName>
    <label>No. of GSTIN verification credits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/QuoteLineItem/fields/No_of_PAN_one__c.field-meta.xml
<CustomField>
    <fullName>No_of_PAN_one__c</fullName>
    <label>No. of PAN</label>
    <precision>17</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/QuoteLineItem/fields/No_of_Total_invoices__c.field-meta.xml
<CustomField>
    <fullName>No_of_Total_invoices__c</fullName>
    <label>No. of Total invoices</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/QuoteLineItem/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>App.Clear</fullName>
            </value>
            <value>
                <fullName>ASP/GSP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-code/main/default/classes/CTX_QliFieldUpdateBasedOnPlatform.cls
public class CTX_QliFieldUpdateBasedOnPlatform {
    public static void updateQli(Map<Id, QuoteLineItem> mapOfNewQuoteLines, Map<Id, QuoteLineItem> mapOfOldQuoteLines){
        Set<Id> 			productIds 				= new Set<Id>();
        
        for(QuoteLineItem qli : mapOfNewQuoteLines.values()){
            if(qli.Platform__c == 'App.Clear'){
                productIds.add(qli.Product2Id);
            }
        }
        
        Map<Id,Product2> ProductMap = new Map<Id,Product2>([SELECT Id, Plan_Allowance_GSTIN__c,Plan_Allowance_PAN__c,
                                                            Plan_Allowance_GSTIN_Verification__c , Plan_Allowance_Total_invoices__c 
                                                            FROM Product2 
                                                            WHERE Id IN : productIds]);
        
        for(QuoteLineItem thisRec : mapOfNewQuoteLines.values()){
            if(ProductMap.containsKey(thisRec.Product2Id)){
                if(ProductMap.get(thisRec.Product2Id).Plan_Allowance_GSTIN__c != NULL){
                    thisRec.No_of_GSTIN_one__c = ProductMap.get(thisRec.Product2Id).Plan_Allowance_GSTIN__c;
                }
                if(ProductMap.get(thisRec.Product2Id).Plan_Allowance_PAN__c != NULL){
                    thisRec.No_of_PAN_one__c = ProductMap.get(thisRec.Product2Id).Plan_Allowance_PAN__c;
                }
                if(ProductMap.get(thisRec.Product2Id).Plan_Allowance_GSTIN_Verification__c != NULL){
                    thisRec.No_of_GSTIN_verification_credits__c	 = ProductMap.get(thisRec.Product2Id).Plan_Allowance_GSTIN_Verification__c;
                }
                if(ProductMap.get(thisRec.Product2Id).Plan_Allowance_Total_invoices__c != NULL){
                    thisRec.No_of_Total_invoices__c = ProductMap.get(thisRec.Product2Id).Plan_Allowance_Total_invoices__c;
                }
            }
            
            
        }
        

    }
    
}