foundation-objs/main/default/objects/Product2/fields/SaaS_Product__c.field-meta.xml
<CustomField>
    <fullName>SaaS_Product__c</fullName>
    <label>SaaS Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GST</fullName>
            </value>
            <value>
                <fullName>CLEARTAX</fullName>
            </value>
            <value>
                <fullName>E_INVOICING</fullName>
            </value>
            <value>
                <fullName>CLEARONE</fullName>
            </value>
            <value>
                <fullName>CLEAR_INVOICE</fullName>
            </value>
            <value>
                <fullName>InvoiceCapture</fullName>
            </value>
            <value>
                <fullName>CLEAR_IDENTITY</fullName>
            </value>
            <value>
                <fullName>MaxItc</fullName>
            </value>
            <value>
                <fullName>TAX_ENGINE</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
            </value>
            <value>
                <fullName>CLEAR_PRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

scripts/apex/updateSaaSProductScript.cls
/** 

**/

List<Product2>      produtsToUpdate = new List<Product2>();
Map<String, String> productLineMap  = new Map<String, String>{
    'GST' => 'GST',
    'E-invoicing & E-Way Bill' => 'E_INVOICING',
    'Invoicing API' => 'CLEAR_INVOICE',
    'Max' => 'MaxItc',
    'TDS' => 'TDS',
    'Clear Capture' => 'InvoiceCapture',
    'KYC APIs' => 'CLEAR_IDENTITY' };

for( Product2 thisRec : [ SELECT Id, Name, Product_Line__c FROM Product2 ] ){
    
    thisRec.Saas_Product__c =   productLineMap.get(thisRec.Product_Line__c);
    produtsToUpdate.add(p2);
}

update produtsToUpdate;