foundation-objs/main/default/objects/Team_Responsible_SF_Jira__mdt/Team_Responsible_SF_Jira__mdt.object-meta.xml
<CustomObject>
    <label>Team Responsible SF &lt;&gt; Jira</label>
    <pluralLabel>Team Responsible SF &lt;&gt; Jira</pluralLabel>
</CustomObject>

foundation-objs/main/default/objects/Team_Responsible_SF_Jira__mdt/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <label>Assignee</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Team_Responsible_SF_Jira__mdt/fields/Assignee_Name__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Name__c</fullName>
    <label>Assignee Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Team_Responsible_SF_Jira__mdt/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <label>Project Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Team_Responsible_SF_Jira__mdt/fields/Team_Responsible__c.field-meta.xml
<CustomField>
    <fullName>Team_Responsible__c</fullName>
    <label>Team Responsible</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-code/main/default/classes/CTX_JIRAMappingClass.cls
public class CTX_JIRAMappingClass {
    
    public static Map<String, Team_Responsible_SF_Jira__mdt> getJIRATeamMapping(){
        
        Map<String, Team_Responsible_SF_Jira__mdt> mapOfL3TeamAndJIRAProject = new Map<String, Team_Responsible_SF_Jira__mdt>();
        
        for(
            Team_Responsible_SF_Jira__mdt  thisRec : [ SELECT Id, MasterLabel, DeveloperName, Team_Responsible__c , Project_Code__c, 
                                                      Assignee__c, Assignee_Name__c 
                                                      FROM Team_Responsible_SF_Jira__mdt WHERE 
                                                      Project_Code__c != NULL ]
        )
            mapOfL3TeamAndJIRAProject.put(thisRec.Team_Responsible__c, thisRec);
        system.debug('mapOfL3TeamAndJIRAProject: '+mapOfL3TeamAndJIRAProject);
        return mapOfL3TeamAndJIRAProject;
    }
}