foundation-objs/main/default/objects/Asset/fields/Account_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_Email__c</fullName>
    <formula>Account.Owner.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Owner Email</label>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Additional_POC_1__c.field-meta.xml
<CustomField>
    <fullName>Additional_POC_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Additional POC 1</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) AND (3 OR 4)</booleanFilter>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Is_Communicable__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.seniority__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Contact.seniority__c</field>
            <operation>equals</operation>
            <value>Senior</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assets (Additional POC 1)</relationshipLabel>
    <relationshipName>Assets1</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Additional_POC_2__c.field-meta.xml
<CustomField>
    <fullName>Additional_POC_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Additional POC 2</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) AND (3 OR 4)</booleanFilter>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Is_Communicable__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.seniority__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Contact.seniority__c</field>
            <operation>equals</operation>
            <value>Senior</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assets (Additional POC 2)</relationshipLabel>
    <relationshipName>Assets2</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Primary_POC__c.field-meta.xml
<CustomField>
    <fullName>Primary_POC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary POC</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Is_Communicable__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Renewal_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renewal Email Sent?</label>
    <type>Checkbox</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Send_Renewal_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Renewal_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Renewal Email?</label>
    <type>Checkbox</type>
</CustomField>

foundation-code/main/default/classes/CTX_RenewalEmailHelper.cls
public class CTX_RenewalEmailHelper {
    
    Public static void sendRenewalEmail(){
        
        Boolean 		isSuccess 			= FALSE;
        List<String> 	errorMessages 		= new List<String>();
        List<Asset> 	filteredAssetList 	= new list<Asset>();
        Date 			validatingDate 		= Date.today().addDays(30);
        Date 			DateToday 			= Date.Today();
        Id 				defaultMailId 		= [ SELECT Id FROM OrgWideEmailAddress WHERE 
                                               Address = 'e-invoicing@cleartaxmailer.com']?.Id;
        
        EmailTemplate 	emailTemplate 		= [ SELECT Id, Subject, Description, HtmlValue, DeveloperName, Body 
                                               FROM EmailTemplate WHERE
                                               name = 'Renewal Email'];
        
        List<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();
        
        filteredAssetList = [ SELECT id, Name, AccountId, Account.Owner.Id, Account.PGSB__c, UsageEndDate, Primary_POC__r.Email, Primary_POC__c, Account_owner_email__c,
                             Send_Renewal_Email__c, Renewal_Email_Sent__c, Additional_POC_1__c, Additional_POC_1__r.Email, Additional_POC_2__c, Additional_POC_2__r.Email 
                             FROM Asset WHERE 
                             Account.PGSB__c IN ('Silver', 'Bronze') AND
                             UsageEndDate <=:validatingDate AND 
                             UsageEndDate >=:DateToday AND 
                             Send_Renewal_Email__c = TRUE AND 
                             Renewal_Email_Sent__c = FALSE ];
        
        System.debug('filteredAssetList : '+filteredAssetList);
        System.debug('emailTemplate : '+emailTemplate.Id);
        
        for( Asset thisAsset : filteredAssetList ){
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTargetObjectId(thisAsset.Primary_POC__r.Id);
            mail.setUseSignature(false);
            mail.SaveAsActivity = FALSE;
            mail.setWhatId(thisAsset.Id);
            mail.setTemplateId(emailTemplate.ID);
            List<String> ccAddresses = new List<String>();
            if(thisAsset.Primary_POC__c != NULL)
                ccAddresses.add(thisAsset.Primary_POC__r.Email);
            if(thisAsset.Additional_POC_1__c != NULL)
                ccAddresses.add(thisAsset.Additional_POC_1__r.Email);
            if(thisAsset.Additional_POC_2__c != NULL)
                ccAddresses.add(thisAsset.Additional_POC_2__r.Email);
            mail.setToAddresses(new String[]{thisAsset.Account_owner_email__c});
            mail.setccAddresses(ccAddresses);
            mail.setOrgWideEmailAddressId(defaultMailId);
            mailList.add(mail);
        }
        
        system.debug('mailList: '+mailList.size());
        if(!mailList.isEmpty()) {
            try{
                Messaging.sendEmail(mailList);
                isSuccess = TRUE;
            }
            catch (Exception ex) {
                errorMessages.add('Unable to send email'+ ex.getMessage());
            }
        }
        
        if(isSuccess){
            for(Asset thisRec : filteredAssetList){
                thisRec.Renewal_Email_Sent__c = TRUE;
            }
            Database.update(filteredAssetList,FALSE);
        }
        System.debug('Errors : ' +errorMessages);
    }
    
}