foundation-objs/main/default/objects/Asset/fields/Account_PAN__c.field-meta.xml
<CustomField>
    <fullName>Account_PAN__c</fullName>
    <formula>Account.PAN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account PAN</label>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <formula>TEXT(Product2.Billing_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Type</label>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/ERP__c.field-meta.xml
<CustomField>
    <fullName>ERP__c</fullName>
    <label>ERP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>TallyPrime</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Infor LN</fullName>
            </value>
            <value>
                <fullName>JD Edwards</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics 365 Finance and Operations</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics 365 Business Central</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics AX</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics NAV</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics CRM</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics GP</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics SL</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics 365</fullName>
            </value>
            <value>
                <fullName>Microsoft Others</fullName>
            </value>
            <value>
                <fullName>Oracle E-Business Suite</fullName>
            </value>
            <value>
                <fullName>Oracle Fusion</fullName>
            </value>
            <value>
                <fullName>Oracle NetSuite</fullName>
            </value>
            <value>
                <fullName>Oracle Others</fullName>
            </value>
            <value>
                <fullName>Oracle PeopleSoft</fullName>
            </value>
            <value>
                <fullName>SAP Business One</fullName>
            </value>
            <value>
                <fullName>SAP ECC / S4 Hana</fullName>
            </value>
            <value>
                <fullName>SAP Others</fullName>
            </value>
            <value>
                <fullName>SAP B1</fullName>
            </value>
            <value>
                <fullName>Tally ERP 9</fullName>
            </value>
            <value>
                <fullName>Tally Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_B2B_SalesInvoice_per_year__c.field-meta.xml
<CustomField>
    <fullName>License_B2B_SalesInvoice_per_year__c</fullName>
    <label>Allowance_No. of B2B sales invoice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_B2C_SalesInvoice_per_year__c.field-meta.xml
<CustomField>
    <fullName>License_B2C_SalesInvoice_per_year__c</fullName>
    <label>Allowance_No. of B2C sales invoice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_ID__c.field-meta.xml
<CustomField>
    <fullName>License_ID__c</fullName>
    <label>License ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_no_of_gstin_verification_credits__c.field-meta.xml
<CustomField>
    <fullName>License_no_of_gstin_verification_credits__c</fullName>
    <label>Allowance_No. GSTIN verification credits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_no_of_gstins__c.field-meta.xml
<CustomField>
    <fullName>License_no_of_gstins__c</fullName>
    <label>Allowance_No. of GSTINs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_no_of_invoice_formats__c.field-meta.xml
<CustomField>
    <fullName>License_no_of_invoice_formats__c</fullName>
    <label>Allowance_No. of invoice formats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_no_of_irns_per_year__c.field-meta.xml
<CustomField>
    <fullName>License_no_of_irns_per_year__c</fullName>
    <label>Allowance_No. of IRNs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_no_of_pans__c.field-meta.xml
<CustomField>
    <fullName>License_no_of_pans__c</fullName>
    <label>Allowance_No. of PANs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_no_of_total_Sales_Invoices__c.field-meta.xml
<CustomField>
    <fullName>License_no_of_total_Sales_Invoices__c</fullName>
    <label>Allowance_No. of Total Sales Invoices</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_no_of_userids__c.field-meta.xml
<CustomField>
    <fullName>License_no_of_userids__c</fullName>
    <label>Allowance_No. of User IDs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/No_of_airline_invoices__c.field-meta.xml
<CustomField>
    <fullName>No_of_airline_invoices__c</fullName>
    <label>Allowance_No. of airline invoices</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/No_of_Vendor__c.field-meta.xml
<CustomField>
    <fullName>No_of_Vendor__c</fullName>
    <label>Allowance_No. of Vendor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Number_of_eway_bill__c.field-meta.xml
<CustomField>
    <fullName>Number_of_eway_bill__c</fullName>
    <label>Allowance_No. of E-way bill</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Number_of_Purchase_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Purchase_Invoice__c</fullName>
    <label>Allowance_No. of Purchase Invoice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
            <value>
                <fullName>Razorpay</fullName>
            </value>
            <value>
                <fullName>NEFT</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Paytm</fullName>
            </value>
            <value>
                <fullName>IMPS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10 days from date of invoice</fullName>
            </value>
            <value>
                <fullName>15 days from date of invoice</fullName>
            </value>
            <value>
                <fullName>30 days from date of invoice</fullName>
            </value>
            <value>
                <fullName>45 days from date of invoice</fullName>
            </value>
            <value>
                <fullName>60 days from date of invoice</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Annual Advance</fullName>
            </value>
            <value>
                <fullName>7 days from date of invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Type_of_Integration__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Integration__c</fullName>
    <label>Type of Integration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>API - Only by CT SI</fullName>
            </value>
            <value>
                <fullName>API - Only by CT Inhouse SAP ECC/HANA</fullName>
            </value>
            <value>
                <fullName>API - Only by CT Inhouse SAP B1</fullName>
            </value>
            <value>
                <fullName>API - Only by CT Inhouse Custom ERP</fullName>
            </value>
            <value>
                <fullName>API - Only by CT Inhouse Tally ERP</fullName>
            </value>
            <value>
                <fullName>API - Only by CT Inhouse Netsuite ERP</fullName>
            </value>
            <value>
                <fullName>FTP/SFTP - Only by customer</fullName>
            </value>
            <value>
                <fullName>API- Only by Customer</fullName>
            </value>
            <value>
                <fullName>FTP/ SFTP - Only by CT Inhouse</fullName>
            </value>
            <value>
                <fullName>FTP/ SFTP - Only by SI</fullName>
            </value>
            <value>
                <fullName>ID - API based Integration</fullName>
            </value>
            <value>
                <fullName>ID - Middleware based Integration</fullName>
            </value>
            <value>
                <fullName>ID - SFTP based Integration</fullName>
            </value>
            <value>
                <fullName>ID - Manual Integration</fullName>
            </value>
            <value>
                <fullName>API - Only by CT Inhouse Microsoft ERP</fullName>
            </value>
            <value>
                <fullName>API - Only by Customer</fullName>
                <isActive>false</isActive>
                <label>API - Only by Customer</label>
            </value>
            <value>
                <fullName>API- Only by CT</fullName>
                <isActive>false</isActive>
                <label>API- Only by CT</label>
            </value>
            <value>
                <fullName>BOX</fullName>
                <isActive>false</isActive>
                <label>BOX</label>
            </value>
            <value>
                <fullName>Excel/Custom Mapper</fullName>
                <isActive>false</isActive>
                <label>Excel/Custom Mapper</label>
            </value>
            <value>
                <fullName>FTP</fullName>
                <isActive>false</isActive>
                <label>FTP</label>
            </value>
            <value>
                <fullName>FTP/SFTP - SI/In-house</fullName>
                <isActive>false</isActive>
                <label>FTP/SFTP - SI/In-house</label>
            </value>
            <value>
                <fullName>SFTP-SI</fullName>
                <isActive>false</isActive>
                <label>SFTP-SI</label>
            </value>
            <value>
                <fullName>Tally Connector</fullName>
                <isActive>false</isActive>
                <label>Tally Connector</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Type_of_Integration_QLI__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Integration_QLI__c</fullName>
    <label>Type of Integration (new)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Integration</valueSetName>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/ERP__c.field-meta.xml
<CustomField>
    <fullName>ERP__c</fullName>
    <label>ERP</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ERP</valueSetName>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
            <value>
                <fullName>Razorpay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10 days from date of invoice</fullName>
            </value>
            <value>
                <fullName>15 days from date of invoice</fullName>
            </value>
            <value>
                <fullName>30 days from date of invoice</fullName>
            </value>
            <value>
                <fullName>45 days from date of invoice</fullName>
            </value>
            <value>
                <fullName>7 days from date of invoice</fullName>
            </value>
            <value>
                <fullName>60 days from date of invoice</fullName>
                <isActive>false</isActive>
                <label>60 days from date of invoice</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

scripts/apex/upsertLicenseScript.cls
/** 
This code will accept the AssetId and isUpdate and based on the It will Create or Update the License
Input Parameters:
    1. Asset Id
    2. isUpdate
**/

String  AssetId;
Boolean isUpdate;

Map<Id, Asset>  assetMap    = new Map<Id, Asset>(
            [ SELECT Id, Name, AccountId, Opportunity__c, ParentId, Billing_Type__c, Quantity, Price, Account_PAN__c, Status, 
             Payment_Term__c, Payment_Method__c, License_ID__c, PurchaseDate, UsageEndDate, License_no_of_gstins__c, License_no_of_pans__c, License_no_of_userids__c, No_of_Vendor__c,ERP__c, License_B2B_SalesInvoice_per_year__c, Number_of_Purchase_Invoice__c, Number_of_eway_bill__c, No_of_airline_invoices__c, License_B2C_SalesInvoice_per_year__c, Type_of_Integration__c, Type_of_Integration_QLI__c, License_no_of_total_Sales_Invoices__c, License_no_of_irns_per_year__c, License_no_of_invoice_formats__c, License_no_of_gstin_verification_credits__c, License_No_of_MM2A_2B_usage_GSTIN_mon__c, License_no_of_Recon__c, No_of_expected_B2C_invoices_for_QR_code__c, Workspace_Details__c, Master_Email__c, Product_Name_Formula__c, Platform__c, Product_Line__c,
             Parent.License_Id__c, Account.Master_admin_Email__c, Account.Product_Email__c, Account.Org_Unit_ID__c, Account.Name, Account.Country_of_Origin__c, Account.IsTestAccount__c, Opportunity__r.Name, Opportunity__r.Billing_Frequency__c, Opportunity__r.Billing_F__c, Opportunity__r.Billing_Method__c, Product2.Plan_Tier__c, Product2.Product_Plan_Id__c, Product2.Is_Standard__c, Product2.Family, Product2.ProductCode, Product2.Constraint_JSON__c, Product2.Saas_Product__c 
             FROM Asset WHERE Id = '02iC50000006zC1IAI' ] );

CTX_UpsertAssetLicense.callout_UpsertAsset_API(assetMap, assetMap, new Map<Id, Boolean>{'02iC50000006qVoIAI' => TRUE}, NULL);