foundation-objs/main/default/objects/Asset/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <label>Billing Address</label>
    <type>TextArea</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Legal_Entity_Name_Of_The_Client__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name_Of_The_Client__c</fullName>
    <label>Legal Entity Name Of The Client</label>
    <type>TextArea</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Place_of_Supply__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Supply__c</fullName>
    <label>Place of Supply</label>
    <type>TextArea</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Renewal_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Renewal Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets (Renewal Opportunity)</relationshipLabel>
    <relationshipName>Assets_Renewal</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <label>Shipping Address</label>
    <type>TextArea</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <label>Billing Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Billing_GST__c.field-meta.xml
<CustomField>
    <fullName>Billing_GST__c</fullName>
    <label>Billing GSTIN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/City_2__c.field-meta.xml
<CustomField>
    <fullName>City_2__c</fullName>
    <label>Billing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/If_SEZ__c.field-meta.xml
<CustomField>
    <fullName>If_SEZ__c</fullName>
    <label>If SEZ (Yes/No)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Legal_Entity_Name_Of_The_Client__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name_Of_The_Client__c</fullName>
    <label>Legal Entity Name Of The Client</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/PAN_No_as_per_PO__c.field-meta.xml
<CustomField>
    <fullName>PAN_No_as_per_PO__c</fullName>
    <label>Billing PAN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <label>Billing Pincode</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Place_of_Supply__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Supply__c</fullName>
    <label>Place of Supply</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <label>Shipping Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/State_2__c.field-meta.xml
<CustomField>
    <fullName>State_2__c</fullName>
    <label>Billing State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-code/main/default/classes/CTX_GSTINAPICalloutManually.cls
public class CTX_GSTINAPICalloutManually {
    
    public static Set<String> getOpportunityIds( String contentDocumentId ){
        
        ContentVersion 		contentDocumentVersionDetails	= [ SELECT VersionData FROM ContentVersion WHERE 
                                                               ContentDocumentId = :contentDocumentId AND 
                                                               IsLatest = TRUE ];
        Blob 			versionDataStringBody	= contentDocumentVersionDetails.VersionData;
        List<String> 	columnLiner				= versionDataStringBody.tostring().split('\n');
        Set<String>		assetIds	 			= new Set<String>();
        Set<String>		opportunityIds	 		= new Set<String>();
        
        for( Integer i = 1; i < columnLiner.size(); i++ ){
            
            assetIds.add(
                columnLiner[i].split(',')[0].trim()
            );
        }
        system.debug('assetIds: '+assetIds);
        system.debug('assetIds size: '+assetIds.size());
        
        for( 
            Asset thisRec : [ SELECT Id, 
                             Opportunity__c, Opportunity__r.Billing_Address__c, Opportunity__r.Shipping_Address__c, Opportunity__r.State_2__c,
                             Renewal_Opportunity__c, Renewal_Opportunity__r.Billing_Address__c, Renewal_Opportunity__r.Shipping_Address__c, Renewal_Opportunity__r.State_2__c
                             FROM Asset WHERE Id IN :assetIds ] 
        ){
            
            if( 
                thisRec.Renewal_Opportunity__c != NULL &&
                (
                    thisRec.Renewal_Opportunity__r.Billing_Address__c == NULL ||
                    thisRec.Renewal_Opportunity__r.Shipping_Address__c == NULL || 
                    thisRec.Renewal_Opportunity__r.State_2__c == NULL
                )
            ){
                opportunityIds.add(thisRec.Renewal_Opportunity__c);
            } else if( 
                thisRec.Opportunity__c != NULL &&
                (
                    thisRec.Opportunity__r.Billing_Address__c == NULL ||
                    thisRec.Opportunity__r.Shipping_Address__c == NULL || 
                    thisRec.Opportunity__r.State_2__c == NULL
                )
            ){
                opportunityIds.add(thisRec.Opportunity__c);
            } 
            
            
        }
        
        system.debug('opportunityIds: '+opportunityIds);
        system.debug('opportunityIds size: '+opportunityIds.size());
        return opportunityIds;
    }
    
    
    public static List<Opportunity> getGSTINDetailsAndUpdateOpportunity( Set<String> opportunityIds ){
        
        List<Opportunity> updateOpportunities = new List<Opportunity>();
        
        for( Opportunity thisRec : [ SELECT Id, Billing_GST__c 
                                    FROM Opportunity WHERE 
                                    Id IN :opportunityIds LIMIT 90 ]
           ){
               
               if( thisRec.Billing_GST__c != NULL ){
                   
                   HttpRequest request		= new HttpRequest();
                   Http			http		= new Http();
                   HTTPResponse	response;
                   request.setEndpoint(System.Label.GST_Portal_Endpoint + thisRec.Billing_GST__c);
                   request.setMethod('GET');
                   request.setHeader('Content-Type', 'application/json');
                   request.setHeader('x-cleartax-auth-token', System.Label.GST_ApiToken);
                   response = http.send(request);
                   
                   if (response.getStatusCode() == 200) { 
                       
                       System.debug('@response: '+ response.getBody());
                       Map<String, Object> responseMap         = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
                       Map<String, Object> taxPayerInfo		= (Map<String, Object>)responseMap.get('taxPayerInfo');
                       Map<String, Object> principalAddress 	= new  Map<String, Object>();
                       Map<String, Object> billingAddress 		= new Map<String, Object>();
                       
                       if(taxPayerInfo != NULL){
                           
                           if( taxPayerInfo.get('principalAddress') != NULL ){
                               principalAddress = (Map<String, Object>) taxPayerInfo.get('principalAddress');
                           }
                           if( principalAddress != NULL ) {
                               billingAddress = (Map<String, Object>) principalAddress.get('address');
                           }  
                           
                           String billingCity = '';
                           if(billingAddress != NULL){
                               billingCity = ((String) billingAddress?.get('city') != 'null' && (String) billingAddress?.get('city') != NULL &&(String) billingAddress?.get('city') != '') ? (String) billingAddress.get('city') :(String) billingAddress?.get('district');
                               
                           }
                           
                           Opportunity companyInfo = new Opportunity(
                               Id 									= thisRec.Id,
                               Legal_Entity_Name_Of_The_Client__c 	= (String)taxPayerInfo?.get('legalBusinessName'),
                               If_SEZ__c 							= ((String)taxPayerInfo.get('taxpayerType')).containsIgnoreCase('SEZ') ? 'Yes' : 'No',
                               PAN_No_as_per_PO__c 				= (String)taxPayerInfo?.get('pan'),
                               Pincode__c							= (String)billingAddress?.get('pinCode'),
                               City_2__c                           = billingCity,
                               State_2__c                          = (String)billingAddress?.get('stateName'),
                               Place_of_Supply__c                  = (String)billingAddress?.get('stateName')
                           );
                           companyInfo.Billing_Address__c			=   
                               (String) billingAddress?.get('doorNumber')  + ' ' + 
                               (String) billingAddress?.get('buildingName') + ' ' + 
                               (String) billingAddress?.get('floorNumber')  + ' ' +
                               (String) billingAddress?.get('street')      + ' ' +
                               (String) billingAddress?.get('locality')    + ' ' +
                               billingCity                        + ' ' +
                               (String) billingAddress?.get('district')    + ' ' +
                               (String) billingAddress?.get('stateName')   + ' ' +
                               (String) billingAddress?.get('pinCode');
                           companyInfo.Shipping_Address__c			= companyInfo?.Billing_Address__c;
                           companyInfo.Shipping_Address__c			= companyInfo?.Billing_Address__c;
                           
                           updateOpportunities.add(companyInfo);
                       }
                   }
               }
           }
        
        
        system.debug( 'updateOpportunities size: '+updateOpportunities.size() );
        return updateOpportunities;
    }
    
    
    public static void executeLogic( String contentDocumentId ){
        
        if( String.isNotBlank(contentDocumentId) ){
            Set<String> opportunityIds = getOpportunityIds(contentDocumentId);
            List<Opportunity> updateOpportunities =getGSTINDetailsAndUpdateOpportunity(opportunityIds);
            
            system.debug( 'updateOpportunities in Execute size: '+updateOpportunities.size() );
            OpportunityConstants.ENABLE_GSTIN_VERIFICATION_RULE = FALSE;
            RecursiveTriggerHandler.isFirstTimeOpportunity = FALSE;
            update updateOpportunities;
            RecursiveTriggerHandler.isFirstTimeOpportunity = TRUE;
        }
        
    }
    
}