foundation-objs/main/default/objects/Asset/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <formula>TEXT(Product2.Billing_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Type</label>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/ClearTax_Billing_Entity__c.field-meta.xml
<CustomField>
    <fullName>ClearTax_Billing_Entity__c</fullName>
    <label>ClearTax Billing Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Defmacro</fullName>
            </value>
            <value>
                <fullName>ClearSharp</fullName>
            </value>
            <value>
                <fullName>Xpedize</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>Choose Q1/ Q2/ Q3</description>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Q1 : Non Max ITC/MS/API/AMC/Non-integration related Assets</fullName>
            </value>
            <value>
                <fullName>Q2 : Non Max ITC/MS/API/AMC but integration involved from CT Side</fullName>
            </value>
            <value>
                <fullName>Q3 : Max ITC/MS/API/AMC/Uneecops and client side Integration Assets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>TEXT(Product2.Product_Line__c)</formula>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/ClearTax_Billing_Entity__c.field-meta.xml
<CustomField>
    <fullName>ClearTax_Billing_Entity__c</fullName>
    <label>ClearTax Billing Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Defmacro</fullName>
            </value>
            <value>
                <fullName>Xpedize</fullName>
            </value>
            <value>
                <fullName>CimplyFive</fullName>
            </value>
            <value>
                <fullName>ClearSharp</fullName>
                <isActive>false</isActive>
                <label>ClearSharp</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-code/main/default/classes/CTX_AssetParrentTagging.cls
public class CTX_AssetParrentTagging {
    
    public static void assetsParentTagging(List<Asset> newAssetList, Map<Id, Product2> prodMap, Map<Id,Opportunity> opportunityMap){
        System.debug('### Parent Tagging Execution Started ###');
        Set<Id>					accountIdSet 	= new Set<Id>();
        
        for(Asset thisAsset : newAssetList){
            if(thisAsset.Opportunity__c != NULL){
                if((opportunityMap.get(thisAsset.Opportunity__c).RecordTypeId == OpportunityConstants.RECORDTYPEID_RENEWAL || 
                   (opportunityMap.get(thisAsset.Opportunity__c).RecordTypeId == OpportunityConstants.RECORDTYPEID_NET_NEW ) && opportunityMap.get(thisAsset.Opportunity__c).ClearTax_Billing_Entity__c == 'CimplyFive') && /** Changed By Niraj : Removal of Net New Cimplyfive Record Type **/
                   (thisAsset.ParentId == NULL && 
                    thisAsset.Product2Id != NULL && 
                    thisAsset.AccountId != NULL &&
                    thisAsset.Billing_Type__c == 'ARR'
                   ))
                {
                    accountIdSet.add(thisAsset.AccountId);                    
                }   
            }
        }  
        
        
        
        Map<String, List<Asset>> 	accountIdProductIdExistingAsset 			= new Map<String, List<Asset>>();
        Map<String, List<Asset>> 	accountIdProductLineCategoryExistingAsset 	= new Map<String, List<Asset>>();
        /**	Make Licensing Changes : START	**/
        if(accountIdSet.size() > 0){
            
            for(
                Asset thisRec : [SELECT Id, AccountId, PurchaseDate, UsageEndDate, 
                                 Product2.Product_Line__c, Product2Id, Product2.Product_Category__c
                                 FROM Asset WHERE 
                                 AccountId IN :accountIdSet AND 
                                 ( NOT Status IN ('Churn', 'Sales return') ) AND
                                 Billing_Type__c NOT IN ('OTP')
                                 ORDER BY UsageEndDate DESC]
            ){
                String tempString1 = String.valueOf(thisRec.AccountId) + String.valueOf(thisRec.Product2Id);
                System.debug('tempString1: '+tempString1);
                
                if(!accountIdProductIdExistingAsset?.containsKey(tempString1)){
                    accountIdProductIdExistingAsset.put(tempString1, new List<Asset>{thisRec});
                } else {
                    accountIdProductIdExistingAsset.get(tempString1).add(thisRec);
                }
                
                if(thisRec.Product2.Product_Line__c != 'Secretarial Automation'){
                    String tempString2 = thisRec.AccountId + thisRec.Product2.Product_Line__c + thisRec.Product2.Product_Category__c;
                    System.debug('tempString2: '+tempString2);
                    
                    if(!accountIdProductLineCategoryExistingAsset?.containsKey(tempString2)){
                        accountIdProductLineCategoryExistingAsset.put(tempString2, new List<Asset>{thisRec});
                    } else{
                        accountIdProductLineCategoryExistingAsset.get(tempString2).add(thisRec);
                    }
                    
                }
            }
            
            for(Asset thisAsset : newAssetList){
                System.debug('##accountIdProductIdExistingAsset: '+accountIdProductIdExistingAsset);
                System.debug('##accountIdProductLineCategoryExistingAsset: '+accountIdProductLineCategoryExistingAsset);
                String tempString1 = String.valueOf(thisAsset.AccountId) + String.valueOf(thisAsset.Product2Id);
                String tempString2 = thisAsset.AccountId + prodMap?.get(thisAsset.Product2Id).Product_Line__c + prodMap?.get(thisAsset.Product2Id).Product_Category__c;
                if(accountIdProductIdExistingAsset?.containsKey(tempString1)){
                    for(Asset assetInst : accountIdProductIdExistingAsset.get(tempString1)){
                        if( assetInst.UsageEndDate != NULL && thisAsset.PurchaseDate != NULL && assetInst.UsageEndDate.daysBetween(thisAsset.PurchaseDate) <= 60 && assetInst.UsageEndDate.daysBetween(thisAsset.PurchaseDate) >= -15){
                            thisAsset.parentId = assetInst.Id;
                            break;
                        }
                    }
                    
                } 
                
                if(thisAsset.parentId == NULL && thisAsset.Product2.Product_Line__c != 'Secretarial Automation'){
                    if(accountIdProductLineCategoryExistingAsset?.containsKey(tempString2)){
                        for(Asset assetInst : accountIdProductLineCategoryExistingAsset.get(tempString2)){
                            if(assetInst.UsageEndDate   != NULL                                     &&
                                thisAsset.PurchaseDate  != NULL                                     &&
                                assetInst.UsageEndDate.daysBetween(thisAsset.PurchaseDate) <= 60    && 
                                assetInst.UsageEndDate.daysBetween(thisAsset.PurchaseDate) >= -15){
                                thisAsset.parentId = assetInst.Id; 
                                break;  
                            }
                        } 
                    }   
                }
            }
        }
         
    }

}