foundation-objs/main/default/objects/Asset/fields/CSM_Handled_Asset__c.field-meta.xml
<CustomField>
    <fullName>CSM_Handled_Asset__c</fullName>
    <formula>AND(
NOT(Is_Test_Asset__c),
NOT(CONTAINS($Label.Exclude_Account_Record_Types_CSM_Journey, Account.RecordTypeId)),
If( ISBLANK(Account.Channel_Partner_Account_Name__c), true, NOT(CONTAINS(LOWER(Account.Channel_Partner_Account_Name__c), &apos;uneecops&apos;))),
ParentId == null,
NOT(ISPICKVAL(Stage_in_MY__c, &apos;Middle Year&apos;)),
NOT(ISPICKVAL(Stage_in_MY__c, &apos;Last Year&apos;)),
Product2.CSM_Handled_Product__c = true,
CONTAINS(TEXT(Product2.Product_category__c),&apos;SaaS&apos;)
,
OR(
AND(
 ISPICKVAL(Product2.Product_Line__c, &apos;GST&apos;),
 NOT(CONTAINS(LOWER(Product2.Name), &apos;without csm&apos;)),
 Price &gt;= 50000
),
AND(
 ISPICKVAL(Product2.Product_Line__c, &apos;E-invoicing &amp; E-Way Bill&apos;),
 Price &gt;= 35000
),
 TEXT(Product2.Product_Line__c) = &apos;Invoicing API&apos;,
 TEXT(Product2.Product_Line__c) = &apos;Clear Capture&apos;,
 TEXT(Product2.Product_Line__c) = &apos;Max&apos;,
 TEXT(Product2.Product_Line__c) = &apos;TDS&apos;
)
) ||

TEXT(Account.Country_of_Origin__c) != &apos;India&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CSM Handled Asset?</label>
    <type>Checkbox</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Is_Escalation_Required__c.field-meta.xml
<CustomField>
    <fullName>Is_Escalation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Escalation Required?</label>
    <type>Checkbox</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Onboarding_process_start_date__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_process_start_date__c</fullName>
    <label>Onboarding process start date</label>
    <type>Date</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Onboarding_Stage__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Stage__c</fullName>
    <description>Current stage in the onboarding process</description>
    <label>Onboarding Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
                <default>true</default>
                <label>Not started</label>
            </value>
            <value>
                <fullName>Sales CSM Handover</fullName>
            </value>
            <value>
                <fullName>Introduction Email / Kickoff Call</fullName>
            </value>
            <value>
                <fullName>Customer Prerequisite Collection</fullName>
            </value>
            <value>
                <fullName>Customer License Account Creation</fullName>
            </value>
            <value>
                <fullName>Product Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Onboarding_status__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_status__c</fullName>
    <label>Onboarding status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Onboarding_Status</valueSetName>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>Choose Q1/ Q2/ Q3</description>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Q1 : Non Max ITC/MS/API/AMC/Non-integration related Assets</fullName>
            </value>
            <value>
                <fullName>Q2 : Non Max ITC/MS/API/AMC but integration involved from CT Side</fullName>
            </value>
            <value>
                <fullName>Q3 : Max ITC/MS/API/AMC/Uneecops and client side Integration Assets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Sales_CSM_Handover_Status__c.field-meta.xml
<CustomField>
    <fullName>Sales_CSM_Handover_Status__c</fullName>
    <label>Sales CSM Handover Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be started</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onboarding</fullName>
                <default>true</default>
                <label>Onboarding</label>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-code/main/default/classes/CTX_CSMJorneyQueueable.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 10-05-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class CTX_CSMJorneyQueueable IMPLEMENTS Queueable {
    
    public	Set<Id> 			assetIds;
    public 	Map<Id, Asset> 		newAssetMap;
    public 	Map<Id, Asset> 		oldAssetMap;
    public 	Map<Id, Product2> 	productMap;
    public 	Boolean 			isUpdate;
    public	Set<Id>				parentAssetId;
    
    public CTX_CSMJorneyQueueable(
        Map<Id, Asset>		newAssetMap, 
        Map<Id, Asset> 		oldAssetMap, 
        Map<Id, Product2> 	productMap, 
        Boolean 			isUpdate,
        Set<Id>				parentAssetId
    ){
        this.newAssetMap 	= newAssetMap;
        this.oldAssetMap 	= oldAssetMap;
        this.productMap 	= productMap;
        this.isUpdate 		= isUpdate;
        this.parentAssetId	= parentAssetId;
    }
    
    public CTX_CSMJorneyQueueable( Set<Id> assetIds ){
        this.assetIds = assetIds;
    }
    
    public void execute(QueueableContext context){
        
        List<Asset> 						assetsToUpdate 	
            = [ SELECT Id, Name, Stage__c, RecordTypeId, CSM_Handled_Asset__c, Onboarding_Stage__c, 
               Product2.Product_Category__c, Account.Name, Account.Onboarding_Owner__c, Account.Onboarding_Owner__r.Name, 
               Account.Onboarding_Owner__r.Email, Account.Sum_of_ARR_Assets__c, 
               Account.Onboarding_Owner__r.Manager.Email, Account.Sales_Owner__r.Email, Is_Escalation_Required__c 
               FROM Asset WHERE 
               Id IN : newAssetMap.keySet() AND 
               RecordType.Name = 'License Asset' ];
        List<Messaging.SingleEmailMessage> 	mailList 		= new List<Messaging.SingleEmailMessage>();
        Id 									defaultMailId 	= [ SELECT Id FROM OrgWideEmailAddress WHERE 
                                                               Address =: System.Label.CSM_Journey_Org_Wide_Generic_Email ]?.Id;
        
        for(Asset assetInstance : assetsToUpdate){
            if(assetInstance.CSM_Handled_Asset__c == true){
                assetInstance.Stage__c 					= 'Onboarding';
                assetInstance.Is_Escalation_Required__c = true;
                if(assetInstance.Account?.Onboarding_Owner__c != null){
                    assetInstance.Sales_CSM_Handover_Status__c 		= 'Started';
                    assetInstance.Onboarding_status__c 				= 'Onboarding Pending';
                    assetInstance.Onboarding_Stage__c 				= 'Sales CSM Handover';
                    assetInstance.Onboarding_process_start_date__c 	= System.today();
                    mailList.add(createNewAssetToCSMEmail(assetInstance, defaultMailId));
                } else {
                    assetInstance.Onboarding_Stage__c 				= 'Not started';
                }
            } else {
                //assetInstance.Stage__c 					= 'Success';
                assetInstance.Onboarding_status__c 			= 'Onboarding Not Required';
            }
            
        }
        
        if(!mailList.isEmpty()) {
            try{
                Messaging.sendEmail(mailList);
                
            }
            catch (Exception ex) {
                System.debug('Unable to send CSM Intro email'+ ex.getMessage());
            }
        }
        
        try{
            update assetsToUpdate;
        } catch(Exception e){
            system.debug('Asset Update Failed CSM Journey: '+e.getMessage());
        } finally{
            CTX_LicensingAssetFilterLogic.filterAssetsForlicensing(newAssetMap, NULL, productMap, FALSE, parentAssetId);
        }
        
        
        /**	Chaining Job for Renewal Licensing	: START	**/
        
        /**	Chaining Job for Renewal Licensing	: END	**/
        
    }

    public static Messaging.SingleEmailMessage createNewAssetToCSMEmail(Asset assetInstance, Id defaultMailId){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.SaveAsActivity = TRUE;
        mail.setWhatId(assetInstance.Id);
        String Subject = 'New Asset '+assetInstance.Name+' Created.';
        mail.setSubject(Subject);
        String body = 'Hi '+assetInstance.Account.Onboarding_Owner__r.Name+','+'<br/>';
        body += 'New asset has been added to the account for which you are assigned as a CSM.'+'<br/>';
        body += '<b>Asset Name :</b>'+' '+assetInstance.Name+'<br/>';
        body += '<b>Account Name :</b>'+' '+assetInstance.Account.Name+'<br/>';
        body += '<b>Asset URL :</b>'+' '+ URL.getSalesforceBaseUrl().toExternalForm()+'/'+assetInstance.Id +'<br/>';
        body += ''+'<br/>';
        body += ''+'<br/>';
        body +='Regards'+',<br/>'+'\n CSM Team'+'<br/>';
        mail.setHtmlBody(body);
        List<String> ccAddresses = new List<String>();
        ccAddresses.add(assetInstance.Account.Onboarding_Owner__r.Manager.email);
        ccAddresses.add(assetInstance.Account.Sales_Owner__r.email);
        mail.setToAddresses(new String[]{assetInstance.Account.Onboarding_Owner__r.email });
        mail.setccAddresses(ccAddresses);
        mail.setOrgWideEmailAddressId(defaultMailId);
        return mail;
    }
}