foundation-objs/main/default/objects/Asset/fields/Customer_License_Account_creation_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_License_Account_creation_Status__c</fullName>
    <label>Customer License Account creation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be started</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Customer_Prerequisite_collection_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Prerequisite_collection_Status__c</fullName>
    <label>Customer Prerequisite collection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be started</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Introduction_Email_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Introduction_Email_Completion_Date__c</fullName>
    <label>Introduction Email Completion Date</label>
    <type>Date</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Introduction_Email_Kickoff_Call_Status__c.field-meta.xml
<CustomField>
    <fullName>Introduction_Email_Kickoff_Call_Status__c</fullName>
    <label>Introduction Email / Kickoff Call Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be started</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Is_Asset_Activated__c.field-meta.xml
<CustomField>
    <fullName>Is_Asset_Activated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Asset Activated?</label>
    <type>Checkbox</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/License_Account_creation_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>License_Account_creation_Completion_Date__c</fullName>
    <label>License Account creation Completion Date</label>
    <type>Date</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Onboarding_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Completed_Date__c</fullName>
    <description>The day the last onboarding session is completed</description>
    <label>Onboarding Completed Date</label>
    <type>Date</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Onboarding_process_start_date__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_process_start_date__c</fullName>
    <label>Onboarding process start date</label>
    <type>Date</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Onboarding_Stage__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Stage__c</fullName>
    <description>Current stage in the onboarding process</description>
    <label>Onboarding Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
                <default>true</default>
                <label>Not started</label>
            </value>
            <value>
                <fullName>Sales CSM Handover</fullName>
            </value>
            <value>
                <fullName>Introduction Email / Kickoff Call</fullName>
            </value>
            <value>
                <fullName>Customer Prerequisite Collection</fullName>
            </value>
            <value>
                <fullName>Customer License Account Creation</fullName>
            </value>
            <value>
                <fullName>Product Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Onboarding_status__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_status__c</fullName>
    <label>Onboarding status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Onboarding_Status</valueSetName>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Prerequisite_collection_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Prerequisite_collection_Completion_Date__c</fullName>
    <label>Prerequisite collection Completion Date</label>
    <type>Date</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Product_training_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Product_training_Completion_Date__c</fullName>
    <label>Product  training Completion Date</label>
    <type>Date</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Product_training_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_training_Status__c</fullName>
    <label>Product  training Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be started</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Sales_CSM_Handover_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Sales_CSM_Handover_Completion_Date__c</fullName>
    <label>Sales CSM Handover Completion Date</label>
    <type>Date</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Sales_CSM_Handover_Status__c.field-meta.xml
<CustomField>
    <fullName>Sales_CSM_Handover_Status__c</fullName>
    <label>Sales CSM Handover Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To be started</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onboarding</fullName>
                <default>true</default>
                <label>Onboarding</label>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-code/main/default/classes/CTX_CSMJourneyOnbaordingFlow.cls
public class CTX_CSMJourneyOnbaordingFlow {
    
    public static void updateStage(List<Asset> assetList, Map<Id, Asset> oldAssetMap){
        for(Asset thisAsset : assetList){
            Asset oldInstance = oldAssetMap.get(thisAsset.Id);
            if(oldInstance.Onboarding_Status__c != thisAsset.Onboarding_Status__c) {
                If(thisAsset.Onboarding_Status__c == 'Onboarding Complete'){
                    thisAsset.Stage__c = 'Activation';
                }
            }
            if(oldInstance.Is_Asset_Activated__c != thisAsset.Is_Asset_Activated__c){
                if (thisAsset.Is_Asset_Activated__c == true) {
                    thisAsset.Stage__c = 'Success';
                }   
            }            
        }
    }
    
    public static void updateOnboardingSubstages(List<Asset> assetList, Map<Id, Asset> oldAssetMap){
        for(Asset thisAsset : assetList){
           	Asset oldInstance = oldAssetMap.get(thisAsset.Id);
            if(oldInstance.Onboarding_Stage__c == 'Not started' && thisAsset.Onboarding_Stage__c == 'Sales CSM Handover'){
                thisAsset.Sales_CSM_Handover_Status__c = 'Started';
                thisAsset.Onboarding_status__c = 'Onboarding Pending';
                thisAsset.Onboarding_process_start_date__c = System.today();
            } else if(thisAsset.Onboarding_Stage__c == 'Sales CSM Handover' && thisAsset.Sales_CSM_Handover_Status__c == 'Completed'){
                thisAsset.Sales_CSM_Handover_Completion_Date__c = System.today();
                thisAsset.Onboarding_Stage__c = 'Introduction Email / Kickoff Call';
                thisAsset.Introduction_Email_Kickoff_Call_Status__c = 'Started';
            } else if(thisAsset.Onboarding_Stage__c == 'Introduction Email / Kickoff Call' && thisAsset.Introduction_Email_Kickoff_Call_Status__c == 'Completed') {
                thisAsset.Introduction_Email_Completion_Date__c = System.today();
                thisAsset.Onboarding_Stage__c = 'Customer Prerequisite Collection';
                thisAsset.Customer_Prerequisite_collection_Status__c = 'Started';
            } else if(thisAsset.Onboarding_Stage__c == 'Customer Prerequisite Collection' && thisAsset.Customer_Prerequisite_collection_Status__c == 'Completed') {
                thisAsset.Prerequisite_collection_Completion_Date__c = System.today();
                thisAsset.Onboarding_Stage__c = 'Customer License Account Creation';
                thisAsset.Customer_License_Account_creation_Status__c = 'Started';
            } else if(thisAsset.Onboarding_Stage__c == 'Customer License Account Creation' && thisAsset.Customer_License_Account_creation_Status__c == 'Completed') {
                thisAsset.License_Account_creation_Completion_Date__c = System.today();
                thisAsset.Onboarding_Stage__c = 'Product Training';
                thisAsset.Product_training_Status__c = 'Started';
            } else if(thisAsset.Onboarding_Stage__c == 'Product Training' && (thisAsset.Product_training_Status__c != oldInstance.Product_training_Status__c && thisAsset.Product_training_Status__c == 'Completed')) {
                thisAsset.Onboarding_status__c = 'Onboarding Complete';
                thisAsset.Product_training_Completion_Date__c = System.today();
                thisAsset.Onboarding_Completed_Date__c = System.today();
            }
        }
        
    }
}