foundation-objs/main/default/objects/Asset/fields/ERP__c.field-meta.xml
<CustomField>
    <fullName>ERP__c</fullName>
    <label>ERP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>TallyPrime</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Infor LN</fullName>
            </value>
            <value>
                <fullName>JD Edwards</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics 365 Finance and Operations</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics 365 Business Central</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics AX</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics NAV</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics CRM</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics GP</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics SL</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics 365</fullName>
            </value>
            <value>
                <fullName>Microsoft Others</fullName>
            </value>
            <value>
                <fullName>Oracle E-Business Suite</fullName>
            </value>
            <value>
                <fullName>Oracle Fusion</fullName>
            </value>
            <value>
                <fullName>Oracle NetSuite</fullName>
            </value>
            <value>
                <fullName>Oracle Others</fullName>
            </value>
            <value>
                <fullName>Oracle PeopleSoft</fullName>
            </value>
            <value>
                <fullName>SAP Business One</fullName>
            </value>
            <value>
                <fullName>SAP ECC / S4 Hana</fullName>
            </value>
            <value>
                <fullName>SAP Others</fullName>
            </value>
            <value>
                <fullName>SAP B1</fullName>
            </value>
            <value>
                <fullName>Tally ERP 9</fullName>
            </value>
            <value>
                <fullName>Tally Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Project_Awaiting_Kick_Off_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_Awaiting_Kick_Off_Date__c</fullName>
    <label>Project Awaiting Kick Off Date</label>
    <type>Date</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Project_Complete_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_Complete_Live_Date__c</fullName>
    <label>Project Complete/Live Date</label>
    <type>Date</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Project_Estimated_Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_Estimated_Go_Live_Date__c</fullName>
    <label>Project Estimated Go Live Date</label>
    <type>Date</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Project_Scope_Category__c.field-meta.xml
<CustomField>
    <fullName>Project_Scope_Category__c</fullName>
    <label>Project Scope Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Project_Stage__c.field-meta.xml
<CustomField>
    <fullName>Project_Stage__c</fullName>
    <label>Project Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Kick-off</fullName>
            </value>
            <value>
                <fullName>Project Plan</fullName>
            </value>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Churn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Related_Integration_Asset__c.field-meta.xml
<CustomField>
    <fullName>Related_Integration_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Integration Asset</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No integration asset exists of the same module!</errorMessage>
        <filterItems>
            <field>Asset.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Asset.Product2.Family</field>
            <operation>equals</operation>
            <valueField>$Source.Product_Module__c</valueField>
        </filterItems>
        <filterItems>
            <field>Asset.Product2.Product_category__c</field>
            <operation>equals</operation>
            <value>Integration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Linked License Assets</relationshipLabel>
    <relationshipName>Linked_License_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-code/main/default/classes/CTX_AssetDetailsCapture.cls
public class CTX_AssetDetailsCapture {
    
    public static void getAssetDetails(List<Asset> newAssets, Map<Id, Asset> oldAssetMap){
        
        Map<Id, Asset>		accountIdLicenseAssetMap		= new Map<Id, Asset>();
        Set<Id> 			accountIdSet					= new Set<Id>();
        Map<Id, Id>			assetMapIntegrationLicense		= new Map<Id, Id>();
        List<Asset> 		licenseAssets;
        
        for(Asset thisAsset : newAssets){
            
            if(thisAsset.RecordTypeId == AssetConstants.ASSET_INTEGRATION_RECORDTYPEID){
                
                system.debug('I am in Asset After Update / Insert Block');
                accountIdLicenseAssetMap.put(thisAsset.accountId, thisAsset);
            }
        }	/**	Colse of Asset For to Fetch Details	**/
        
        if(accountIdLicenseAssetMap.size() > 0){
            
            licenseAssets = [ SELECT Id, AccountId, Project_Status__c, Project_Stage__c, Project_Awaiting_Kick_Off_Date__c, Project_Complete_Live_Date__c, 
                             Project_Estimated_Go_Live_Date__c, Project_Scope_Category__c, ProductFamily 
                             FROM Asset WHERE 
                             AccountId IN :accountIdLicenseAssetMap.keySet() AND 
                             RecordTypeId = :AssetConstants.ASSET_LICENSE_RECORDTYPEID ];
            
            system.debug('licenseAssets: '+licenseAssets.size());
            for(Asset thisRec : licenseAssets){
                
                
                if(accountIdLicenseAssetMap.containsKey(thisRec.AccountId)){
                    
                    if(thisRec.ProductFamily == 'E-invoice & EWB' ){
                        if(accountIdLicenseAssetMap.get(thisRec.AccountId).ProductFamily == 'E-invoice & EWB'){
                            
                            thisRec.Related_Integration_Asset__c 		= accountIdLicenseAssetMap.get(thisRec.AccountId).Id;
                            thisRec.ERP__c 								= accountIdLicenseAssetMap.get(thisRec.AccountId).ERP__c;
                            thisRec.Project_Status__c 					= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Status__c;
                            thisRec.Project_Stage__c 					= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Stage__c;
                            thisRec.Project_Awaiting_Kick_Off_Date__c	= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Awaiting_Kick_Off_Date__c;
                            thisRec.Project_Complete_Live_Date__c 		= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Complete_Live_Date__c;
                            thisRec.Project_Estimated_Go_Live_Date__c 	= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Estimated_Go_Live_Date__c;
                            thisRec.Project_Scope_Category__c 			= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Scope_Category__c;
                        }
                    }
                    //Start Add Invoicing Product Family by Mohan Raj
                    if(thisRec.ProductFamily == 'Invoicing' ){
                        if(accountIdLicenseAssetMap.get(thisRec.AccountId).ProductFamily == 'Invoicing'){
                            
                            thisRec.Related_Integration_Asset__c 		= accountIdLicenseAssetMap.get(thisRec.AccountId).Id;
                            thisRec.ERP__c 								= accountIdLicenseAssetMap.get(thisRec.AccountId).ERP__c;
                            thisRec.Project_Status__c 					= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Status__c;
                            thisRec.Project_Stage__c 					= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Stage__c;
                            thisRec.Project_Awaiting_Kick_Off_Date__c	= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Awaiting_Kick_Off_Date__c;
                            thisRec.Project_Complete_Live_Date__c 		= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Complete_Live_Date__c;
                            thisRec.Project_Estimated_Go_Live_Date__c 	= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Estimated_Go_Live_Date__c;
                            thisRec.Project_Scope_Category__c 			= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Scope_Category__c;
                        }
                    }
                    //End Added Invoicing Product Family by Mohan Raj
                    if(thisRec.ProductFamily == 'GST' ){
                        
                        if(accountIdLicenseAssetMap.get(thisRec.AccountId).ProductFamily == 'GST'){
                            
                            thisRec.Project_Status__c 					= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Status__c;
                            thisRec.Project_Stage__c 					= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Stage__c;
                            thisRec.Project_Awaiting_Kick_Off_Date__c	= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Awaiting_Kick_Off_Date__c;
                            thisRec.Project_Complete_Live_Date__c 		= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Complete_Live_Date__c;
                            thisRec.Project_Estimated_Go_Live_Date__c 	= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Estimated_Go_Live_Date__c;
                            thisRec.Project_Scope_Category__c 			= accountIdLicenseAssetMap.get(thisRec.AccountId).Project_Scope_Category__c;
                        } 
                    }
                    
                }
            }
        }
        
        if(licenseAssets != NULL){
            
            try{
                RecursiveTriggerHandler.isFirstTime = FALSE; //Added by Ashwin - SOQL 101
                update licenseAssets;
                RecursiveTriggerHandler.isFirstTime = TRUE;
            } catch(Exception ex){
                system.debug('CTX_AssetDetailsCapture Assert Update Fail: '+ex.getMessage());
            }
        }
    }
    
    
}