foundation-objs/main/default/objects/Asset/fields/In_house_project__c.field-meta.xml
<CustomField>
    <fullName>In_house_project__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Derived from source opportunity</description>
    <label>In-House Project</label>
    <type>Checkbox</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Project_Stage__c.field-meta.xml
<CustomField>
    <fullName>Project_Stage__c</fullName>
    <label>Project Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Kick-off</fullName>
            </value>
            <value>
                <fullName>Project Plan</fullName>
            </value>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Churn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{0000}</displayFormat>
        <label>Project  Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Project__c/fields/CTX_SE__c.field-meta.xml
<CustomField>
    <fullName>CTX_SE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/In_house_project__c.field-meta.xml
<CustomField>
    <fullName>In_house_project__c</fullName>
    <defaultValue>false</defaultValue>
    <description>In case this project is in-house need to mandatorily check this field</description>
    <label>In-house project</label>
    <type>Checkbox</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Lead_Developer__c.field-meta.xml
<CustomField>
    <fullName>Lead_Developer__c</fullName>
    <description>In case this is an in-house project, select the name of the lead developer.</description>
    <inlineHelpText>In case this is an in-house project, select the name of the lead developer,</inlineHelpText>
    <label>Lead Developer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abhay Singh</fullName>
            </value>
            <value>
                <fullName>Akhilesh Tiwari</fullName>
            </value>
            <value>
                <fullName>Anand Udhwani</fullName>
            </value>
            <value>
                <fullName>Ankala Balaraju</fullName>
            </value>
            <value>
                <fullName>Anmol Singh</fullName>
            </value>
            <value>
                <fullName>Ashish Kumar</fullName>
            </value>
            <value>
                <fullName>Ashwin Ayyappan</fullName>
            </value>
            <value>
                <fullName>Avinash Mishra</fullName>
            </value>
            <value>
                <fullName>Banesh Dummani</fullName>
            </value>
            <value>
                <fullName>Gottapu Rajesh</fullName>
            </value>
            <value>
                <fullName>Guguloth Lachhiram</fullName>
            </value>
            <value>
                <fullName>Hariharan Ramasamy</fullName>
            </value>
            <value>
                <fullName>Hunny Meghnani</fullName>
            </value>
            <value>
                <fullName>Kamadani Vamsi</fullName>
            </value>
            <value>
                <fullName>Kanagala Shiva Prasad</fullName>
            </value>
            <value>
                <fullName>Kothapalli Bhargavi</fullName>
            </value>
            <value>
                <fullName>Manish Kumar</fullName>
            </value>
            <value>
                <fullName>Mayank Mani</fullName>
            </value>
            <value>
                <fullName>Mohan Ganjalagunte</fullName>
            </value>
            <value>
                <fullName>Mukul Trivedi</fullName>
            </value>
            <value>
                <fullName>Nazneen Nidha</fullName>
            </value>
            <value>
                <fullName>Ninad Patil</fullName>
            </value>
            <value>
                <fullName>Oindrila Biswas</fullName>
            </value>
            <value>
                <fullName>Pintu Kumar</fullName>
            </value>
            <value>
                <fullName>Preksha Singhal</fullName>
            </value>
            <value>
                <fullName>Ramesh Kothapally</fullName>
            </value>
            <value>
                <fullName>Ram Kumar</fullName>
            </value>
            <value>
                <fullName>Roshni Garg</fullName>
            </value>
            <value>
                <fullName>Sachin Mehndiratta</fullName>
            </value>
            <value>
                <fullName>Sakthidoss Gajendran</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Mode_of_Integration__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Integration__c</fullName>
    <label>Mode of Integration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>JSON API</fullName>
            </value>
            <value>
                <fullName>File upload API</fullName>
            </value>
            <value>
                <fullName>FTP</fullName>
            </value>
            <value>
                <fullName>Manual Upload</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Parent_Project__c.field-meta.xml
<CustomField>
    <fullName>Parent_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Pm_Project_Owner_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Pm_Project_Owner_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Owner from the Program Team</description>
    <label>PM Owner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e2x000000UX85</value>
        </filterItems>
        <filterItems>
            <field>User.Username</field>
            <operation>equals</operation>
            <value>shriram.bhat@cleartax.in</value>
        </filterItems>
        <filterItems>
            <field>User.Username</field>
            <operation>equals</operation>
            <value>hanumanthu.jarpala@cleartax.in</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>This field defines for what product has the client chosen integration for</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASP/GSP</fullName>
            </value>
            <value>
                <fullName>EWB</fullName>
            </value>
            <value>
                <fullName>EINV</fullName>
            </value>
            <value>
                <fullName>Max ITC</fullName>
            </value>
            <value>
                <fullName>GSTIN Verification</fullName>
            </value>
            <value>
                <fullName>TDS 206 AB</fullName>
            </value>
            <value>
                <fullName>Invoice Discounting</fullName>
            </value>
            <value>
                <fullName>KSA_EINV_II</fullName>
                <label>KSA EINV II</label>
            </value>
            <value>
                <fullName>KSA EINV I</fullName>
            </value>
            <value>
                <fullName>Clear Capture</fullName>
            </value>
            <value>
                <fullName>DSC</fullName>
            </value>
            <value>
                <fullName>Clear Invoicing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Project_Stage__c.field-meta.xml
<CustomField>
    <fullName>Project_Stage__c</fullName>
    <label>Project Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Kick-off</fullName>
            </value>
            <value>
                <fullName>Project Plan</fullName>
            </value>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Scope_Category__c.field-meta.xml
<CustomField>
    <fullName>Scope_Category__c</fullName>
    <label>Scope Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Consultation</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>AMC</fullName>
            </value>
            <value>
                <fullName>Change Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/SI_Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>SI_Partner_Account__c</fullName>
    <label>SI Partner Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Churn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/recordTypes/AMC_Module.recordType-meta.xml
<RecordType>
    <fullName>AMC_Module</fullName>
    <active>true</active>
    <label>AMC Module</label>
</RecordType>

foundation-code/main/default/classes/ProjectTriggerHelper.cls
/**
* @File Name          : ProjectTriggerHelper.cls
* @Description        : 
* @Author             : Lokesh@SFDeveloper.SFDoc
* @Group              : 
* @Last Modified By   : Lokesh@SFDeveloper.SFDoc
* @Last Modified On   : 07/12/2020, 12:57:38 pm
* @Modification Log   : 
* Ver       Date            Author              Modification
* 1.0    07/12/2020   Lokesh@SFDeveloper.SFDoc     Initial Version
**/
public class ProjectTriggerHelper {
    
    public static void updateIsProjectCompletedINJunction(Map<Id,Project__c> mapOfProjectToUpdateJunction,boolean changed){
        List<AccountProjectAssetJunction__c> listOfAccountProjectAssetJunctions=new List<AccountProjectAssetJunction__c>();
        Set<Id> setOfProjectIds=new Set<Id>();
        setOfProjectIds=mapOfProjectToUpdateJunction.keySet();
        if(setOfProjectIds.size()>0){
            listOfAccountProjectAssetJunctions=DataBase.query(UtilityClass.getQueryString('AccountProjectAssetJunction__c')+' FROM AccountProjectAssetJunction__c WHERE Project__c IN:setOfProjectIds' );
        }
        if(!changed){
            List<AccountProjectAssetJunction__c> listOfAccountProjectAssetJunctionToUpdate=new List<AccountProjectAssetJunction__c>();
            
            if(listOfAccountProjectAssetJunctions.size()>0){
                
                for(AccountProjectAssetJunction__c apaJunctionInstance:listOfAccountProjectAssetJunctions){
                    if(mapOfProjectToUpdateJunction.get(apaJunctionInstance.Project__c).Project_Stage__c!=null){ //isProjectCompleted  = true
                        apaJunctionInstance.Project_Status__c = mapOfProjectToUpdateJunction.get(apaJunctionInstance.Project__c).Project_Stage__c;
                        listOfAccountProjectAssetJunctionToUpdate.add(apaJunctionInstance);
                    }
                    
                }
            }
            if(listOfAccountProjectAssetJunctionToUpdate.size()>0){
                ProjectConstants.isFirstTimeApa = FALSE;
                ProjectConstants.isFirstTimeProject  = FALSE;
                RecursiveTriggerHandler.isFirstTime = FALSE;

                update listOfAccountProjectAssetJunctionToUpdate;
                
                ProjectConstants.isFirstTimeApa = TRUE;
                ProjectConstants.isFirstTimeProject  = TRUE;
                RecursiveTriggerHandler.isFirstTime = TRUE;
            }
        }
        else{
            if(listOfAccountProjectAssetJunctions.size()>0){
                ProjectConstants.isFirstTimeApa = FALSE;
                ProjectConstants.isFirstTimeProject  = FALSE;
                RecursiveTriggerHandler.isFirstTime = FALSE;

                update listOfAccountProjectAssetJunctions;

                ProjectConstants.isFirstTimeApa = TRUE;
                ProjectConstants.isFirstTimeProject  = TRUE;
                RecursiveTriggerHandler.isFirstTime = TRUE;
            }
        }
        
    }
    
    //bhaveshjindal
    //send email notification to CSM and Account Owner if project status changes to Churn or stage changes to Live.
    public static void sendEmailNotification(List<Project__c> projectList){
        Id 					defaultMailId 				= [ SELECT Id FROM OrgWideEmailAddress WHERE 
                                                           Address = 'notification@support.clear.in']?.Id;
        List<Messaging.SingleEmailMessage> 	mailList 	= new List<Messaging.SingleEmailMessage>();
        List<String> 		errorMessages 				= new List<String>();
        Set<Id> projectIds = new Set<Id>();
        List<AccountProjectAssetJunction__c> apaJunctionList = new List<AccountProjectAssetJunction__c>();
        Map<Id, AccountProjectAssetJunction__c> apaJunctionMap = new Map<Id, AccountProjectAssetJunction__c>();
        for(Project__c thisProject : projectList){
            projectIds.add(thisProject.Id);
        }
        apaJunctionList = [ SELECT Project__r.Id, Project__c , Customer_Account__c , Asset__c , Customer_Account__r.Owner.Email , Customer_Account__r.Onboarding_Owner__r.Email FROM AccountProjectAssetJunction__c 
                           WHERE Project__c IN : projectIds ];
        
        if(apaJunctionList.size()>0){
            
            for(AccountProjectAssetJunction__c thisApaJunction : apaJunctionList){
                apaJunctionMap.put(thisApaJunction.Project__r.Id, thisApaJunction);
            }
            
            for(Project__c thisProject : projectList){
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.SaveAsActivity = TRUE;
                mail.setWhatId(thisProject.Id);
                List<String> ccAddresses = new List<String>();
                List<String> toAddresses = new List<String>();
                String subject ='';
                
                if(thisProject.Project_Stage__c == 'Live'){
                    subject = thisProject.Name+' is live now.';
                }
                if(thisProject.Status__c == 'Churn'){
                    subject ='Project Status Changed to Churn.';
                }
                
                //toAddresses.add(apaJunctionMap.get(thisProject.Id).Customer_Account__r.Owner.Email);
                
                toAddresses.add(apaJunctionMap.get(thisProject.Id).Customer_Account__r.Onboarding_Owner__r.Email);
                
                String body = '';
                if(thisProject.Status__c == 'Churn'){
                    body += 'Status Changed to Churn for below Project. Please take necessary action.'+'<br/>';
                }
                String Recordlink = URL.getSalesforceBaseUrl().toExternalForm()+'/'+thisProject.Id;
                if(thisProject.Project_Stage__c == 'Live'){
                    body += thisProject.Name+' is live now.'+'<br/>';
                    body += 'Please update status in license & integration assets - so that finance can bill accordingly.';
                }
                body += '<br/>';
                body += '<a href='+Recordlink+'>' + thisProject.Name + '</a><br/><br/>';
              
                mail.setSubject(subject);
                mail.setHtmlBody(body);
                mail.setToAddresses(toAddresses);
                mail.setCcAddresses(ccAddresses);
                mail.setOrgWideEmailAddressId(defaultMailId);
                mailList.add(mail);
            }
            system.debug('mailList: '+mailList.size());
            if(!mailList.isEmpty()) {
                try{
                    Messaging.sendEmail(mailList);
                }
                catch (Exception ex) {
                    errorMessages.add('Unable to send email'+ ex.getMessage());
                }
            }
        }
    }
    
    /** Start :: bhaveshjindal :: update fields on AMC module when parent project is tagged **/
    public static void updateAmcFields(Map<Id,Project__c> newProjectsMap){
        System.debug('<-- updateAmcFields Entered -->');
        System.debug('newProjectsMap :: '+newProjectsMap);
        set<Id> parentProjectIds = new set<Id>();
        for(Project__c thisAmc : newProjectsMap.values()){
            parentProjectIds.add(thisAmc.Parent_Project__c);
        }
        Map<Id,Project__c> parentProjectMap = new Map<Id,Project__c>([SELECT Id, CTX_SE__c, Lead_Developer__c, Pm_Project_Owner_Lookup__c, 
                                                                      SI_Partner_Account__c, In_house_project__c, Status__c, Scope_Category__c, 
                                                                      Mode_Of_Integration__c, Product__c, Client_ERP__c, Account_Owner_CSM__c, 
                                                                      Customer_Account_Owner__c,Delivery_Owner__c
                                                                      FROM Project__c WHERE Id IN :parentProjectIds ]);
        System.debug('parentProjectMap :: '+parentProjectMap)
            ;
        try{
            
            if(!parentProjectMap.isEmpty()){
                for(Id thisAmcId : newProjectsMap.keySet()){
                    
                    Project__c	thisAmc 					= newProjectsMap.get(thisAmcId);
                    
                    if(parentProjectMap.containsKey(thisAmc.Parent_Project__c)){
                        
                        if(!thisAmc.Is_Parent_Project_Overridden__c ){
                            thisAmc.Is_Parent_Project_Overridden__c = TRUE;
                            thisAmc.CTX_SE__c 						= parentProjectMap.get(thisAmc.Parent_Project__c).CTX_SE__c;
                            thisAmc.Lead_Developer__c 				= parentProjectMap.get(thisAmc.Parent_Project__c).Lead_Developer__c;
                            thisAmc.Pm_Project_Owner_Lookup__c 		= parentProjectMap.get(thisAmc.Parent_Project__c).Pm_Project_Owner_Lookup__c;
                            thisAmc.SI_Partner_Account__c 			= parentProjectMap.get(thisAmc.Parent_Project__c).SI_Partner_Account__c;
                            thisAmc.In_house_project__c 			= parentProjectMap.get(thisAmc.Parent_Project__c).In_house_project__c;
                            thisAmc.Status__c 						= parentProjectMap.get(thisAmc.Parent_Project__c).Status__c;
                         /* thisAmc.Scope_Category__c 				= parentProjectMap.get(thisAmc.Parent_Project__c).Scope_Category__c;*/
                            thisAmc.Mode_Of_Integration__c 			= parentProjectMap.get(thisAmc.Parent_Project__c).Mode_Of_Integration__c;
                            thisAmc.Product__c 						= parentProjectMap.get(thisAmc.Parent_Project__c).Product__c;
                            thisAmc.Client_ERP__c  					= parentProjectMap.get(thisAmc.Parent_Project__c).Client_ERP__c;
                            thisAmc.Account_Owner_CSM__c 			= parentProjectMap.get(thisAmc.Parent_Project__c).Account_Owner_CSM__c;
                            thisAmc.Customer_Account_Owner__c 		= parentProjectMap.get(thisAmc.Parent_Project__c).Customer_Account_Owner__c;
                            thisAmc.Delivery_Owner__c 				= parentProjectMap.get(thisAmc.Parent_Project__c).Delivery_Owner__c;
                        }else{
                            thisAmc.CTX_SE__c 						= thisAmc.CTX_SE__c 					!= NULL	? 
                                thisAmc.CTX_SE__c 					: parentProjectMap.get(thisAmc.Parent_Project__c).CTX_SE__c;
                            thisAmc.Lead_Developer__c 				= thisAmc.Lead_Developer__c 			!= NULL	? 
                                thisAmc.Lead_Developer__c 			: parentProjectMap.get(thisAmc.Parent_Project__c).Lead_Developer__c;
                            thisAmc.Pm_Project_Owner_Lookup__c 		= thisAmc.Pm_Project_Owner_Lookup__c 	!= NULL	? 
                                thisAmc.Pm_Project_Owner_Lookup__c 	: parentProjectMap.get(thisAmc.Parent_Project__c).Pm_Project_Owner_Lookup__c;
                            thisAmc.SI_Partner_Account__c 			= thisAmc.SI_Partner_Account__c 		!= NULL	? 
                                thisAmc.SI_Partner_Account__c 		: parentProjectMap.get(thisAmc.Parent_Project__c).SI_Partner_Account__c;
                            thisAmc.In_house_project__c 			= thisAmc.In_house_project__c 			!= NULL	? 
                                thisAmc.In_house_project__c 			: parentProjectMap.get(thisAmc.Parent_Project__c).In_house_project__c;
                            thisAmc.Status__c 						= thisAmc.Status__c 					!= NULL	? 
                                thisAmc.Status__c 					: parentProjectMap.get(thisAmc.Parent_Project__c).Status__c;
                         /* thisAmc.Scope_Category__c 				= thisAmc.Scope_Category__c 			!= NULL	? 
                                thisAmc.Scope_Category__c 			: parentProjectMap.get(thisAmc.Parent_Project__c).Scope_Category__c;*/
                            thisAmc.Mode_Of_Integration__c 			= thisAmc.Mode_Of_Integration__c 		!= NULL	? 
                                thisAmc.Mode_Of_Integration__c 		: parentProjectMap.get(thisAmc.Parent_Project__c).Mode_Of_Integration__c;
                            thisAmc.Product__c 						= thisAmc.Product__c 					!= NULL	? 
                                thisAmc.Product__c 					: parentProjectMap.get(thisAmc.Parent_Project__c).Product__c;
                            thisAmc.Client_ERP__c  					= thisAmc.Client_ERP__c 				!= NULL	? 
                                thisAmc.Client_ERP__c 				: parentProjectMap.get(thisAmc.Parent_Project__c).Client_ERP__c;
                            thisAmc.Account_Owner_CSM__c 			= thisAmc.Account_Owner_CSM__c 			!= NULL	? 
                                thisAmc.Account_Owner_CSM__c 			: parentProjectMap.get(thisAmc.Parent_Project__c).Account_Owner_CSM__c;
                            thisAmc.Customer_Account_Owner__c 		= thisAmc.Customer_Account_Owner__c 	!= NULL	? 
                                thisAmc.Customer_Account_Owner__c 	: parentProjectMap.get(thisAmc.Parent_Project__c).Customer_Account_Owner__c;
                            thisAmc.Delivery_Owner__c 				= thisAmc.Delivery_Owner__c 	!= NULL	? 
                                thisAmc.Delivery_Owner__c 			: parentProjectMap.get(thisAmc.Parent_Project__c).Delivery_Owner__c;
                        }
                    }
                }
            }
        } catch(Exception e){
            System.debug('Error in updateing amc module fields on populatin Parent Project : '+e.getMessage()+'line : '+e.getLineNumber());
        }
        
    }
    
    public static void autoUpdateAmcFields(Map<Id,Project__c> newProjectsMap, Map<Id,Project__c> oldProjectsMap){
        
        Map<Id,Project__c> amcModuleMap = new Map<Id,Project__c>([SELECT Id, Parent_Project__c, Name, Scope_Category__c, 
                                                                  Mode_Of_Integration__c, Product__c, Client_ERP__c, 
                                                                  Account_Owner_CSM__c, Customer_Account_Owner__c,Delivery_Owner__c
                                                                  FROM Project__c 
                                                                  WHERE RecordType.DeveloperName = 'AMC_Module'
                                                                  AND Parent_Project__c IN :newProjectsMap.keySet()]);
        System.debug('amcModuleMap :: '+amcModuleMap);
        List<Project__c> amcModulesToUpdate = new List<Project__c>();
        if(!amcModuleMap.isEmpty()){
            for(Project__c thisAMC : amcModuleMap.Values()){
                
              /*thisAMC.Scope_Category__c = 
                    ( thisAMC.Scope_Category__c == oldProjectsMap.get(thisAMC.Parent_Project__c).Scope_Category__c ) ? 
                    newProjectsMap.get(thisAMC.Parent_Project__c).Scope_Category__c : thisAMC.Scope_Category__c;*/
                
                thisAMC.Mode_Of_Integration__c = 
                    ( thisAMC.Mode_Of_Integration__c == oldProjectsMap.get(thisAMC.Parent_Project__c).Mode_Of_Integration__c ) ? 
                    newProjectsMap.get(thisAMC.Parent_Project__c).Mode_Of_Integration__c : thisAMC.Mode_Of_Integration__c;
                
                thisAMC.Product__c = 
                    ( thisAMC.Product__c == oldProjectsMap.get(thisAMC.Parent_Project__c).Product__c ) ? 
                    newProjectsMap.get(thisAMC.Parent_Project__c).Product__c : thisAMC.Product__c;
                
                thisAMC.Client_ERP__c = 
                    ( thisAMC.Client_ERP__c == oldProjectsMap.get(thisAMC.Parent_Project__c).Client_ERP__c ) ? 
                    newProjectsMap.get(thisAMC.Parent_Project__c).Client_ERP__c : thisAMC.Client_ERP__c;
                
                thisAMC.Account_Owner_CSM__c = 
                    ( thisAMC.Account_Owner_CSM__c == oldProjectsMap.get(thisAMC.Parent_Project__c).Account_Owner_CSM__c ) ? 
                    newProjectsMap.get(thisAMC.Parent_Project__c).Account_Owner_CSM__c : thisAMC.Account_Owner_CSM__c;
                
                thisAMC.Customer_Account_Owner__c = 
                    ( thisAMC.Customer_Account_Owner__c == oldProjectsMap.get(thisAMC.Parent_Project__c).Customer_Account_Owner__c ) ? 
                    newProjectsMap.get(thisAMC.Parent_Project__c).Customer_Account_Owner__c : thisAMC.Customer_Account_Owner__c;
                
                thisAMC.Delivery_Owner__c = 
                    ( thisAMC.Delivery_Owner__c == oldProjectsMap.get(thisAMC.Parent_Project__c).Delivery_Owner__c ) ? 
                    newProjectsMap.get(thisAMC.Parent_Project__c).Delivery_Owner__c : thisAMC.Delivery_Owner__c;
                
                amcModulesToUpdate.add(thisAMC);
            }
        }
        System.debug('amcModulesToUpdate :: '+amcModulesToUpdate);
        if(amcModulesToUpdate.size()>0){
            try{
                Update amcModulesToUpdate;
            }catch(Exception e){
                System.debug('Error in auto updateing amc module fields on updating Parent Project : '+e.getMessage()+' line : '+e.getLineNumber());
            }
        }
    }
    
    @future
    public static void assetSoftUpdate(Set<Id> projIds){
        List<Asset> assetSoftUpdateList = new List<Asset>();
        
        
        for(AccountProjectAssetJunction__c apaJunctionInstance : [SELECT Id, Project__c, Asset__c 	
                                                                  FROM AccountProjectAssetJunction__c	
                                                                  WHERE Project__c IN :projIds]	
           ){	
               Asset tempAsset = new Asset (Id = apaJunctionInstance.Asset__c);	
               assetSoftUpdateList.add(tempAsset);	
           }	

       if(assetSoftUpdateList.size()>0){	
           update assetSoftUpdateList;	
       }
        
    }
    
    
}