foundation-objs/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Billing_Details__c/Billing_Details__c.object-meta.xml
<CustomObject>
    <label>Billing &amp; Risk</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing &amp; Risk</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Billing_Details__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipName>Billing_Details</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Billing_Details__c/fields/Support_required__c.field-meta.xml
<CustomField>
    <fullName>Support_required__c</fullName>
    <label>Support required</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

foundation-code/main/default/classes/CTX_BillingDetailsTriggerHelper.cls
public class CTX_BillingDetailsTriggerHelper {
    
    public static void postSupportRequired(Map<Id,Billing_Details__c> newBillingMap, Map<Id,Billing_Details__c> oldBillingMap){
        List<Billing_Details__c> billingListCollection = new List<Billing_Details__c>();
        List<Billing_Details__c> billingListRisk = new List<Billing_Details__c>();
        List<FeedItem>	postList 	= new List<FeedItem>();
        
        for(Billing_Details__c thisRec : newBillingMap.values()){
            if(thisRec.Support_Required__c != oldBillingMap.get(thisRec.Id).Support_Required__c &&
               thisRec.Support_Required__c != NULL){
                   billingListCollection.add(thisRec);
               }
            if(thisRec.Support_required_Risk__c  != oldBillingMap.get(thisRec.Id).Support_required_Risk__c  &&
               thisRec.Support_required_Risk__c  != NULL){
                   billingListRisk.add(thisRec);
               }
        }
        
        if(billingListCollection.size()>0){
            for(Billing_Details__c thisRec : billingListCollection){
                FeedItem post = new FeedItem();
                post.ParentId = thisRec.Id;
                post.Body = thisRec.Support_Required__c;
                
                postList.add(post);
            }
        }
        
          if(billingListRisk.size()>0){
            for(Billing_Details__c thisRec : billingListRisk){
                FeedItem post = new FeedItem();
                post.ParentId = thisRec.Id;
                post.Body = thisRec.Support_required_Risk__c;
                
                postList.add(post);
            }
        }
        
        if(!postList.isEmpty()){
            Insert postList;
        }
      
    }
    
    public static void fetchActionOwner(List<Billing_Details__c> billingDetails){
        List<Billing_Details__c> billingList = new List<Billing_Details__c> ();
        Set<Id> assetIds = new Set<Id>();
        
        for(Billing_Details__c thisRec : billingDetails){
            if(thisRec.Donot_Override__c == FALSE){
                billingList.add(thisRec);
                assetIds.add(thisRec.Asset__c);
            }
        }
        
        Map<Id,Asset> assetMap = new Map<Id,Asset>([SELECT Id, opportunity__c,Account.Sales_Owner__c,
                                                    opportunity__r.OwnerId, opportunity__r.Owner.isActive,
                                                    Account.Sales_Owner__r.isActive,
                                                    Account.OwnerId
                                                    FROM Asset
                                                    WHERE Id IN :assetIds]);
        
        for(Billing_Details__c thisRec : billingList){
            if(assetMap.containsKey(thisRec.Asset__c) &&
               assetMap.get(thisRec.Asset__c).opportunity__c != NULL && 
               assetMap.get(thisRec.Asset__c).opportunity__r.OwnerId != NULL &&
               assetMap.get(thisRec.Asset__c).opportunity__r.Owner.isActive)
            {
                thisRec.Action_Owner_Collection__c  = assetMap.get(thisRec.Asset__c).opportunity__r.OwnerId;
            }else if(assetMap.get(thisRec.Asset__c).Account.Sales_Owner__c != NULL &&
                     assetMap.get(thisRec.Asset__c).Account.Sales_Owner__r.isActive)
            {
                thisRec.Action_Owner_Collection__c  = assetMap.get(thisRec.Asset__c).Account.Sales_Owner__c;
            }else{
                thisRec.Action_Owner_Collection__c  = assetMap.get(thisRec.Asset__c).Account.OwnerId;
            }
        }
    }
    
}