foundation-objs/main/default/objects/Asset/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>Choose Q1/ Q2/ Q3</description>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Q1 : Non Max ITC/MS/API/AMC/Non-integration related Assets</fullName>
            </value>
            <value>
                <fullName>Q2 : Non Max ITC/MS/API/AMC but integration involved from CT Side</fullName>
            </value>
            <value>
                <fullName>Q3 : Max ITC/MS/API/AMC/Uneecops and client side Integration Assets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/recordTypes/Integration_Asset.recordType-meta.xml
<RecordType>
    <fullName>Integration_Asset</fullName>
    <active>true</active>
    <label>Integration Asset</label>
</RecordType>

foundation-objs/main/default/objects/Asset/recordTypes/Integration_Asset_ID.recordType-meta.xml
<RecordType>
    <fullName>Integration_Asset_ID</fullName>
    <active>true</active>
    <label>Integration Asset - ID</label>
</RecordType>

foundation-objs/main/default/objects/Asset/recordTypes/License_Asset.recordType-meta.xml
<RecordType>
    <fullName>License_Asset</fullName>
    <active>true</active>
    <label>License Asset</label>
</RecordType>

foundation-objs/main/default/objects/Asset/recordTypes/License_Asset_ID.recordType-meta.xml
<RecordType>
    <fullName>License_Asset_ID</fullName>
    <active>true</active>
    <label>License Asset - ID</label>
</RecordType>

foundation-objs/main/default/objects/Asset/recordTypes/One_Time_Asset.recordType-meta.xml
<RecordType>
    <fullName>One_Time_Asset</fullName>
    <active>true</active>
    <label>One Time Asset</label>
</RecordType>

foundation-objs/main/default/objects/Task/recordTypes/Asset_Create.recordType-meta.xml
<RecordType>
    <fullName>Asset_Create</fullName>
    <active>true</active>
    <label>Asset Create</label>
</RecordType>

foundation-objs/main/default/objects/Task/recordTypes/Asset_Delete.recordType-meta.xml
<RecordType>
    <fullName>Asset_Delete</fullName>
    <active>true</active>
    <label>Asset Delete</label>
</RecordType>

foundation-objs/main/default/objects/Task/recordTypes/Asset_Update.recordType-meta.xml
<RecordType>
    <fullName>Asset_Update</fullName>
    <active>true</active>
    <label>Asset Update</label>
</RecordType>

foundation-code/main/default/classes/AssetConstants.cls
public class AssetConstants {

    public static Boolean TASK_APPROVAL 								= FALSE;
    public static Boolean isFirstTimeAdditionalGstin					= TRUE;
    public static Boolean isRun											= TRUE;
    public static final String RENEWAL_PENDING							='Renewal Pending';
    public static final String RENEWED									='Renewed';
    public static final String RECORD_TYPE_NAME_LICENCED_ASSET 			= 'License_Asset';
    public static final String RECORD_TYPE_NAME_INTEGRATION_ASSET 		= 'Integration_Asset';
    public static final String RECORD_TYPE_NAME_ONETIME_ASSET 			= 'One_Time_Asset';
    public static final String ONBOARDING_STATUS_ONBOARDING_COMPLETED 	= 'Onboarding Complete';
    public static final String INTEGRATION_STATUS_PROJECT_COMPLETED 	= 'Project complete';
    public static final String STATUS_ACTIVE 							= 'Active';
    public static final String STATUS_RENEWAL_PENDING 					= 'Renewal Pending';
    public static final String STATUS_UPCOMING_RENEWAL 					= 'Upcoming Renewal';
    public static final String STATUS_AT_RISK 							= 'At Risk';
    public static final String STATUS_INACTIVE 							= 'Inactive';
    public static final String STATUS_EXPERIED	 						= 'Expired';
    public static final String STATUS_CHURN 							= 'Churn';
    public static final String STATUS_SALES_RETURN 						= 'Sales return';
    public static final String STATUS_VALID_RENEWED 					= 'Valid & Renewed';
    public static final Id ASSET_UPDATE_RecordTypeId					= Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Asset_Update').getRecordTypeId();
    public static final Id ASSET_CREATE_RecordTypeId					= Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Asset_Create').getRecordTypeId();
    public static final Id ASSET_DELETE_RecordTypeId					= Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Asset_Delete').getRecordTypeId();
    PUBLIC STATIC FINAL ID ASSET_INTEGRATION_RECORDTYPEID 				= Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get('Integration_Asset').getRecordTypeId();
    public static final Id ASSET_LICENSE_RECORDTYPEID					= Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get('License_Asset').getRecordTypeId();
    public static final Id ASSET_LICENSEID_RECORDTYPEID					= Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get('License_Asset_ID').getRecordTypeId();
    public static final Id ASSET_INTEGRATIONID_RECORDTYPEID				= Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get('Integration_Asset_ID').getRecordTypeId();
    public static final Id ASSET_ONETIMEASSET_RECORDTYPEID						= Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get(AssetConstants.RECORD_TYPE_NAME_ONETIME_ASSET).getRecordTypeId();
    
    public static Boolean LICENSING_SYNC_FLOW_RUN 							= TRUE;
    public static Boolean SALES_SYNC_FLOW_RUN    							= TRUE;
    
    public static Map<Id, Boolean> CSMAssets (set<Id> assetIds) {
        Map<Id, Boolean> assetCSMValidationMap = new Map<Id, Boolean>();
        for(Asset asst : [SELECT Id, Name, Account.ARR_Total_Amount__c, Product2.Product_Category__c FROM Asset 
                          WHERE Id IN : assetIds AND 
                          RecordTypeId IN : new Set<Id>{ASSET_LICENSE_RECORDTYPEID, ASSET_LICENSEID_RECORDTYPEID}]
           ){
               if(asst.Account.ARR_Total_Amount__c > 50000 && asst.Product2.Product_Category__c != 'MS'){
                   assetCSMValidationMap.put(asst.Id, true);
               }else {
                   assetCSMValidationMap.put(asst.Id, false);
               }
           }
        return assetCSMValidationMap;
    }


}