foundation-objs/main/default/objects/Asset/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onboarding</fullName>
                <default>true</default>
                <label>Onboarding</label>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/E_Sign_Customer_Info__c.field-meta.xml
<CustomField>
    <fullName>E_Sign_Customer_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>E-Sign Customer Info</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Mark Esign customer contact as communicable by navigating to the contact</errorMessage>
        <filterItems>
            <field>Contact.Email</field>
            <operation>notContain</operation>
            <value>cleartax.in</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Is_Communicable__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes_llq</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/E_Sign_Status__c.field-meta.xml
<CustomField>
    <fullName>E_Sign_Status__c</fullName>
    <defaultValue>&apos;E-Sign&apos;</defaultValue>
    <label>E-Sign Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>E-Sign Request Sent</fullName>
            </value>
            <value>
                <fullName>E-Sign Unsuccessful</fullName>
            </value>
            <value>
                <fullName>E-Sign Successful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/ESign_BE_Docket_ID__c.field-meta.xml
<CustomField>
    <fullName>ESign_BE_Docket_ID__c</fullName>
    <label>ESign BE Docket ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/ESign_BE_Document_ID__c.field-meta.xml
<CustomField>
    <fullName>ESign_BE_Document_ID__c</fullName>
    <label>ESign BE Document ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/ESign_Category__c.field-meta.xml
<CustomField>
    <fullName>ESign_Category__c</fullName>
    <label>ESign Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E-Sign</fullName>
                <default>true</default>
                <label>E-Sign</label>
            </value>
            <value>
                <fullName>Physical Sign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/ESign_CTX_Status__c.field-meta.xml
<CustomField>
    <fullName>ESign_CTX_Status__c</fullName>
    <label>ESign CTX Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/ESign_Doc_Updated__c.field-meta.xml
<CustomField>
    <fullName>ESign_Doc_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ESign Doc Updated</label>
    <type>Checkbox</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/ESign_Message__c.field-meta.xml
<CustomField>
    <fullName>ESign_Message__c</fullName>
    <label>ESign Message</label>
    <type>TextArea</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Physical_Sign_completed__c.field-meta.xml
<CustomField>
    <fullName>Physical_Sign_completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Physical Sign completed?</label>
    <type>Checkbox</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Retrigger_E_Sign__c.field-meta.xml
<CustomField>
    <fullName>Retrigger_E_Sign__c</fullName>
    <description>Used to re-trigger E-Sign</description>
    <inlineHelpText>Re- send E-Sign</inlineHelpText>
    <label>Retrigger E-Sign</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resend</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
                <label>Sent - Updated Automatically</label>
            </value>
            <value>
                <fullName>Sent Successfully</fullName>
                <label>Sent Successfully - Updated Automatically</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/recordTypes/Upsell.recordType-meta.xml
<RecordType>
    <fullName>Upsell</fullName>
    <active>true</active>
    <businessProcess>Net New%2C Cross Sell%2FUpsell and Partner Success</businessProcess>
    <description>Used for Upsell</description>
    <label>Upsell</label>
</RecordType>

foundation-objs/main/default/objects/Upsell_Top_up__c/Upsell_Top_up__c.object-meta.xml
<CustomObject>
    <label>Upsell - Top-up</label>
    <nameField>
        <label>Upsell - Top-up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Upsell - Top-ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finance Approval In Progress</fullName>
            </value>
            <value>
                <fullName>Finance Approval Approved</fullName>
            </value>
            <value>
                <fullName>Finance Approval Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/E_Sign_Customer_Info__c.field-meta.xml
<CustomField>
    <fullName>E_Sign_Customer_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>E-Sign Customer Info</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Upsell - Top-ups</relationshipLabel>
    <relationshipName>Upsell_Top_ups</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/E_Sign_Status__c.field-meta.xml
<CustomField>
    <fullName>E_Sign_Status__c</fullName>
    <label>E-Sign Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>E-Sign Request Sent</fullName>
            </value>
            <value>
                <fullName>E-Sign Unsuccessful</fullName>
            </value>
            <value>
                <fullName>E-Sign Successful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/ESign_BE_Docket_ID__c.field-meta.xml
<CustomField>
    <fullName>ESign_BE_Docket_ID__c</fullName>
    <label>ESign BE Docket ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/ESign_BE_Document_ID__c.field-meta.xml
<CustomField>
    <fullName>ESign_BE_Document_ID__c</fullName>
    <label>ESign BE Document ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/ESign_Category__c.field-meta.xml
<CustomField>
    <fullName>ESign_Category__c</fullName>
    <label>ESign Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E-Sign</fullName>
            </value>
            <value>
                <fullName>Physical Sign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/ESign_Client_Status__c.field-meta.xml
<CustomField>
    <fullName>ESign_Client_Status__c</fullName>
    <label>ESign Client Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/ESign_CTX_Status__c.field-meta.xml
<CustomField>
    <fullName>ESign_CTX_Status__c</fullName>
    <label>ESign CTX Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/ESign_Doc_Updated__c.field-meta.xml
<CustomField>
    <fullName>ESign_Doc_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ESign Doc Updated</label>
    <type>Checkbox</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/ESign_Message__c.field-meta.xml
<CustomField>
    <fullName>ESign_Message__c</fullName>
    <label>ESign Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Physical_Sign_Completed__c.field-meta.xml
<CustomField>
    <fullName>Physical_Sign_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Physical Sign Completed?</label>
    <type>Checkbox</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Retrigger_E_Sign__c.field-meta.xml
<CustomField>
    <fullName>Retrigger_E_Sign__c</fullName>
    <label>Retrigger E-Sign</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resend</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
                <label>Sent - Updated Automatically</label>
            </value>
            <value>
                <fullName>Sent Successfully</fullName>
                <label>Sent Successfully - Updated Automatically</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Request</fullName>
                <default>true</default>
                <label>New Request</label>
            </value>
            <value>
                <fullName>Billing Details</fullName>
            </value>
            <value>
                <fullName>Finance Approval</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closed Won</fullName>
                <default>true</default>
                <label>Closed Won</label>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/fields/Upsell_close_date__c.field-meta.xml
<CustomField>
    <fullName>Upsell_close_date__c</fullName>
    <label>Upsell close date</label>
    <type>Date</type>
</CustomField>

foundation-objs/main/default/objects/Upsell_Top_up__c/recordTypes/Upsell.recordType-meta.xml
<RecordType>
    <fullName>Upsell</fullName>
    <active>true</active>
    <label>Upsell</label>
</RecordType>

foundation-code/main/default/classes/UpsellTriggerHandler.cls
public without sharing class UpsellTriggerHandler implements TriggerInterface{
    
    
    public void beforeInsert(List<sObject> listofNewsObjectRecords){}
    
    public void afterInsert(List<sObject> listofNewsObjectRecords, Map<Id,sObject> mapofNewsObjectRecords){
        
        Map<Id, Upsell_Top_up__c> 	newUpsellMap = (Map<Id, Upsell_Top_up__c>)mapofNewsObjectRecords;
        Map<Id,Upsell_Top_up__c>	mapOfNewUpsellToUpdate	= new Map<Id,Upsell_Top_up__c>();
        
        if(newUpsellMap.size()>0){
            UpsellTriggerHelper.checkUpsell(newUpsellMap);
            //UpsellTriggerHelper.updateAdditionalGstinAddOnSplit(newUpsellMap);
        }
   
    }
    
    public void beforeUpdate(map<id,sObject> mapofNewsObjectRecords,map<id,sObject> mapofOldsObjectRecords){
        Map<Id, Upsell_Top_up__c> 	newUpsellMap 								= (Map<Id, Upsell_Top_up__c>)mapofNewsObjectRecords;
        Map<Id, Upsell_Top_up__c> 	oldUpsellMap 								= (Map<Id, Upsell_Top_up__c>)mapofOldsObjectRecords;
        Map<Id,Upsell_Top_up__c>	mapOfUpsellToUpdate							= new Map<Id,Upsell_Top_up__c>();
        Map<Id,Upsell_Top_up__c>	mapOfUpsellToValidateAdditionalGstins		= new Map<Id,Upsell_Top_up__c>();
        List<Upsell_Top_up__c>		listOfPhysicalSignUpsForOrderFormValidation	= new List<Upsell_Top_up__c>();
        
        for(Id key:newUpsellMap.KeySet()){
            Upsell_Top_up__c UpsellNewInstance=(Upsell_Top_up__c)newUpsellMap.get(key);
            Upsell_Top_up__c UpsellOldInstance=(Upsell_Top_up__c)oldUpsellMap.get(key);
            
            /** @Ashwin - Check if Additional Gstin is added to Upsell **/
            if(UpsellNewInstance.Stage__c != UpsellOldInstance.Stage__c && 
               UpsellNewInstance.Stage__c == 'Finance Approval'){		
                   mapOfUpsellToValidateAdditionalGstins.put(UpsellNewInstance.Id,UpsellNewInstance);
               }
            
            /** @Ashwin - Reset eSign params when stage moved back from Fin Approval **/
            if((UpsellNewInstance.Stage__c != UpsellOldInstance.Stage__c) &&
               UpsellNewInstance.Stage__c != 'Finance Approval'           &&
               UpsellNewInstance.Stage__c != 'Closed')
            {		
                UpsellNewInstance.E_Sign_Status__c 			= NULL;
                UpsellNewInstance.ESign_CTX_Status__c 		= NULL;
                UpsellNewInstance.ESign_Client_Status__c 	= NULL;
                UpsellNewInstance.ESign_Message__c 			= NULL;
                UpsellNewInstance.Retrigger_E_Sign__c 		= NULL;
                UpsellNewInstance.ESign_Doc_Updated__c 		= FALSE;
                UpsellNewInstance.Physical_Sign_Completed__c= FALSE;
                
            }
            
            
            /** @Ashwin - Reset eSign params when Physical_Sign_completed__c is unchecked OR Re-triggered for eSign **/
            if(
                (
                    UpsellNewInstance.Physical_Sign_completed__c != UpsellOldInstance.Physical_Sign_completed__c &&
                    !UpsellNewInstance.Physical_Sign_completed__c
                ) 
                || 
                (
                    String.isNotBlank(UpsellNewInstance.Retrigger_E_Sign__c) 						&&  
                    UpsellOldInstance.Retrigger_E_Sign__c != UpsellNewInstance.Retrigger_E_Sign__c  &&
                    UpsellNewInstance.Retrigger_E_Sign__c   == 'Resend'
                )
            ){
                
                UpsellNewInstance.E_Sign_Status__c 			= NULL;
                UpsellNewInstance.ESign_CTX_Status__c 		= NULL;
                UpsellNewInstance.ESign_Message__c 			= NULL;
                UpsellNewInstance.ESign_Client_Status__c 	= NULL;
                UpsellNewInstance.ESign_Doc_Updated__c 		= FALSE;
            }
            
            
            /** @Ashwin - Update Upsell Stage to Closed Won when ESign Status is Successfull **/
            if((UpsellNewInstance.E_Sign_Status__c != UpsellOldInstance.E_Sign_Status__c) && UpsellNewInstance.E_Sign_Status__c == 'E-Sign Successful'){
                mapOfUpsellToUpdate.put(UpsellNewInstance.Id,UpsellNewInstance);
            }
            
            /** @Ashwin - Check signed order form is attached when Physical_Sign_completed__c is checked **/
            if(
                UpsellNewInstance.ESign_Category__c == 'Physical Sign' && 
                UpsellNewInstance.Physical_Sign_completed__c == TRUE && 
                UpsellOldInstance.Physical_Sign_completed__c == FALSE
            ){
                listOfPhysicalSignUpsForOrderFormValidation.add(UpsellNewInstance);
            }
            
            /** @Ashwin - Update closed date when Upsell is closed **/
            if((UpsellNewInstance.Stage__c != UpsellOldInstance.Stage__c) && UpsellNewInstance.Stage__c == 'Closed'){		
                UpsellNewInstance.Upsell_close_date__c = System.TODAY();
            }
            
        }
        
        /** @Ashwin - Check if Additional Gstin is added to Upsell **/
        if(mapOfUpsellToValidateAdditionalGstins.size()>0){
            UpsellTriggerHelper.validateAdditionalGstins(mapOfUpsellToValidateAdditionalGstins); 
        }
        
        /** @Ashwin - Check signed order form is attached when Physical_Sign_completed__c is checked **/
        if(!listOfPhysicalSignUpsForOrderFormValidation.isEmpty()){
            UpsellTriggerHelper.checkForOrderForm(listOfPhysicalSignUpsForOrderFormValidation,true);
        }
        
        /** @Ashwin - Update Upsell Stage to Closed Won when ESign Status is Successfull **/
        if(mapOfUpsellToUpdate.size()>0){
            UpsellTriggerHelper.updateUpsellStage(mapOfUpsellToUpdate);
        }
    }
    
    public void afterUpdate(map<id,sObject> mapofNewsObjectRecords,map<id,sObject> mapofOldsObjectRecords){
        UpsellConstants.isFirstTimeUpsell = False;
        Map<Id, Upsell_Top_up__c> 	newUpsellMap 						= (Map<Id, Upsell_Top_up__c>)mapofNewsObjectRecords;
        Map<Id, Upsell_Top_up__c> 	oldUpsellMap 						= (Map<Id, Upsell_Top_up__c>)mapofOldsObjectRecords;
        Map<Id,Upsell_Top_up__c>	mapOfNewUpsellToUpdate				= new Map<Id,Upsell_Top_up__c>();
        Map<Id,Upsell_Top_up__c>	mapOfNewUpsellToSubmit				= new Map<Id,Upsell_Top_up__c>();
        Map<String,String> 			mapOfUpsellToItsESignCustomerId 	= new Map<String,String>();
        List<Upsell_Top_up__c> 		listOfUpsellsForESignRequest 		= new  List<Upsell_Top_up__c>();
        Map<Id,Upsell_Top_up__c> 	MapOfUpsellsToCloneCvs 				= new  Map<Id,Upsell_Top_up__c>();
        
        for(Id key:newUpsellMap.KeySet()){
            Upsell_Top_up__c UpsellNewInstance=(Upsell_Top_up__c)newUpsellMap.get(key);
            Upsell_Top_up__c UpsellOldInstance=(Upsell_Top_up__c)oldUpsellMap.get(key);
            
            /** @Ashwin - Send for Finance Approval **/
            if(UpsellNewInstance.Stage__c != UpsellOldInstance.Stage__c &&
               UpsellNewInstance.Stage__c == 'Finance Approval'){
                   mapOfNewUpsellToSubmit.put(UpsellNewInstance.Id,UpsellNewInstance); 
                   System.debug('FIN APPROVAL MAP -->'+mapOfNewUpsellToSubmit);
               }
            
            /** @Ashwin - Update Asset with Upsell params and Create upsell opportunity on upsell closure **/
            if(UpsellNewInstance.Stage__c != UpsellOldInstance.Stage__c &&
               UpsellNewInstance.Stage__c == 'Closed' && 
               UpsellNewInstance.Sub_Stage__c == 'Closed Won'){
                   mapOfNewUpsellToUpdate.put(UpsellNewInstance.Id,UpsellNewInstance);
               }
                
            /**	@Ashwin - Revoke Order Form when retriggered for eSign **/
            if(UpsellNewInstance.Stage__c == 'Finance Approval') 
            {			
                if(UpsellNewInstance.Retrigger_E_Sign__c   != UpsellOldInstance.Retrigger_E_Sign__c	&&
                   UpsellNewInstance.Retrigger_E_Sign__c   == 'Resend')
                {
                    System.debug('In Revoke Approval');
                    CTX_SignDeskAPIQueuable myJob 
                        = new CTX_SignDeskAPIQueuable( 
                            UpsellNewInstance.ESign_BE_Document_ID__c, 
                            UpsellNewInstance.ESign_BE_Docket_ID__c
                        );
                    System.enqueueJob(myJob);
                    
                    MapOfUpsellsToCloneCvs.put(UpsellNewInstance.Id, UpsellNewInstance);
                }
                
                
            }
            
            /** E-Sign **/
            if(UpsellNewInstance.ESign_Category__c      == 'E-Sign'	){
                if((UpsellNewInstance.Approval_Status__c 	!= UpsellOldInstance.Approval_Status__c 	&&
                    UpsellNewInstance.Approval_Status__c 	== 'Finance Approval Approved')	
                  )
                {
                    
                    listOfUpsellsForESignRequest.add(UpsellNewInstance);
                    mapOfUpsellToItsESignCustomerId.put(UpsellNewInstance.Id, UpsellNewInstance.E_Sign_Customer_Info__c);
                }
            } 
            /** Physical Sign **/
            else if(
                UpsellNewInstance.ESign_Category__c == 'Physical Sign' && 
                UpsellNewInstance.Approval_Status__c == 'Finance Approval Approved' &&
                UpsellNewInstance.Physical_Sign_completed__c == TRUE && 
                UpsellOldInstance.Physical_Sign_completed__c == FALSE
            ){
                listOfUpsellsForESignRequest.add(UpsellNewInstance);
            }
            
            
            /** @Ashwin - Resend eSign **/
            if( 
                UpsellNewInstance.Retrigger_E_Sign__c 	!= UpsellOldInstance.Retrigger_E_Sign__c	&&
                UpsellNewInstance.Retrigger_E_Sign__c   == 'Resend'
            ) 
            {
                if(UpsellNewInstance.Approval_Status__c 	== 'Finance Approval Approved'){
                    listOfUpsellsForESignRequest.add(UpsellNewInstance);
                    mapOfUpsellToItsESignCustomerId.put(UpsellNewInstance.Id, UpsellNewInstance?.E_Sign_Customer_Info__c);
                }else{
                    UpsellNewInstance.addError('Please try resending after Finance Approval!');
                }
            }
            
        }  
        /** @Ashwin - Clone CV on Resend eSign **/
        if(MapOfUpsellsToCloneCvs.size()>0){
            UpsellTriggerHelper.cloneCvs(MapOfUpsellsToCloneCvs);
        }
        /** @Ashwin - Send for Finance Approval **/
        if(mapOfNewUpsellToSubmit.size()>0){
            UpsellTriggerHelper.submitForApproval(mapOfNewUpsellToSubmit);
        }
        
         /** @Ashwin 
          	 *Update Asset with Upsell params*
			 *Create upsell opportunity*
			 *Update Addn Gstins*
		     *Update Upsell Revenue on upsell closure*
		 **/
        if(mapOfNewUpsellToUpdate.size()>0){
            UpsellTriggerHelper.updateAsset(mapOfNewUpselltoUpdate);
            UpsellTriggerHelper.createOpportunity(mapOfNewUpselltoUpdate);
            UpsellTriggerHelper.updateAdditionalGstinAmount(mapOfNewUpselltoUpdate);
            UpsellTriggerHelper.updateRevenueFromUpsell(mapOfNewUpselltoUpdate);
        }
        
        
        /** @Ashwin - SF <> SignDesk **/
        if(!listOfUpsellsForESignRequest.isEmpty()){
            System.enqueueJob(new CTX_UpsellEsignRequest(listOfUpsellsForESignRequest, mapOfUpsellToItsESignCustomerId));
        }        
        
        
    }
    
    public void beforeDelete(list<sObject> listofOldsObjectRecords,map<id,sObject> mapofOldsObjectRecords){}
    
    public void afterDelete(map<id,sObject> mapofOldsObjectRecords){
        Map<Id, Upsell_Top_up__c> 	oldUpsellMap = (Map<Id, Upsell_Top_up__c>)mapofOldsObjectRecords;
        if(oldUpsellMap.size()>0){
            UpsellTriggerHelper.checkUpsellOnDelete(oldUpsellMap);
        }
        
        UpsellTriggerHelper.updateRevenueFromUpsell(oldUpsellMap);
    }
    
    public void afterUndelete(list<sObject> listofNewsObjectRecords,map<id,sObject> mapofNewsObjectRecords){}
    
}