foundation-objs/main/default/objects/AccountProjectAssetJunction__c/fields/Project_Comment_Formula__c.field-meta.xml
<CustomField>
    <fullName>Project_Comment_Formula__c</fullName>
    <formula>Project__r.Comments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Comment Formula</label>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/AccountProjectAssetJunction__c/fields/Project_PM_Project_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_PM_Project_Owner_Email__c</fullName>
    <formula>Project__r.Pm_Project_Owner_Lookup__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project PM Project Owner Email</label>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/AccountProjectAssetJunction__c/fields/Project_Solution_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Project_Solution_Engineer__c</fullName>
    <formula>Project__r.CTX_SE__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Solution Engineer</label>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/PM_Project_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>PM_Project_Owner_Name__c</fullName>
    <label>PM Project Owner Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Project_Comment_Field__c.field-meta.xml
<CustomField>
    <fullName>Project_Comment_Field__c</fullName>
    <label>Project Comment Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Project_Issue_Description_Field__c.field-meta.xml
<CustomField>
    <fullName>Project_Issue_Description_Field__c</fullName>
    <label>Project Issue Description Field</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Project_Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Issue_Type__c</fullName>
    <label>Project Issue Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Project_PM_Owner_Email_Field__c.field-meta.xml
<CustomField>
    <fullName>Project_PM_Owner_Email_Field__c</fullName>
    <label>Project PM Owner Email Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Project_Scope_Category__c.field-meta.xml
<CustomField>
    <fullName>Project_Scope_Category__c</fullName>
    <label>Project Scope Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Project_Solution_Engineer_Email_Field__c.field-meta.xml
<CustomField>
    <fullName>Project_Solution_Engineer_Email_Field__c</fullName>
    <label>Project Solution Engineer Email Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Project_Stage__c.field-meta.xml
<CustomField>
    <fullName>Project_Stage__c</fullName>
    <label>Project Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Kick-off</fullName>
            </value>
            <value>
                <fullName>Project Plan</fullName>
            </value>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Asset/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Churn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{0000}</displayFormat>
        <label>Project  Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Project__c/fields/Client_ERP__c.field-meta.xml
<CustomField>
    <fullName>Client_ERP__c</fullName>
    <label>Client ERP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Infor LN</fullName>
            </value>
            <value>
                <fullName>JD Edwards</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics 365</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics 365 Business Central</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics 365 Finance and Operations</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics AX</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics CRM</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics GP</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics NAV</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics SL</fullName>
            </value>
            <value>
                <fullName>Microsoft Others</fullName>
            </value>
            <value>
                <fullName>Oracle E-Business Suite</fullName>
            </value>
            <value>
                <fullName>Oracle Fusion</fullName>
            </value>
            <value>
                <fullName>Oracle NetSuite</fullName>
            </value>
            <value>
                <fullName>Oracle Others</fullName>
            </value>
            <value>
                <fullName>Oracle PeopleSoft</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>SAP B1</fullName>
            </value>
            <value>
                <fullName>SAP ECC / S4 Hana</fullName>
            </value>
            <value>
                <fullName>SAP Others</fullName>
            </value>
            <value>
                <fullName>Tally ERP 9</fullName>
            </value>
            <value>
                <fullName>Tally Others</fullName>
            </value>
            <value>
                <fullName>TallyPrime</fullName>
            </value>
            <value>
                <fullName>IDS</fullName>
            </value>
            <value>
                <fullName>Infor Sun Systems</fullName>
            </value>
            <value>
                <fullName>Oracle Opera PMS</fullName>
            </value>
            <value>
                <fullName>QAD Java</fullName>
            </value>
            <value>
                <fullName>In house/Custom ERP</fullName>
                <label>Custom / In-house ERP</label>
            </value>
            <value>
                <fullName>POS systems</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Issue_Description__c.field-meta.xml
<CustomField>
    <fullName>Issue_Description__c</fullName>
    <label>Project Updates</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>Issue_Type__c</fullName>
    <label>Issue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client - Access Expiry</fullName>
            </value>
            <value>
                <fullName>Client - Connectivity</fullName>
            </value>
            <value>
                <fullName>Client - ERP Not Ready</fullName>
            </value>
            <value>
                <fullName>Client - Future Start Date</fullName>
            </value>
            <value>
                <fullName>Client - Kick-off Delay</fullName>
            </value>
            <value>
                <fullName>Client - Payment Pending</fullName>
            </value>
            <value>
                <fullName>Client - Prioritizing Another Project</fullName>
            </value>
            <value>
                <fullName>Client - Requirement Change</fullName>
            </value>
            <value>
                <fullName>Client - Requirements Confirmation</fullName>
            </value>
            <value>
                <fullName>Client - Turnover Less Than Threshold</fullName>
            </value>
            <value>
                <fullName>Client - UAT Delay</fullName>
            </value>
            <value>
                <fullName>Client - Unresponsive</fullName>
            </value>
            <value>
                <fullName>Client - User Provisioning</fullName>
            </value>
            <value>
                <fullName>CT - CSM Issue</fullName>
            </value>
            <value>
                <fullName>CT - Integration Issue</fullName>
            </value>
            <value>
                <fullName>CT - Kick-off Delay</fullName>
            </value>
            <value>
                <fullName>CT - Legal Issue</fullName>
            </value>
            <value>
                <fullName>CT - Onboarding Issue</fullName>
            </value>
            <value>
                <fullName>CT - Product Issue</fullName>
            </value>
            <value>
                <fullName>CT - Sales Issue</fullName>
            </value>
            <value>
                <fullName>CT - SI Delay</fullName>
            </value>
            <value>
                <fullName>CT - SI Payment Issue</fullName>
            </value>
            <value>
                <fullName>CT - SI PO Issue</fullName>
            </value>
            <value>
                <fullName>Client - Cutover Delay</fullName>
                <isActive>false</isActive>
                <label>Client - Cutover Delay</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Pm_Project_Owner_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Pm_Project_Owner_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Owner from the Program Team</description>
    <label>PM Owner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e2x000000UX85</value>
        </filterItems>
        <filterItems>
            <field>User.Username</field>
            <operation>equals</operation>
            <value>shriram.bhat@cleartax.in</value>
        </filterItems>
        <filterItems>
            <field>User.Username</field>
            <operation>equals</operation>
            <value>hanumanthu.jarpala@cleartax.in</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Project_Stage__c.field-meta.xml
<CustomField>
    <fullName>Project_Stage__c</fullName>
    <label>Project Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Kick-off</fullName>
            </value>
            <value>
                <fullName>Project Plan</fullName>
            </value>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Scope_Category__c.field-meta.xml
<CustomField>
    <fullName>Scope_Category__c</fullName>
    <label>Scope Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Consultation</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>AMC</fullName>
            </value>
            <value>
                <fullName>Change Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Churn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-code/main/default/classes/CTX_IntegrationEscalationHelper.cls
public class CTX_IntegrationEscalationHelper {
    
    public static void populateProjectDetailsOnAsset(Map<Id,Asset> newAssetMap,Map<Id,Asset> oldAssetMap){
        
        Map<Id, Id> 								getAssetProjectMap 		= new Map<Id, Id>();
        Map<Id, AccountProjectAssetJunction__c> 	getAssetJunctionMap 	= new Map<Id, AccountProjectAssetJunction__c>();
        Map<String, Id> 							leastStageProjectMap 	= new Map<String, Id>();
        
        for(
            AccountProjectAssetJunction__c thisRec : [ SELECT Id, Customer_Account__c, Project__c, Asset__c, 
                                                      
                                                      Asset__r.Project_Stage__c, Project__r.Project_Stage__c, Project__r.Name, Project__r.Status__c,
                                                      Asset__r.Project_Status__c, Project__r.Scope_Category__c, Asset__r.Project_Scope_Category__c,
                                                      
                                                      Project_Comment_Formula__c, Project_PM_Project_Owner_Email__c, Project_Solution_Engineer__c, 
                                                      
                                                      Project__r.Issue_Description__c, Project__r.Pm_Project_Owner_Lookup__r.Name, Project__r.LastModifiedDate,
                                                      Project__r.Issue_Type__c, Project__r.Project_Name__c, Project__r.Client_ERP__c 
                                                      
                                                      FROM AccountProjectAssetJunction__c WHERE 
                                                      Asset__c IN : newAssetMap.keySet() AND
                                                      Project__r.Status__c != 'Churn'
                                                      ORDER BY Asset__c ]
        ){
            
            if(thisRec.Project__r.Project_Stage__c == 'Awaiting Kick-off'){
                leastStageProjectMap.put(thisRec.Project__r.Project_Stage__c, thisRec.Asset__c);
                getAssetJunctionMap.put(thisRec.Asset__c,thisRec);
                getAssetProjectMap.put(thisRec.Asset__c,thisRec.Project__c);
            }
            
            if(thisRec.Project__r.Project_Stage__c == 'Project Plan'){
                if( leastStageProjectMap.containsKey('Awaiting Kick-off') ){
                    /**	Do Nothing	**/
                } else{
                    leastStageProjectMap.put(thisRec.Project__r.Project_Stage__c, thisRec.Asset__c);
                    getAssetJunctionMap.put(thisRec.Asset__c,thisRec);
                    getAssetProjectMap.put(thisRec.Asset__c,thisRec.Project__c);
                }
            }
            
            if(thisRec.Project__r.Project_Stage__c == 'Implementation'){
                if( leastStageProjectMap.containsKey('Awaiting Kick-off') || 
                   leastStageProjectMap.containsKey('Project Plan')
                  ){
                    /**	Do Nothing	**/
                } else{
                    leastStageProjectMap.put(thisRec.Project__r.Project_Stage__c, thisRec.Asset__c);
                    getAssetJunctionMap.put(thisRec.Asset__c,thisRec);
                    getAssetProjectMap.put(thisRec.Asset__c,thisRec.Project__c);
                }
            }
            
            if(thisRec.Project__r.Project_Stage__c == 'UAT'){
                if( 
                    leastStageProjectMap.containsKey('Awaiting Kick-off') 	|| 
                    leastStageProjectMap.containsKey('Project Plan') 		|| 
                    leastStageProjectMap.containsKey('Implementation')
                ){
                    /**	Do Nothing	**/
                } else{
                    leastStageProjectMap.put(thisRec.Project__r.Project_Stage__c, thisRec.Asset__c);
                    getAssetJunctionMap.put(thisRec.Asset__c,thisRec);
                    getAssetProjectMap.put(thisRec.Asset__c,thisRec.Project__c);
                }
            }
            if(thisRec.Project__r.Project_Stage__c == 'Live'){
                if( 
                    leastStageProjectMap.containsKey('Awaiting Kick-off') 	|| 
                    leastStageProjectMap.containsKey('Project Plan') 		|| 
                    leastStageProjectMap.containsKey('Implementation')		||
                    leastStageProjectMap.containsKey('UAT')
                ){
                    /**	Do Nothing	**/
                } else{
                    leastStageProjectMap.put(thisRec.Project__r.Project_Stage__c, thisRec.Asset__c);
                    getAssetJunctionMap.put(thisRec.Asset__c,thisRec);
                    getAssetProjectMap.put(thisRec.Asset__c,thisRec.Project__c);
                }
            }

        }
        
        System.debug('getAssetProjectMap : '+ getAssetProjectMap);
        Map<Id,Integer> projectWithCurrentStageAging = new Map<Id,Integer>();
        Map<Id,Date> projectWithCurrentStageChangeDate = new Map<Id,Date>();
        Map<Id,Date> projectWithCreateDate = new Map<Id,Date>();
        Date CurrentStageDate;
        Date ProjectCreateDate;
        
        //for stage change date
        for(Project__History thisProjectHistory : [ SELECT Id, ParentId, CreatedDate, Field 
                                                   FROM Project__History 
                                                   WHERE ParentId IN :getAssetProjectMap.values() 
                                                   AND Field IN ('Project_Stage__c') ] 
           ){
               System.debug('thisProjectHistory :'+thisProjectHistory);
               CurrentStageDate = Date.newinstance(thisProjectHistory.CreatedDate.year(), thisProjectHistory.CreatedDate.month(), thisProjectHistory.CreatedDate.day());
               projectWithCurrentStageAging.put(thisProjectHistory.ParentId, CurrentStageDate.daysBetween(Date.today()));
               projectWithCurrentStageChangeDate.put(thisProjectHistory.ParentId, CurrentStageDate);
           }
        
        //for project created date map
        for(Project__c thisProject : [ SELECT Id, CreatedDate FROM Project__c 
                                      WHERE Id IN :getAssetProjectMap.values() ] 
           ){
               System.debug('thisProject :'+thisProject);
               ProjectCreateDate = Date.newinstance(thisProject.CreatedDate.year(), thisProject.CreatedDate.month(), thisProject.CreatedDate.day());
               projectWithCreateDate.put(thisProject.Id,ProjectCreateDate);
           }
        
        System.debug('CurrentStageDate :'+CurrentStageDate);
        System.debug('projectWithCurrentStageAging :'+projectWithCurrentStageAging);
        
        for(Asset thisRec : newAssetMap.values()){
            
            if(getAssetJunctionMap.containsKey(thisRec.Id)){
                
                thisRec.Project_Comment_Field__c 					= getAssetJunctionMap.get(thisRec.Id).Project_Comment_Formula__c;
                thisRec.Project_Issue_Description_Field__c 			= getAssetJunctionMap.get(thisRec.Id).Project__r.Issue_Description__c;
                System.debug('thisRec.Project_Issue_Description_Field__c'+thisRec.Project_Issue_Description_Field__c);
                thisRec.Project_PM_Owner_Email_Field__c 			= getAssetJunctionMap.get(thisRec.Id).Project_PM_Project_Owner_Email__c;
                thisRec.Project_Solution_Engineer_Email_Field__c	= getAssetJunctionMap.get(thisRec.Id).Project_Solution_Engineer__c;
                thisRec.PM_Project_Owner_Name__c					= getAssetJunctionMap.get(thisRec.Id).Project__r.Pm_Project_Owner_Lookup__r.Name;
                thisRec.Project_Stage__c							= getAssetJunctionMap.get(thisRec.Id).Project__r.Project_Stage__c;
                thisRec.Project_Status__c							= getAssetJunctionMap.get(thisRec.Id).Project__r.Status__c;
                thisRec.Project_Scope_Category__c 					= getAssetJunctionMap.get(thisRec.Id).Project__r.Scope_Category__c;
                thisRec.Project_Name__c								= getAssetJunctionMap.get(thisRec.Id).Project__r.Project_Name__c;
                thisRec.Project_Issue_Type__c						= getAssetJunctionMap.get(thisRec.Id).Project__r.Issue_Type__c;
                thisRec.Project_Client_ERP__c						= getAssetJunctionMap.get(thisRec.Id).Project__r.Client_ERP__c;
                thisRec.Project_ID__c								= getAssetJunctionMap.get(thisRec.Id).Project__c;
                
                DateTime myDate = getAssetJunctionMap.get(thisRec.Id).Project__r.LastModifiedDate;
                
                thisRec.Project_Last_Modified_Date_Field__c			= Date.newInstance( 
                        myDate.year(), 
                        myDate.month(), 
                        myDate.day()
                    );
                
                if(projectWithCurrentStageAging.containsKey(getAssetProjectMap.get(thisRec.Id))){
                    thisRec.Aging_in_current_Stage__c 				= projectWithCurrentStageAging.get(getAssetProjectMap.get(thisRec.Id));
                }else{
                    thisRec.Aging_in_current_Stage__c				= thisRec.Escalation_Days_Count__c;
                }
                
                //StageChangeDate
                if(projectWithCurrentStageChangeDate.containsKey(getAssetProjectMap.get(thisRec.Id))){
                    thisRec.Project_Stage_Change_Date__c = projectWithCurrentStageChangeDate.get(getAssetProjectMap.get(thisRec.Id));
                }else{
                    thisRec.Project_Stage_Change_Date__c = projectWithCreateDate.get(getAssetProjectMap.get(thisRec.Id));
                }
                
                
            }
        }
        
        
    }
    
    public static void updateAccountARRTypeDetails(List<Asset> newAssets){
        
        List<Asset> 		updateAssetList 	= new List<Asset>();
        Map<Id, String>		accountIdARRMap		= new Map<id, String>();
        
        for(Asset thisRec : newAssets){
            if(thisRec.AccountId != NULL){
                accountIdARRMap.put(thisRec.AccountId, NULL);
            }
        }
        
        for(
            Asset thisRec : [SELECT Id, AccountId, Account.Sum_of_ARR_Assets__c FROM Asset WHERE AccountId IN :accountIdARRMap.keySet() ]
        ){
            
            system.debug('thisRec.Account.Sum_of_ARR_Assets__c: '+thisRec.Account.Sum_of_ARR_Assets__c);
            String accountARRType;
            
            if(thisRec.Account.Sum_of_ARR_Assets__c  != NULL){
                
                if(thisRec.Account.Sum_of_ARR_Assets__c  >= 2000000.00)
                    accountIdARRMap.put(thisRec.AccountId, 'A1');
                if(thisRec.Account.Sum_of_ARR_Assets__c  >= 400000.00 && thisRec.Account.Sum_of_ARR_Assets__c  < 2000000.00)
                    accountIdARRMap.put(thisRec.AccountId, 'A2');
                if(thisRec.Account.Sum_of_ARR_Assets__c  >= 100000.00 	&& thisRec.Account.Sum_of_ARR_Assets__c  < 400000.00)
                    accountIdARRMap.put(thisRec.AccountId, 'A3');
                if(thisRec.Account.Sum_of_ARR_Assets__c  < 100000.00)
                    accountIdARRMap.put(thisRec.AccountId, 'A4');
            }
        }
        
        for(Asset thisRec : newAssets){
            if(accountIdARRMap.containsKey(thisRec.AccountId)){
                thisRec.Account_ARR_Type__c = accountIdARRMap.get(thisRec.AccountId);
            }
        }
        
        
    }
}