foundation-objs/main/default/objects/Integration_Add_On__c/Integration_Add_On__c.object-meta.xml
<CustomObject>
    <label>Integration Add On</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Add Ons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Integration_Add_On__c/fields/Add_On_Scope__c.field-meta.xml
<CustomField>
    <fullName>Add_On_Scope__c</fullName>
    <label>Add On Scope</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Add_On__c/fields/ERP_Family__c.field-meta.xml
<CustomField>
    <fullName>ERP_Family__c</fullName>
    <label>ERP Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ERP_Family</valueSetName>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Integration_Add_On__c/fields/Estimated_Effort_in_Days__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Effort_in_Days__c</fullName>
    <label>Estimated Effort in Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Add_On__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Add_On__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Add_On__c/fields/Product_SKU__c.field-meta.xml
<CustomField>
    <fullName>Product_SKU__c</fullName>
    <label>Product SKU</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Add_On__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Add_On_Type</valueSetName>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/Integration_Scope_Add_On__c.object-meta.xml
<CustomObject>
    <label>Integration Scope Add On</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Scope Add Ons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/Add_On_Status__c.field-meta.xml
<CustomField>
    <fullName>Add_On_Status__c</fullName>
    <label>Add On Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Applicable any more</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/Discount_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percentage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Discount Percentage</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/Discount_Rate__c.field-meta.xml
<CustomField>
    <fullName>Discount_Rate__c</fullName>
    <formula>( List_Price__c - ( (List_Price__c *  Discount_Percentage__c) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/ERP_Family__c.field-meta.xml
<CustomField>
    <fullName>ERP_Family__c</fullName>
    <label>ERP Family</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/Estimated_Effort_In_Days__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Effort_In_Days__c</fullName>
    <label>Estimated Effort(In Days)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/Product_SKU__c.field-meta.xml
<CustomField>
    <fullName>Product_SKU__c</fullName>
    <label>Product SKU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/Reject_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Reason__c</fullName>
    <label>Reject Reason</label>
    <type>TextArea</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/Related_Add_On__c.field-meta.xml
<CustomField>
    <fullName>Related_Add_On__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Add On</label>
    <referenceTo>Integration_Add_On__c</referenceTo>
    <relationshipLabel>Integration Scope Add Ons</relationshipLabel>
    <relationshipName>Integration_Scope_Add_Ons</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <formula>CASESAFEID(Related_Quote__r.OpportunityId)</formula>
    <label>Related Opportunity</label>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/Related_Quote__c.field-meta.xml
<CustomField>
    <fullName>Related_Quote__c</fullName>
    <label>Related Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Integration Scope Add Ons</relationshipLabel>
    <relationshipName>Related_Quote</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

foundation-objs/main/default/objects/Integration_Scope_Add_On__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/ERP__c.field-meta.xml
<CustomField>
    <fullName>ERP__c</fullName>
    <label>ERP</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ERP</valueSetName>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/ERP_Family__c.field-meta.xml
<CustomField>
    <fullName>ERP_Family__c</fullName>
    <label>ERP Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ERP_Family</valueSetName>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Quote/fields/Add_On_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Add_On_Approval_Status__c</fullName>
    <label>Add On Approval Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Quote/fields/ERP__c.field-meta.xml
<CustomField>
    <fullName>ERP__c</fullName>
    <label>ERP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Infor LN</fullName>
            </value>
            <value>
                <fullName>JD Edwards</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics 365 Finance and Operations</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics 365 Business Central</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics AX</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics NAV</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics CRM</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics GP</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics SL</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics 365</fullName>
            </value>
            <value>
                <fullName>Microsoft Others</fullName>
            </value>
            <value>
                <fullName>Oracle E-Business Suite</fullName>
            </value>
            <value>
                <fullName>Oracle Fusion</fullName>
            </value>
            <value>
                <fullName>Oracle NetSuite</fullName>
            </value>
            <value>
                <fullName>Oracle Others</fullName>
            </value>
            <value>
                <fullName>Oracle PeopleSoft</fullName>
            </value>
            <value>
                <fullName>SAP Business One</fullName>
            </value>
            <value>
                <fullName>SAP ECC / S4 Hana</fullName>
            </value>
            <value>
                <fullName>SAP Others</fullName>
            </value>
            <value>
                <fullName>SAP B1</fullName>
            </value>
            <value>
                <fullName>Tally ERP 9</fullName>
            </value>
            <value>
                <fullName>Tally Others</fullName>
            </value>
            <value>
                <fullName>TallyPrime</fullName>
            </value>
            <value>
                <fullName>Infor Sun Systems</fullName>
            </value>
            <value>
                <fullName>Oracle Opera PMS</fullName>
            </value>
            <value>
                <fullName>QAD Java</fullName>
            </value>
            <value>
                <fullName>In house/Custom ERP</fullName>
                <label>Custom / In-house ERP</label>
            </value>
            <value>
                <fullName>We use POS systems</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/QuoteLineItem/fields/Actual_Sell_Price__c.field-meta.xml
<CustomField>
    <fullName>Actual_Sell_Price__c</fullName>
    <formula>Sale_Price__c  -  Add_On_Discounted_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Sell Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/QuoteLineItem/fields/Actual_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Actual_Unit_Price__c</fullName>
    <formula>UnitPrice  -  Add_On_Prices__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/QuoteLineItem/fields/Add_On_Discounted_Price__c.field-meta.xml
<CustomField>
    <fullName>Add_On_Discounted_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Add On Discounted Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/QuoteLineItem/fields/Add_On_Prices__c.field-meta.xml
<CustomField>
    <fullName>Add_On_Prices__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Add On Prices</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

foundation-objs/main/default/objects/QuoteLineItem/fields/ERP__c.field-meta.xml
<CustomField>
    <fullName>ERP__c</fullName>
    <label>ERP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ERP</valueSetName>
    </valueSet>
</CustomField>

foundation-objs/main/default/globalValueSets/Add_On_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Technical Scope</fullName>
    </customValue>
    <customValue>
        <fullName>Functional Scope</fullName>
    </customValue>
    <customValue>
        <fullName>Dynamic Add On</fullName>
    </customValue>
    <masterLabel>Add On Type</masterLabel>
</GlobalValueSet>

foundation-objs/main/default/globalValueSets/ERP_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SAP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ECC / S4 Hana</fullName>
    </customValue>
    <customValue>
        <fullName>SAP B1</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle</fullName>
    </customValue>
    <customValue>
        <fullName>Microsoft</fullName>
    </customValue>
    <masterLabel>ERP Family</masterLabel>
</GlobalValueSet>

foundation-code/main/default/classes/CTX_AddOnDetailsClass.cls
public class CTX_AddOnDetailsClass {
    
    @AuraEnabled
    public static InitWrapper fetchRequiredDetails(String recordId){
        
        InitWrapper		wrapperResult		= new InitWrapper();
        Set<String> 	productSKUs 		= new Set<String>();
        String 			erpFamily;
        Set<Id>			existingAddOns		= new Set<Id>();
        
        if(recordId != NULL){
            
            wrapperResult.availableScopeAddOns = [ SELECT Id, Related_Quote__c, Related_Opportunity__c, Related_Add_On__c,
                                                  
                                                  Discount_Percentage__c, Discount_Rate__c, ERP_Family__c, 
                                                  Is_Active__c, List_Price__c, Module__c, Name, 
                                                  Product_SKU__c, Estimated_Effort_In_Days__c, Add_On_Status__c, Scope__c, 
                                                  Reject_Reason__c 
                                                  
                                                  FROM Integration_Scope_Add_On__c WHERE Related_Quote__c =:recordId  ];
            
            if(wrapperResult.availableScopeAddOns.size() > 0)
                wrapperResult.isScopeAvailable = TRUE;
            
            for(Integration_Scope_Add_On__c thisRec : wrapperResult.availableScopeAddOns){
                
                existingAddOns.add(thisRec.Related_Add_On__c);
                wrapperResult.totalSellPrice 		= wrapperResult.totalSellPrice + thisRec.List_Price__c;
                wrapperResult.totalDiscountedPrice 	= wrapperResult.totalDiscountedPrice + thisRec.Discount_Rate__c;
            }
            
            for(
                QuoteLineItem thisRec : [ SELECT Id, Product2.OrderForm_Product_Name__c,
                                         
                                         Quote.Opportunity.ERP_Family__c, Quote.ERP__c, 
                                         Quote.Opportunity.Owner.ManagerId
                                         
                                         FROM QuoteLineItem WHERE 
                                         QuoteId =: recordId AND 
                                         Product2.Billing_Type__c = 'OTP' ]
            ){
                erpFamily = thisRec.Quote.ERP__c ;
                productSKUs.add(thisRec.Product2.OrderForm_Product_Name__c);
            }
            
            wrapperResult.integrationAddOnMap = new Map<Id, Integration_Add_On__c>(
                [ SELECT Id, Name, ERP_Family__c, Product_SKU__c, Module__c, 
                 Estimated_Effort_in_Days__c, List_Price__c, Add_On_Scope__c, Type__c  
                 
                 FROM Integration_Add_On__c WHERE 
                 
                 ERP_Family__c =:erpFamily AND 
                 Product_SKU__c IN :productSKUs ] );
            
            for(Id thisId : existingAddOns){
                if(wrapperResult.integrationAddOnMap.containsKey(thisId)){
                    wrapperResult.integrationAddOnMap.remove(thisId);
                }
            }
            
            
            
            
        } else{
            system.debug('Invalid OpportunityId');
            wrapperResult.isSuccess 	= FALSE;
            wrapperResult.errorMessage 	= 'Invalid OpportunityId';
        }
        
        wrapperResult.integrationAddOns = new List<Integration_Add_On__c>(wrapperResult.integrationAddOnMap.values());
        
        
        return wrapperResult;
    }
    
    
    Public Class InitWrapper{
        
        @AuraEnabled
        Public Map<Id, Integration_Add_On__c>		integrationAddOnMap;
        
        @AuraEnabled
        Public List<Integration_Add_On__c> 			integrationAddOns;
        
        
        @AuraEnabled
        Public List<Integration_Scope_Add_On__c>	availableScopeAddOns;
        
        @AuraEnabled
        Public Decimal								totalSellPrice			= 0;
        
        @AuraEnabled
        Public Decimal								totalDiscountedPrice	= 0;
        
        @AuraEnabled
        Public String			 					errorMessage;
        
        @AuraEnabled
        Public Boolean 								isScopeAvailable 		= 	FALSE;
        
        @AuraEnabled
        Public Boolean 								isSuccess 				= 	FALSE;
    }
    
    
    @AuraEnabled
    public static ApprovalWrapper sendForApproval( 
        List<Integration_Scope_Add_On__c> 	incomingValues, 
        String 								recordId 
    ){
        
        ApprovalWrapper	returnWrapper					= new ApprovalWrapper();
        List<sObject> 	quoteAndIntegrationScopeUpsert	= new List<sObject>();
        
        system.debug('recordId recordId recordId recordId recordId: '+recordId);
        system.debug('incomingValues: '+incomingValues);
        
        Quote thiRec = new Quote(
            Id = recordId,
            Add_On_Approval_Status__c = 'In Approval'
        );
        
        quoteAndIntegrationScopeUpsert.add(thiRec);
        quoteAndIntegrationScopeUpsert.addAll(incomingValues);
        
        try{
            upsert quoteAndIntegrationScopeUpsert;
            returnWrapper.isSuccess = TRUE;
        } catch(Exception ex){
            system.debug('Error while Upserting Integration Scope Add Ons: '+ex.getMessage());
            returnWrapper.errorMessage = 'We encountred an error: '+ex.getMessage();
        }
        
        
        Approval.ProcessSubmitRequest approvalRequest = new Approval.ProcessSubmitRequest();
        approvalRequest.setComments('Please check the records and approve.');
        approvalRequest.setObjectId(recordId);
        approvalRequest.setSubmitterId(UserInfo.getUserId());
        approvalRequest.setProcessDefinitionNameOrId('Quote_Integration_Approval');
        approvalRequest.setSkipEntryCriteria(true);
        
        if(returnWrapper.isSuccess){
            try{
                Approval.ProcessResult result = Approval.process(approvalRequest);
            }catch(Exception ex){
                system.debug('Error while Sending Approval Process: '+ex.getMessage());
                returnWrapper.errorMessage = 'We encountred an error: '+ex.getMessage();
            }
        }
        
        system.debug('returnWrapper Approval : '+returnWrapper);
        return returnWrapper;
    }
    
    
    Public Class ApprovalWrapper{
        
        @AuraEnabled
        Public String			 					errorMessage;
        
        @AuraEnabled
        Public Boolean 								isSuccess 				= 	FALSE;
    }
    
    
    public static void quoteApprovalProcessUpdates(
        Map<Id, Quote> approvedMap, 
        Map<Id, Quote> rejectedMap
    ){
        
        Map<String, Set<Integration_Scope_Add_On__c>> 	erpSKUIntegrationScopeMap 	= new Map<String, Set<Integration_Scope_Add_On__c>>();
        Map<Id, sObject>								quoteLineItemAndISAList		= new Map<Id, sObject>();        
        
        if(approvedMap.size() > 0){
            
            for(
                Integration_Scope_Add_On__c thisRec : [ SELECT Id, Related_Opportunity__c, Related_Add_On__c, 
                                                       Related_Quote__c, 
                                                       
                                                       Discount_Percentage__c, Discount_Rate__c, ERP_Family__c, 
                                                       Is_Active__c, List_Price__c, Module__c, Name, 
                                                       Product_SKU__c, Add_On_Status__c, Estimated_Effort_In_Days__c
                                                       
                                                       FROM Integration_Scope_Add_On__c WHERE 
                                                       Related_Quote__c  IN :approvedMap.keySet() ]
            ){
                
                String tempString = thisRec.ERP_Family__c + thisRec.Product_SKU__c;
                if(erpSKUIntegrationScopeMap.containsKey(tempString)){
                    erpSKUIntegrationScopeMap.get(tempString).add(thisRec);
                } else{
                    erpSKUIntegrationScopeMap.put(tempString, new Set<Integration_Scope_Add_On__c>{thisRec});
                }
                
                thisRec.Add_On_Status__c = 'Approved';
                quoteLineItemAndISAList.put(thisRec.Id, thisRec);
            }
            system.debug('quoteLineItemAndISAList Integration_Scope_Add_On__c Approved: '+quoteLineItemAndISAList);
            
            for(
                QuoteLineItem thisRec : [ SELECT Id, UnitPrice, Sale_Price__c, Add_On_Prices__c, Add_On_Discounted_Price__c, 
                                         Actual_Unit_Price__c, Actual_Sell_Price__c, Product2.OrderForm_Product_Name__c, 
                                         Quote.OpportunityId, Quote.Opportunity.ERP_Family__c, 
                                         Quote.Opportunity.Owner.ManagerId, Quote.ERP__c
                                         
                                         FROM QuoteLineItem WHERE QuoteId IN :approvedMap.keySet() ]
            ){
                String tempString = thisRec.Quote.ERP__c + thisRec.Product2.OrderForm_Product_Name__c;
                if(erpSKUIntegrationScopeMap.containsKey(tempString)){
                    
                    for( Integration_Scope_Add_On__c thisOne : erpSKUIntegrationScopeMap.get(tempString) ){
                        if(thisOne.Related_Opportunity__c == thisRec.Quote.OpportunityId){
                            
                            thisRec.Add_On_Prices__c			= thisRec.Add_On_Prices__c + thisOne.List_Price__c;
                            thisRec.Add_On_Discounted_Price__c	= thisRec.Add_On_Discounted_Price__c + thisOne.Discount_Rate__c;
                            
                            thisRec.UnitPrice 					= thisRec.UnitPrice + thisOne.List_Price__c;
                            thisRec.Sale_Price__c 				= thisRec.Sale_Price__c + thisOne.Discount_Rate__c;
                            
                            quoteLineItemAndISAList.put(thisRec.Id, thisRec);
                        } 
                    }
                    system.debug('quoteLineItemAndISAList QuoteLineItem: '+quoteLineItemAndISAList);
                }
            }
        }
        
        
        if(rejectedMap.size() > 0){
            system.debug('I am Bibhu'+rejectedMap);
            Map<Id, String>	quoteIdAndRejectReason = new Map<Id, String>();
            for(
                ProcessInstance thisRec : [ SELECT Id, TargetObjectId, Status, 
                                           ( SELECT Id, StepStatus, Comments 
                                            FROM Steps
                                            ORDER BY CreatedDate DESC
                                            LIMIT 1 )
                                           FROM ProcessInstance WHERE 
                                           TargetObjectId IN :rejectedMap.keySet() 
                                           ORDER BY CreatedDate DESC LIMIT 1 ] 
            ){
                quoteIdAndRejectReason.put(thisRec.TargetObjectId, thisRec.Steps[0].Comments);
            }
            
            List<Integration_Scope_Add_On__c> deleteScope = new List<Integration_Scope_Add_On__c>();
            
            for(
                Integration_Scope_Add_On__c thisRec : [ SELECT Id, Related_Opportunity__c, Related_Add_On__c,
                                                       Related_Quote__c,
                                                       
                                                       Discount_Percentage__c, Discount_Rate__c, ERP_Family__c, 
                                                       Is_Active__c, List_Price__c, Module__c, Name, 
                                                       Product_SKU__c, Add_On_Status__c, Reject_Reason__c, Estimated_Effort_In_Days__c 
                                                       
                                                       FROM Integration_Scope_Add_On__c WHERE 
                                                       Related_Quote__c  IN :rejectedMap.keySet() AND
                                                       Add_On_Status__c = 'In Approval' ]
            ){     
                system.debug('I am Rec: '+thisRec);
                thisRec.Reject_Reason__c = quoteIdAndRejectReason.get(thisRec.Related_Quote__c);
                thisRec.Add_On_Status__c = 'Rejected';
                deleteScope.add(thisRec);
            }
            try{
                update deleteScope;
            } catch(Exception ex){
                system.debug('Error While deleting Scope: '+ex.getMessage());
            }
            
        }
        
        system.debug('quoteLineItemAndISAList Integration_Scope_Add_On__c Rejected: '+quoteLineItemAndISAList);
        if(quoteLineItemAndISAList.size() > 0){
            update quoteLineItemAndISAList.values();
        }
        
    }
    
}