foundation-objs/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{0000}</displayFormat>
        <label>Project  Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Project__c/fields/Estimated_Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Go_Live_Date__c</fullName>
    <description>Date which is provided as Estimated Go Live Date as per the Project Plan.</description>
    <inlineHelpText>Date which is provided as Estimated Go Live Date as per the Project Plan.</inlineHelpText>
    <label>Estimated Go Live Date (Project plan)</label>
    <type>Date</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Estimated_Implementation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Implementation_End_Date__c</fullName>
    <description>Date which is provided as Estimated Implementation End Date as per the Project Plan.</description>
    <inlineHelpText>Date which is provided as Estimated Implementation End Date as per the Project Plan.</inlineHelpText>
    <label>Estimated Implementation End Date</label>
    <type>Date</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Estimated_UAT_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_UAT_End_Date__c</fullName>
    <description>Date which is provided as Estimated UAT End Date as per the Project Plan.</description>
    <inlineHelpText>Date which is provided as Estimated UAT End Date as per the Project Plan.</inlineHelpText>
    <label>Estimated UAT End Date</label>
    <type>Date</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/In_house_project__c.field-meta.xml
<CustomField>
    <fullName>In_house_project__c</fullName>
    <defaultValue>false</defaultValue>
    <description>In case this project is in-house need to mandatorily check this field</description>
    <label>In-house project</label>
    <type>Checkbox</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/LOE_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>LOE_Received_Date__c</fullName>
    <description>The date that is mentioned as the project start date as per the approved LOE.</description>
    <inlineHelpText>The date that is mentioned as the project start date as per the approved LOE.</inlineHelpText>
    <label>Integration Start Date</label>
    <type>Date</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Mode_of_Integration__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Integration__c</fullName>
    <label>Mode of Integration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>JSON API</fullName>
            </value>
            <value>
                <fullName>File upload API</fullName>
            </value>
            <value>
                <fullName>FTP</fullName>
            </value>
            <value>
                <fullName>Manual Upload</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>This field defines for what product has the client chosen integration for</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASP/GSP</fullName>
            </value>
            <value>
                <fullName>EWB</fullName>
            </value>
            <value>
                <fullName>EINV</fullName>
            </value>
            <value>
                <fullName>Max ITC</fullName>
            </value>
            <value>
                <fullName>GSTIN Verification</fullName>
            </value>
            <value>
                <fullName>TDS 206 AB</fullName>
            </value>
            <value>
                <fullName>Invoice Discounting</fullName>
            </value>
            <value>
                <fullName>KSA_EINV_II</fullName>
                <label>KSA EINV II</label>
            </value>
            <value>
                <fullName>KSA EINV I</fullName>
            </value>
            <value>
                <fullName>Clear Capture</fullName>
            </value>
            <value>
                <fullName>DSC</fullName>
            </value>
            <value>
                <fullName>Clear Invoicing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Scope_Category__c.field-meta.xml
<CustomField>
    <fullName>Scope_Category__c</fullName>
    <label>Scope Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Consultation</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>AMC</fullName>
            </value>
            <value>
                <fullName>Change Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Type_of_Integration__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Integration__c</fullName>
    <label>Type of Integration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>API - Only by CT SI</fullName>
            </value>
            <value>
                <fullName>API - Only by CT Inhouse SAP ECC/HANA</fullName>
            </value>
            <value>
                <fullName>API - Only by CT Inhouse SAP B1</fullName>
            </value>
            <value>
                <fullName>API - Only by CT Inhouse Custom ERP</fullName>
            </value>
            <value>
                <fullName>API - Only by CT Inhouse Tally ERP</fullName>
            </value>
            <value>
                <fullName>API - Only by CT Inhouse Netsuite ERP</fullName>
            </value>
            <value>
                <fullName>FTP/SFTP - Only by customer</fullName>
            </value>
            <value>
                <fullName>API- Only by Customer</fullName>
            </value>
            <value>
                <fullName>FTP/ SFTP - Only by CT Inhouse</fullName>
            </value>
            <value>
                <fullName>FTP/ SFTP - Only by SI</fullName>
            </value>
            <value>
                <fullName>ID - API based Integration</fullName>
            </value>
            <value>
                <fullName>ID - Middleware based Integration</fullName>
            </value>
            <value>
                <fullName>ID - SFTP based Integration</fullName>
            </value>
            <value>
                <fullName>ID - Manual Integration</fullName>
            </value>
            <value>
                <fullName>API - Only by CT Inhouse Microsoft ERP</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Invoice Discounting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-code/main/default/classes/CTX_ProjectAutomationHelper.cls
public class CTX_ProjectAutomationHelper {
    
    public static Project__c getScopeModeInHouseDetails( Project__c thisRec ){
        
        switch on thisRec.Type_of_Integration__c {
            when 'API - Only by CT SI'{ 
                thisRec.Scope_Category__c = 'Development';
                thisRec.Mode_of_Integration__c = 'JSON API';
                thisRec.In_house_project__c = FALSE;
            }
            when 'API - Only by CT Inhouse SAP ECC/HANA'{ 
                thisRec.Scope_Category__c = 'Development';
                thisRec.Mode_of_Integration__c = 'JSON API'; 
                thisRec.In_house_project__c = FALSE;
            }
            when 'API - Only by CT Inhouse SAP B1'{ 
                thisRec.Scope_Category__c = 'Development';
                thisRec.Mode_of_Integration__c = 'JSON API';
                thisRec.In_house_project__c = FALSE;
            }
            when 'API - Only by CT Inhouse Custom ERP'{ 
                thisRec.Scope_Category__c = 'Development';
                thisRec.Mode_of_Integration__c = 'JSON API';
                thisRec.In_house_project__c = FALSE;
            }
            when 'API - Only by CT Inhouse Tally ERP'{ 
                thisRec.Scope_Category__c = 'Development';
                thisRec.Mode_of_Integration__c = 'JSON API';
                thisRec.In_house_project__c = TRUE;
            }
            when 'API - Only by CT Inhouse Netsuite ERP'{ 
                thisRec.Scope_Category__c = 'Development';
                thisRec.Mode_of_Integration__c = 'JSON API';
                thisRec.In_house_project__c = FALSE;
            }
            when 'FTP/SFTP - Only by customer'{ 
                thisRec.Scope_Category__c = 'Consultation';
                thisRec.Mode_of_Integration__c = 'FTP';
                thisRec.In_house_project__c = TRUE;
            }
            when 'API- Only by Customer'{ 
                thisRec.Scope_Category__c = 'Consultation';
                thisRec.Mode_of_Integration__c = 'JSON API';
                thisRec.In_house_project__c = TRUE;
            }
            when 'FTP/ SFTP - Only by CT Inhouse'{ 
                thisRec.Scope_Category__c = 'Development';
                thisRec.Mode_of_Integration__c = 'FTP';
                thisRec.In_house_project__c = TRUE;
            }
            when 'FTP/ SFTP - Only by SI'{ 
                thisRec.Scope_Category__c = 'Development';
                thisRec.Mode_of_Integration__c = 'FTP';
                thisRec.In_house_project__c = FALSE;
            }
            when 'ID - API based Integration'{ 
                thisRec.Scope_Category__c = 'Development';
                thisRec.Mode_of_Integration__c = 'JSON API';
                thisRec.In_house_project__c = TRUE;
            }
            when 'ID - Middleware based Integration'{ 
                thisRec.Scope_Category__c = 'Development';
                thisRec.Mode_of_Integration__c = 'JSON API';
                thisRec.In_house_project__c = TRUE;
            }
            when 'ID - SFTP based Integration'{ 
                thisRec.Scope_Category__c = 'Development';
                thisRec.Mode_of_Integration__c = 'FTP';
                thisRec.In_house_project__c = TRUE;
            }
            when 'ID - Manual Integration'{ 
                thisRec.Scope_Category__c = 'Development';
                thisRec.Mode_of_Integration__c = 'Manual Upload';
                thisRec.In_house_project__c = TRUE;
            }
            when 'API - Only by CT Inhouse Microsoft ERP'{ 
                thisRec.Scope_Category__c = 'Development';
                thisRec.Mode_of_Integration__c = 'JSON API';
                thisRec.In_house_project__c = TRUE;
            }
            when 'Others'{ 
                thisRec.Scope_Category__c = 'Development';
                thisRec.Mode_of_Integration__c = 'JSON API';
                thisRec.In_house_project__c = TRUE;
            }
            when 'Invoice Discounting'{ 
                thisRec.Scope_Category__c = 'Development';
                thisRec.Mode_of_Integration__c = 'JSON API';
                thisRec.In_house_project__c = TRUE;
            }
        }
        
        return thisRec;
    }
    
    public static Project__c getEstimatedDateForProject( Project__c thisRec, Date assetPurchaseDate ){
        
        DateTime projectStartDate 		= assetPurchaseDate;
        Integer implementation_End_Days = 0;
        Integer uat_End_Days 			= 0;
        Integer goLive_Days 			= 0;
        
        if( projectStartDate < thisRec.CreatedDate ){
            projectStartDate = thisRec.CreatedDate;
        }
        if( projectStartDate < thisRec.LOE_Received_Date__c ){
            projectStartDate = thisRec.LOE_Received_Date__c;
        }
        
        
        if( thisRec.Scope_Category__c == 'Consultation' ){
            implementation_End_Days = 39;
            uat_End_Days = 14;
            goLive_Days = 7;
        }
        if( thisRec.Scope_Category__c == 'Development' ){
            
            if( thisRec.Product__c == 'EINV' ){
                implementation_End_Days = 24;
                uat_End_Days = 14;
                goLive_Days = 7;
            }
            if( thisRec.Product__c == 'EWB' ){
                implementation_End_Days = 24;
                uat_End_Days = 14;
                goLive_Days = 7;
            }
            if( thisRec.Product__c == 'ASP/GSP' ){
                implementation_End_Days = 39;
                uat_End_Days = 14;
                goLive_Days = 7;
            }
            if( thisRec.Product__c == 'Invoice Discounting' ){
                implementation_End_Days = 39;
                uat_End_Days = 14;
                goLive_Days = 7;
            }
            if( thisRec.Product__c == 'Max ITC' ){
                implementation_End_Days = 59;
                uat_End_Days = 21;
                goLive_Days = 10;
            }
            if( thisRec.Product__c == 'Clear Capture' ){
                implementation_End_Days = 59;
                uat_End_Days = 21;
                goLive_Days = 10;
            }
            if( thisRec.Product__c == 'AP' ){
                implementation_End_Days = 59;
                uat_End_Days = 21;
                goLive_Days = 10;
            }
            if( thisRec.Product__c == 'KSA EINV I' ){
                implementation_End_Days = 59;
                uat_End_Days = 21;
                goLive_Days = 10;
            }
            if( thisRec.Product__c == 'KSA EINV II' ){
                implementation_End_Days = 59;
                uat_End_Days = 21;
                goLive_Days = 10;
            }
        }

        thisRec.LOE_Received_Date__c 					= Date.newinstance(projectStartDate.year(), projectStartDate.month(), projectStartDate.day());
        thisRec.Estimated_Implementation_End_Date__c	= thisRec.LOE_Received_Date__c.addDays(implementation_End_Days);
        thisRec.Estimated_UAT_End_Date__c 				= thisRec.Estimated_Implementation_End_Date__c.addDays(uat_End_Days);
        thisRec.Estimated_Go_Live_Date__c 				= thisRec.Estimated_UAT_End_Date__c.addDays(goLive_Days);
        
        return thisRec;
    }
    
    
}