foundation-objs/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{0000}</displayFormat>
        <label>Project  Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Project__c/fields/CTX_SE__c.field-meta.xml
<CustomField>
    <fullName>CTX_SE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Issue_Description__c.field-meta.xml
<CustomField>
    <fullName>Issue_Description__c</fullName>
    <label>Project Updates</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>Issue_Type__c</fullName>
    <label>Issue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client - Access Expiry</fullName>
            </value>
            <value>
                <fullName>Client - Connectivity</fullName>
            </value>
            <value>
                <fullName>Client - ERP Not Ready</fullName>
            </value>
            <value>
                <fullName>Client - Future Start Date</fullName>
            </value>
            <value>
                <fullName>Client - Kick-off Delay</fullName>
            </value>
            <value>
                <fullName>Client - Payment Pending</fullName>
            </value>
            <value>
                <fullName>Client - Prioritizing Another Project</fullName>
            </value>
            <value>
                <fullName>Client - Requirement Change</fullName>
            </value>
            <value>
                <fullName>Client - Requirements Confirmation</fullName>
            </value>
            <value>
                <fullName>Client - Turnover Less Than Threshold</fullName>
            </value>
            <value>
                <fullName>Client - UAT Delay</fullName>
            </value>
            <value>
                <fullName>Client - Unresponsive</fullName>
            </value>
            <value>
                <fullName>Client - User Provisioning</fullName>
            </value>
            <value>
                <fullName>CT - CSM Issue</fullName>
            </value>
            <value>
                <fullName>CT - Integration Issue</fullName>
            </value>
            <value>
                <fullName>CT - Kick-off Delay</fullName>
            </value>
            <value>
                <fullName>CT - Legal Issue</fullName>
            </value>
            <value>
                <fullName>CT - Onboarding Issue</fullName>
            </value>
            <value>
                <fullName>CT - Product Issue</fullName>
            </value>
            <value>
                <fullName>CT - Sales Issue</fullName>
            </value>
            <value>
                <fullName>CT - SI Delay</fullName>
            </value>
            <value>
                <fullName>CT - SI Payment Issue</fullName>
            </value>
            <value>
                <fullName>CT - SI PO Issue</fullName>
            </value>
            <value>
                <fullName>Client - Cutover Delay</fullName>
                <isActive>false</isActive>
                <label>Client - Cutover Delay</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Pm_Project_Owner_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Pm_Project_Owner_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Owner from the Program Team</description>
    <label>PM Owner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e2x000000UX85</value>
        </filterItems>
        <filterItems>
            <field>User.Username</field>
            <operation>equals</operation>
            <value>shriram.bhat@cleartax.in</value>
        </filterItems>
        <filterItems>
            <field>User.Username</field>
            <operation>equals</operation>
            <value>hanumanthu.jarpala@cleartax.in</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Project_Stage__c.field-meta.xml
<CustomField>
    <fullName>Project_Stage__c</fullName>
    <label>Project Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Kick-off</fullName>
            </value>
            <value>
                <fullName>Project Plan</fullName>
            </value>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/SE_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>SE_Owner_Email__c</fullName>
    <formula>CTX_SE__r.Email</formula>
    <label>SE Owner Email</label>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Churn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-code/main/default/classes/CTX_ProjectInactivityEmailHelper.cls
public class CTX_ProjectInactivityEmailHelper {
    
    Public static void sendInactivityEmail(){
        
        Date 				dateToday 					= Date.today();
        Date 				sevenWorkingDaysBeforeToday = BusinessDays.AddBusinessDays(dateToday, -7);
        List<Project__c> 	parentProjectsList 			= new List<Project__c>();
        Id 					defaultMailId 				= [ SELECT Id FROM OrgWideEmailAddress WHERE 
                                                           Address = 'notifications.sf@cleartaxmailer.com']?.Id;
        List<String> 		errorMessages 				= new List<String>();
        
        parentProjectsList 								= [ SELECT id, Name, Issue_Type__c, Issue_Description__c, CreatedDate, 
                                                           Project_Stage__c, Status__c, Pm_Project_Owner_Lookup__r.Email, 
                                                           Pm_Project_Owner_Lookup__c ,CTX_SE__c ,SE_Owner_Email__c 
                                                           FROM Project__c WHERE Status__c NOT IN ('Churn') 
                                                           AND Project_Stage__c NOT IN ('Live') 
                                                           AND CreatedDate <=: sevenWorkingDaysBeforeToday ];
        
        Map<Id, Project__c> mapOfParentProjects			= new Map<Id, Project__c>();
        mapOfParentProjects.putAll(parentProjectsList);
        
        List<Project__History> historyProjectsList		= new List<Project__History>();
        historyProjectsList								= [ SELECT Id, ParentId, CreatedDate, Field 
                                                           FROM Project__History 
                                                           WHERE ParentId IN:mapOfParentProjects.keySet() 
                                                           AND Field IN ('Issue_Type__c', 'Issue_Description__c') 
                                                           AND CreatedDate >=: sevenWorkingDaysBeforeToday ];
        
        List<Messaging.SingleEmailMessage> 	mailList 	= new List<Messaging.SingleEmailMessage>();
        
        if(historyProjectsList != NULL)
            for(Project__History historyProjectInstance : historyProjectsList){
                mapOfParentProjects.remove(historyProjectInstance.ParentId);
            }
        
        for(Id thisProjectsId : mapOfParentProjects.keySet()){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.SaveAsActivity = TRUE;
            mail.setWhatId(thisProjectsId);
            List<String> ccAddresses = new List<String>();
			List<String> toAddresses = new List<String>();
            
            if(mapOfParentProjects.get(thisProjectsId).Pm_Project_Owner_Lookup__c != NULL)
                toAddresses.add(mapOfParentProjects.get(thisProjectsId).Pm_Project_Owner_Lookup__r.Email);
                toAddresses.add('bhavesh.jindal@cleartax.in');
            if(mapOfParentProjects.get(thisProjectsId).CTX_SE__c != NULL)
                ccAddresses.add(mapOfParentProjects.get(thisProjectsId).SE_Owner_Email__c);
            
            String body = 'Your Attention Please!  '+','+'<br/>';
            body += 'Issue Type and Issue Description for below Project has not been updated since last 7 working Days. Please take necessary action.'+'<br/>';
            body += '<b>Project name :</b>'+' '+mapOfParentProjects.get(thisProjectsId).Name+'		'+'<b>Created Date :</b>'+mapOfParentProjects.get(thisProjectsId).CreatedDate+'<br/>';
            body += ''+'<br/>';
            body += '<b>Issue Type :</b>'+mapOfParentProjects.get(thisProjectsId).Issue_Type__c+'<br/>';
            body += '<b>Issue Description :</b>'+' '+mapOfParentProjects.get(thisProjectsId).Issue_Description__c+'<br/>';
            body += ''+'<br/>';
            body +='Regards'+',<br/>'+'\n Project Inactivity Monitoring'+'<br/>';
            
            mail.setSubject('Inactivity in Project.');
            mail.setHtmlBody(body);
            mail.setToAddresses(toAddresses);
            mail.setCcAddresses(ccAddresses);
            mail.setOrgWideEmailAddressId(defaultMailId);
            mailList.add(mail);
        }
        system.debug('mailList: '+mailList.size());
        if(!mailList.isEmpty()) {
            try{
                Messaging.sendEmail(mailList);
            }
            catch (Exception ex) {
                errorMessages.add('Unable to send email'+ ex.getMessage());
            }
        }
        
        //debugs
        System.debug( ' Size of Map : ' + mapOfParentProjects.keySet().size());
        System.debug('Size : ' + parentProjectsList.size() + ' parentProjectsList '+ parentProjectsList);
        System.debug('Size : ' + historyProjectsList.size() + ' historyProjectsList '+ historyProjectsList);
        System.debug('today date'+ dateToday);
        System.debug('subtracted date'+sevenWorkingDaysBeforeToday);
        
    }
    
}