foundation-objs/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{0000}</displayFormat>
        <label>Project  Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Project__c/fields/Client_ERP__c.field-meta.xml
<CustomField>
    <fullName>Client_ERP__c</fullName>
    <label>Client ERP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Infor LN</fullName>
            </value>
            <value>
                <fullName>JD Edwards</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics 365</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics 365 Business Central</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics 365 Finance and Operations</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics AX</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics CRM</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics GP</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics NAV</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics SL</fullName>
            </value>
            <value>
                <fullName>Microsoft Others</fullName>
            </value>
            <value>
                <fullName>Oracle E-Business Suite</fullName>
            </value>
            <value>
                <fullName>Oracle Fusion</fullName>
            </value>
            <value>
                <fullName>Oracle NetSuite</fullName>
            </value>
            <value>
                <fullName>Oracle Others</fullName>
            </value>
            <value>
                <fullName>Oracle PeopleSoft</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>SAP B1</fullName>
            </value>
            <value>
                <fullName>SAP ECC / S4 Hana</fullName>
            </value>
            <value>
                <fullName>SAP Others</fullName>
            </value>
            <value>
                <fullName>Tally ERP 9</fullName>
            </value>
            <value>
                <fullName>Tally Others</fullName>
            </value>
            <value>
                <fullName>TallyPrime</fullName>
            </value>
            <value>
                <fullName>IDS</fullName>
            </value>
            <value>
                <fullName>Infor Sun Systems</fullName>
            </value>
            <value>
                <fullName>Oracle Opera PMS</fullName>
            </value>
            <value>
                <fullName>QAD Java</fullName>
            </value>
            <value>
                <fullName>In house/Custom ERP</fullName>
                <label>Custom / In-house ERP</label>
            </value>
            <value>
                <fullName>POS systems</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Delivery_Owner__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Delivery_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/In_house_project__c.field-meta.xml
<CustomField>
    <fullName>In_house_project__c</fullName>
    <defaultValue>false</defaultValue>
    <description>In case this project is in-house need to mandatorily check this field</description>
    <label>In-house project</label>
    <type>Checkbox</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Pm_Project_Owner_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Pm_Project_Owner_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Owner from the Program Team</description>
    <label>PM Owner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e2x000000UX85</value>
        </filterItems>
        <filterItems>
            <field>User.Username</field>
            <operation>equals</operation>
            <value>shriram.bhat@cleartax.in</value>
        </filterItems>
        <filterItems>
            <field>User.Username</field>
            <operation>equals</operation>
            <value>hanumanthu.jarpala@cleartax.in</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>This field defines for what product has the client chosen integration for</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ASP/GSP</fullName>
            </value>
            <value>
                <fullName>EWB</fullName>
            </value>
            <value>
                <fullName>EINV</fullName>
            </value>
            <value>
                <fullName>Max ITC</fullName>
            </value>
            <value>
                <fullName>GSTIN Verification</fullName>
            </value>
            <value>
                <fullName>TDS 206 AB</fullName>
            </value>
            <value>
                <fullName>Invoice Discounting</fullName>
            </value>
            <value>
                <fullName>KSA_EINV_II</fullName>
                <label>KSA EINV II</label>
            </value>
            <value>
                <fullName>KSA EINV I</fullName>
            </value>
            <value>
                <fullName>Clear Capture</fullName>
            </value>
            <value>
                <fullName>DSC</fullName>
            </value>
            <value>
                <fullName>Clear Invoicing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Project_Owner_automation__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner_automation__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Project - Owner automation</label>
    <type>Checkbox</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Scope_Category__c.field-meta.xml
<CustomField>
    <fullName>Scope_Category__c</fullName>
    <label>Scope Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Consultation</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>AMC</fullName>
            </value>
            <value>
                <fullName>Change Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/SI_Account_Lookup__c.field-meta.xml
<CustomField>
    <fullName>SI_Account_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SI Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Churn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-code/main/default/classes/CTX_ProjectOwnerMapping.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-08-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class CTX_ProjectOwnerMapping {
    
    /**	Priyanka Chettri - BIBHU	**/
    /**	Rajeev Rajanala - Vaishnav	**/
    /**	Harish Pancholi - Kartikeya	**/ 
    
    public static void projectOwnerMapping(List<Project__c> projects){
        Set<Id> SIAccounts = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();
      
        for(Project__c thisProject : projects){
            if(thisProject.SI_Account_Lookup__c != NULL)
                SIAccounts.add(thisProject.SI_Account_Lookup__c);
            	accountIds.add(thisProject.Account__c);
        }
        
        
        Map<Id, Account> accountMap = new Map<Id, Account>([SELECT Id, Name, Onboarding_Owner__c
                                                            FROM Account 
                                                            WHERE Id IN :SIAccounts OR Id IN :accountIds]);
     
        
        for(Project__c thisRec : projects){
            if(thisRec.Project_Owner_automation__c 		== TRUE && 
               thisRec.Status__c 						!= 'Complete'&&
               thisRec.Status__c 						!= 'Churn')
            {
                
                /**	Installation	**/
                if(thisRec.Scope_Category__c == 'Installation' &&
                   thisRec.In_house_project__c == TRUE			){
                       
                       thisRec.OwnerId 						= System.Label.PM_Owner_Shriram_Bhat;
                       thisRec.Pm_Project_Owner_Lookup__c 	= System.Label.PM_Owner_Shriram_Bhat;
                       thisRec.Delivery_Owner__c			= System.Label.PM_Owner_Shriram_Bhat;
                       
                   } 
                
                /**	Consultation	**/
                if(
                    thisRec.Scope_Category__c == 'Consultation' && 
                    thisRec.In_house_project__c == TRUE)			
                {
                    thisRec.OwnerId 						= System.Label.PM_Owner_Shriram_Bhat;
                    thisRec.Pm_Project_Owner_Lookup__c 		= System.Label.PM_Owner_Shriram_Bhat;
                    thisRec.Delivery_Owner__c 				= System.Label.PM_Owner_Shriram_Bhat;
                }
                
                
                
                if( thisRec.Scope_Category__c == 'Development' &&
                   thisRec.In_house_project__c == TRUE ){
                       thisRec.OwnerId 						= System.Label.PM_Owner_Daksh_Sikka;
                       thisRec.Pm_Project_Owner_Lookup__c 	= System.Label.PM_Owner_Daksh_Sikka;
                   }
                
                
                if( thisRec.Scope_Category__c == 'Development' &&
                   thisRec.In_house_project__c == FALSE && 
                   accountMap.containsKey(thisRec.SI_Account_Lookup__c) &&
                   accountMap.get(thisRec.SI_Account_Lookup__c).Name != NULL){
                       if(accountMap.get(thisRec.SI_Account_Lookup__c).Name.containsIgnoreCase('Slite') ||
                          accountMap.get(thisRec.SI_Account_Lookup__c).Name.containsIgnoreCase('diligence') ||
                          accountMap.get(thisRec.SI_Account_Lookup__c).Name.containsIgnoreCase('Piranha') ||
                          accountMap.get(thisRec.SI_Account_Lookup__c).Name.containsIgnoreCase('Trenchant '))
                       {
                           thisRec.OwnerId 						= System.Label.PM_Owner_Rajesh_Chandran;
                           thisRec.Pm_Project_Owner_Lookup__c 	= System.Label.PM_Owner_Rajesh_Chandran;
                           
                       }else if(accountMap.get(thisRec.SI_Account_Lookup__c).Name.containsIgnoreCase('Denpro') ||
                                accountMap.get(thisRec.SI_Account_Lookup__c).Name.containsIgnoreCase('Iteanz') ||
                                accountMap.get(thisRec.SI_Account_Lookup__c).Name.containsIgnoreCase('Osswal'))
                       {
                           thisRec.OwnerId 						= System.Label.PM_Owner_Yash_Kothari;
                           thisRec.Pm_Project_Owner_Lookup__c 	= System.Label.PM_Owner_Yash_Kothari;
                           
                           
                       }else  if(accountMap.get(thisRec.SI_Account_Lookup__c).Name.containsIgnoreCase('Sterck') ||
                                 accountMap.get(thisRec.SI_Account_Lookup__c).Name.containsIgnoreCase('Cloudare') ||
                                 accountMap.get(thisRec.SI_Account_Lookup__c).Name.containsIgnoreCase('Prateek'))
                       {
                           thisRec.OwnerId 						= System.Label.PM_Owner_Harish_Pancholi;
                           thisRec.Pm_Project_Owner_Lookup__c 	= System.Label.PM_Owner_Harish_Pancholi;
                           
                       }else {
                           thisRec.OwnerId 						= System.Label.PM_Owner_Harish_Pancholi;
                           thisRec.Pm_Project_Owner_Lookup__c 	= System.Label.PM_Owner_Harish_Pancholi;
                       }
                   }
                
                
                
                if( 
                    thisRec.Scope_Category__c == 'Development' )
                {
                    if(thisRec.Client_ERP__c?.containsIgnoreCase('Microsoft')) {
                        thisRec.OwnerId 					= System.Label.PM_Owner_Rakesh_Ranjan;
                        thisRec.Pm_Project_Owner_Lookup__c 	= System.Label.PM_Owner_Rakesh_Ranjan;
                        thisRec.Delivery_Owner__c 			= System.Label.PM_Owner_Rakesh_Ranjan;
                    }else if( thisRec.Client_ERP__c?.containsIgnoreCase('Custom'))
                    {
                        thisRec.Delivery_Owner__c 			= System.Label.PM_Owner_Shriram_Bhat;
                    } else if(
                        thisRec.Product__c == 'Clear Capture' 			|| 
                        thisRec.Product__c == 'Invoice Discounting'  	||
                        thisRec.Product__c == 'GSTIN Verification'	 	||
                        thisRec.Product__c == 'AP'	 					||
                        thisRec.Product__c == 'ASP/GSP'	
                    ){
                        
                        thisRec.Delivery_Owner__c 			= System.Label.PM_Owner_Rajeev_Rajanala;
                    }else if(thisRec.Product__c == 'EINV'										||
                             thisRec.Product__c == 'EWB'	)
                    {
                        thisRec.Delivery_Owner__c 			= System.Label.PM_Owner_Hanumanthu_Jarpala;                                 
                    }else if(thisRec.Product__c == 'MAX ITC'){
                        thisRec.Delivery_Owner__c 			= System.Label.PM_Owner_Sakthidoss_Gajendran;                                 
                    }
                }
                
                if( 
                    thisRec.Scope_Category__c == 'Development' )
                {
                    if(thisRec.Product__c == 'EINV'	||
                       thisRec.Product__c == 'EWB')
                    {
                        thisRec.Pm_Project_Owner_Lookup__c = system.label.PM_Owner_Shriram_Bhat;
                    } else if(thisRec.Product__c == 'Clear Identity')
                    {
                        thisRec.Pm_Project_Owner_Lookup__c = System.Label.PM_Owner_Rakesh_Ranjan;	
                    } else if(thisRec.Product__c == 'DSC')
                    {
                        thisRec.Pm_Project_Owner_Lookup__c = System.Label.PM_Owner_Hanumanthu_Jarpala	;
                    }
                }
                
                /**	KSA	**/
                if(thisRec.Product__c == 'KSA EINV I' || 
                   thisRec.Product__c == 'KSA EINV II')
                {
                    thisRec.OwnerId 					= System.Label.PM_Owner_Usha  ;
                    thisRec.Pm_Project_Owner_Lookup__c 	= System.Label.PM_Owner_Usha ; 
                    thisRec.Delivery_Owner__c 			= System.Label.PM_Owner_Usha;
                    
                }
                
                
            }
        }
    }                   
}