foundation-objs/main/default/objects/Opportunity/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <label>Billing Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/City_2__c.field-meta.xml
<CustomField>
    <fullName>City_2__c</fullName>
    <label>Billing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/If_SEZ__c.field-meta.xml
<CustomField>
    <fullName>If_SEZ__c</fullName>
    <label>If SEZ (Yes/No)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Legal_Entity_Name_Of_The_Client__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name_Of_The_Client__c</fullName>
    <label>Legal Entity Name Of The Client</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/PAN_No_as_per_PO__c.field-meta.xml
<CustomField>
    <fullName>PAN_No_as_per_PO__c</fullName>
    <label>Billing PAN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <label>Billing Pincode</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Place_of_Supply__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Supply__c</fullName>
    <label>Place of Supply</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <label>Shipping Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/State_2__c.field-meta.xml
<CustomField>
    <fullName>State_2__c</fullName>
    <label>Billing State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-code/main/default/classes/CTX_GSTCompanyInfo.cls
/** GSTIN verification API <> SF **/

public class CTX_GSTCompanyInfo {
    
 
     @AuraEnabled
    public static String fetchCompanyInfo(String gstin, Id opportunityId)  {
        
        HttpRequest 	  	request     						= 	new HttpRequest();
        
         List<Logger__c>   logFaliures      		= new List<Logger__c>();
        request.setEndpoint(System.Label.GST_Portal_Endpoint + gstin);
        request.setMethod('GET');
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('x-cleartax-auth-token', System.Label.GST_ApiToken);
        
        Http 				http 								= 	new Http();
        
        HTTPResponse 		response 							= 	http.send(request);
        
        String toastMessage;
       
        
        if (response.getStatusCode() == 200) { 
            
            System.debug('@response: '+ response.getBody());
            
            Map<String, Object> responseMap 					= 	(Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            
            Map<String, Object> taxPayerInfo 					= 	(Map<String, Object>) responseMap.get('taxPayerInfo');
            
            Map<String, Object> principalAddress = new  Map<String, Object>();
            
            Map<String, Object> billingAddress = new Map<String, Object>();
            
            if(taxPayerInfo != NULL){
                
                
                
                
                if(taxPayerInfo.get('principalAddress') != NULL ){
                    principalAddress  = (Map<String, Object>) taxPayerInfo.get('principalAddress');
                }
                
                
                if(principalAddress != NULL) {
                    billingAddress 	= 	(Map<String, Object>) principalAddress.get('address');
                }    
                
                Opportunity companyInfo = new Opportunity(Id 	= 	opportunityId);
                
                companyInfo.Legal_Entity_Name_Of_The_Client__c  = 	(String) taxPayerInfo?.get('legalBusinessName');
                
                if(((String) taxPayerInfo.get('taxpayerType')).containsIgnoreCase('SEZ')){
                    
                    companyInfo.If_SEZ__c  						= 	'Yes';
                    
                }else{
                    
                    companyInfo.If_SEZ__c  						= 	'No';
                    
                }
                
                companyInfo.PAN_No_as_per_PO__c 				= 	(String) taxPayerInfo?.get('pan');
                
                String billingCity = '';
                     
                if(billingAddress != NULL){
                    billingCity = ((String) billingAddress?.get('city') != 'null' && (String) billingAddress?.get('city') != NULL &&(String) billingAddress?.get('city') != '') ? (String) billingAddress.get('city') :(String) billingAddress?.get('district');

                    companyInfo.Billing_Address__c  					= 	(String) billingAddress?.get('doorNumber') 	+ ' ' + 
                        (String) billingAddress?.get('buildingName') + ' ' + 
                        (String) billingAddress?.get('floorNumber')  + ' ' +
                        (String) billingAddress?.get('street') 		+ ' ' +
                        (String) billingAddress?.get('locality') 	+ ' ' +
                         		 billingCity						+ ' ' +
                        (String) billingAddress?.get('district') 	+ ' ' +
                        (String) billingAddress?.get('stateName') 	+ ' ' +
                        (String) billingAddress?.get('pinCode');
                }
                
                companyInfo.Shipping_Address__c 				= 	companyInfo?.Billing_Address__c;
                
                companyInfo.Pincode__c 							= 	(String) billingAddress?.get('pinCode');
                
                companyInfo.City_2__c   						= 	billingCity;
                
                companyInfo.State_2__c 							= 	(String) billingAddress?.get('stateName');
                
                companyInfo.Place_of_Supply__c					= 	(String) billingAddress?.get('stateName');
                
                OpportunityConstants.ENABLE_GSTIN_VERIFICATION_RULE = FALSE;
                
                Database.SaveResult sr = Database.Update(companyInfo, false);
                
                if (sr.isSuccess()) {
                    toastMessage = 'Updated Successfully!';
                } else {
                    for (Database.Error err : sr.getErrors()) {
                        toastMessage = 'Error : ' + err.getMessage();
                    }
                }
                
                
                
                
                
               
            }else{

                Map<String, Object> taxPayerErrorResponse = (Map<String, Object>) responseMap.get('taxPayerErrorResponse');
                String ErrorMessage = (String) taxPayerErrorResponse.get('message');
                toastMessage = 'ERROR -'+ErrorMessage; 
                
                logFaliures.add(CTX_LoggerImplementation.createLoggerInstance(
                    response.getBody(),
                    NULL,
                    'CTX_GstCompanyInfo',
                    'CTX_GstCompanyInfo.fetchCompanyInfo()',
                    'TaxPayerInfo Not Found',
                    opportunityId,
                    'Opportunity' 
                ));
                
            }
            
        }else{
            
            logFaliures.add(CTX_LoggerImplementation.createLoggerInstance(
                response.getBody(),
                NULL,
                'CTX_GstCompanyInfo',
                'CTX_GstCompanyInfo.fetchCompanyInfo()',
                'Callout Failure',
                opportunityId,
                'Opportunity' 
            ));
            
             
            
        }
        
        if(!logFaliures.isEmpty()){
            Insert logFaliures;
        }
        
        return toastMessage;
        
    }
    
}