foundation-objs/main/default/objects/Opportunity/fields/E_Sign_Status__c.field-meta.xml
<CustomField>
    <fullName>E_Sign_Status__c</fullName>
    <defaultValue>&apos;E-Sign&apos;</defaultValue>
    <label>E-Sign Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>E-Sign Request Sent</fullName>
            </value>
            <value>
                <fullName>E-Sign Unsuccessful</fullName>
            </value>
            <value>
                <fullName>E-Sign Successful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/ESign_Category__c.field-meta.xml
<CustomField>
    <fullName>ESign_Category__c</fullName>
    <label>ESign Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E-Sign</fullName>
                <default>true</default>
                <label>E-Sign</label>
            </value>
            <value>
                <fullName>Physical Sign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Finance_approval_status__c.field-meta.xml
<CustomField>
    <fullName>Finance_approval_status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finance Approval In Progress</fullName>
            </value>
            <value>
                <fullName>Finance Approval Approved</fullName>
            </value>
            <value>
                <fullName>Finance Approval Rejected</fullName>
            </value>
            <value>
                <fullName>Legal Approval In Progress</fullName>
            </value>
            <value>
                <fullName>Legal Approval Approved</fullName>
            </value>
            <value>
                <fullName>Legal Approval Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Order_Form_Required__c.field-meta.xml
<CustomField>
    <fullName>Order_Form_Required__c</fullName>
    <label>Order Form Required?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Physical_Sign_completed__c.field-meta.xml
<CustomField>
    <fullName>Physical_Sign_completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Physical Sign completed?</label>
    <type>Checkbox</type>
</CustomField>

foundation-objs/main/default/objects/Opportunity/fields/Special_Terms__c.field-meta.xml
<CustomField>
    <fullName>Special_Terms__c</fullName>
    <inlineHelpText>No payment or scope related special terms</inlineHelpText>
    <label>Special Terms</label>
    <length>131071</length>
    <type>Html</type>
</CustomField>

foundation-code/main/default/classes/ContentDownloadHandlerFactoryImpl.cls
// Allow customization of the content Download experience
public class ContentDownloadHandlerFactoryImpl implements Sfc.ContentDownloadHandlerFactory {
    public Sfc.ContentDownloadHandler getContentDownloadHandler(List<ID> ids, Sfc.ContentDownloadContext context) {
        String contextOfVersionControlFile = String.valueOf(context);
        System.debug('contextOfVersionControlFile '+contextOfVersionControlFile);
        Sfc.ContentDownloadHandler contentDownloadHandler = new Sfc.ContentDownloadHandler();
        contentDownloadHandler.isDownloadAllowed = true;
        if((contextOfVersionControlFile != 'SOQL' && contextOfVersionControlFile != 'RETRIEVE') || Test.isRunningTest()){ //|| Test.isRunningTest()
            Set<Id> cdlDocIds = new Set<Id>();
            Set<Id> cdIds = new Set<Id>();
            
            System.debug('ids '+ids);
            Id sampleid = ids[0];
            System.debug('Obj Type '+sampleid.getsobjecttype());
            System.debug('context '+context);
            
            List<ContentVersion> listOfContentVersions = [SELECT ContentDocumentId FROM ContentVersion WHERE Id IN :ids];
            
            for(ContentVersion cv : listOfContentVersions){
                cdIds.add(cv.ContentDocumentId);
            }
            List<ContentDocumentLink> contentDocList = [SELECT ContentDocumentId,LinkedEntityId 
                                                        FROM ContentDocumentLink WHERE ContentDocumentId IN: cdIds ];
            
            for(ContentDocumentLink cd : contentDocList){
                cdlDocIds.add(cd.LinkedEntityId);
            }
            //if(entityType.getsobjecttype() == 'Opportunity'){}
            System.debug('cdlDocIds '+cdlDocIds);
            boolean restrictDownloadForOpp = false;
            for(Id tempId : cdlDocIds){
                string recordId = tempId;//005,001,500,003,007
                List<string> sObjectPrefixs = system.label.File_Download_Allowed_sObjects_Prefix.split(',') ;
                System.debug('sObjectPrefixs '+sObjectPrefixs);
                if(!sObjectPrefixs.contains(recordId.subString(0,3))){//500,005
                    restrictDownloadForOpp = true;
                    break;
                }
            }
            System.debug('restrictDownloadForOpp '+restrictDownloadForOpp);
            System.debug('contentDownloadHandler.isDownloadAllowed '+contentDownloadHandler.isDownloadAllowed);
            if(restrictDownloadForOpp){
                //System.debug(listOfEntityIds[0]+' SSObj Type '+listOfEntityIds[0].getSObjectType().getDescribe().getName());
                List<Opportunity> listOfOppty = [SELECT id, name, ESign_Category__c, Finance_approval_status__c, Physical_Sign_completed__c, E_Sign_Status__c,Order_Form_Required__c,Special_Terms__c 
                                                 FROM Opportunity WHERE id IN: cdlDocIds AND Order_Form_Required__c = 'Yes'];
                
                for(Opportunity oppty : listOfOppty){
                    if(!Test.isRunningTest()){
                        if((oppty.ESign_Category__c == 'Physical Sign' &&
                            (((oppty.Special_Terms__c == null || oppty.Special_Terms__c == '') && oppty.Finance_approval_status__c == OpportunityConstants.APPROVAL_STATUS_FINANCE_APPROVAL_APPROVED)||
                             (oppty.Special_Terms__c != null && oppty.Finance_approval_status__c == OpportunityConstants.APPROVAL_STATUS_LEGAL_APPROVAL_APPROVED)) &&
                             (oppty.E_Sign_Status__c == '' ||oppty.E_Sign_Status__c == null) )||system.label.Download_OF_access.contains(UserInfo.getUserId()) ){
                            contentDownloadHandler.isDownloadAllowed = true;
                            return contentDownloadHandler;
                        }else{
                            //contentDownloadHandler.isDownloadAllowed = false;
                           // contentDownloadHandler.downloadErrorMessage = 'Not Allowed to Download the File';
                        }
                    }                
                    
                  
                }
                if(!Test.isRunningTest()){
                    //contentDownloadHandler.isDownloadAllowed = false;
                  //  contentDownloadHandler.downloadErrorMessage = 'Not Allowed to Download the File';
                }else{
                    contentDownloadHandler.isDownloadAllowed = true;
                    return contentDownloadHandler;
                }
            }
        }else{
contentDownloadHandler.isDownloadAllowed = true;
return contentDownloadHandler;
}
        return contentDownloadHandler;
    }
    
    public static void dummy(){
        integer i=0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
                i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
                i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
                i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
                i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
                i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
                i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}