foundation-objs/main/default/objects/Qualifications_Questionnaire__c/Qualifications_Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Qualifications Questionnaire</label>
    <nameField>
        <displayFormat>QQ-{0000}</displayFormat>
        <label>Qualifications Questionnaire Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualifications Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

foundation-objs/main/default/objects/Qualifications_Questionnaire__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Qualifications Questionnaires</relationshipLabel>
    <relationshipName>Qualifications_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Qualifications_Questionnaire__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Qualifications Questionnaires</relationshipLabel>
    <relationshipName>Qualifications_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Qualifications_Questionnaire__c/fields/Parent_Questionnaires__c.field-meta.xml
<CustomField>
    <fullName>Parent_Questionnaires__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Questionnaires</label>
    <referenceTo>Qualifications_Questionnaire__c</referenceTo>
    <relationshipLabel>Parent Questionnaires</relationshipLabel>
    <relationshipName>Parent_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

foundation-objs/main/default/objects/Qualifications_Questionnaire__c/fields/Question_Related_To__c.field-meta.xml
<CustomField>
    <fullName>Question_Related_To__c</fullName>
    <inlineHelpText>Question Should be related to Account or Opportunity</inlineHelpText>
    <label>Question Related To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

foundation-objs/main/default/objects/Qualifications_Questionnaire__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <label>Questionnaire</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

foundation-code/main/default/classes/QuestionnaireFormController.cls
public without sharing class QuestionnaireFormController {
    @AuraEnabled(cacheable=true)
    Public static List<Qualifications_Questionnaire__c> getQuestionnaire(Id opportunityId){
        Id accountId = [SELECT Id from Account where Id = :opportunityId]?.Id;
        List<Qualifications_Questionnaire__c> masterQuestionnarieRecordList	= new List<Qualifications_Questionnaire__c>
            (
                [ SELECT Id, RecordTypeId, Questionnaire__c, Explanation__c, Remarks__c, Answer__c,
                 Opportunity__c, Account__c, Question_Related_To__c, Parent_Questionnaires__c
                 FROM Qualifications_Questionnaire__c WHERE
                 RecordType.Name = 'Record Specific' AND (Opportunity__c = :opportunityId OR Account__c = :accountId)]
            );
        System.debug('masterQuestionnarieRecordMap-->'+masterQuestionnarieRecordList);
        return masterQuestionnarieRecordList;
    }
}